/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ChannelOut,
  ConnectionIn,
  ConnectionOut,
  FeatureOut,
  GuildIn,
  GuildOut,
  GuildPlaytimeAnalysis,
  GuildUpdate,
  HTTPValidationError,
  InteractionIn,
  InteractionOut,
  ListInteractionsV1GuildsMeInteractionsGetParams,
  OnlineMember
} from '../model';

import { nexuscoreFetcher } from '../../../lib/nexuscore-fetcher';
import type { ErrorType } from '../../../lib/nexuscore-fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Creates a new guild. If a guild with this ID already exists, it returns a 400.
 * @summary Create Guild
 */
export const getCreateGuildV1GuildsPostUrl = () => {




  return `/v1/guilds`
}

export const createGuildV1GuildsPost = async (guildIn: GuildIn, options?: RequestInit): Promise<GuildOut> => {

  return nexuscoreFetcher<GuildOut>(getCreateGuildV1GuildsPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      guildIn,)
  }
);}




export const getCreateGuildV1GuildsPostMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createGuildV1GuildsPost>>, TError,{data: GuildIn}, TContext>, request?: SecondParameter<typeof nexuscoreFetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof createGuildV1GuildsPost>>, TError,{data: GuildIn}, TContext> => {

const mutationKey = ['createGuildV1GuildsPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createGuildV1GuildsPost>>, {data: GuildIn}> = (props) => {
          const {data} = props ?? {};

          return  createGuildV1GuildsPost(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateGuildV1GuildsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createGuildV1GuildsPost>>>
    export type CreateGuildV1GuildsPostMutationBody = GuildIn
    export type CreateGuildV1GuildsPostMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Create Guild
 */
export const useCreateGuildV1GuildsPost = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createGuildV1GuildsPost>>, TError,{data: GuildIn}, TContext>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createGuildV1GuildsPost>>,
        TError,
        {data: GuildIn},
        TContext
      > => {
      return useMutation(getCreateGuildV1GuildsPostMutationOptions(options), queryClient);
    }
    /**
 * Fetch your guild information
 * @summary Get Guild
 */
export const getGetGuildV1GuildsMeGetUrl = () => {




  return `/v1/guilds/me`
}

export const getGuildV1GuildsMeGet = async ( options?: RequestInit): Promise<GuildOut> => {

  return nexuscoreFetcher<GuildOut>(getGetGuildV1GuildsMeGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetGuildV1GuildsMeGetInfiniteQueryKey = () => {
    return [
    'infinite', `/v1/guilds/me`
    ] as const;
    }

export const getGetGuildV1GuildsMeGetQueryKey = () => {
    return [
    `/v1/guilds/me`
    ] as const;
    }


export const getGetGuildV1GuildsMeGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getGuildV1GuildsMeGet>>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getGuildV1GuildsMeGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGuildV1GuildsMeGetInfiniteQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGuildV1GuildsMeGet>>> = ({ signal }) => getGuildV1GuildsMeGet({ signal, ...requestOptions });





   return  { queryKey, queryFn,   staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getGuildV1GuildsMeGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetGuildV1GuildsMeGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getGuildV1GuildsMeGet>>>
export type GetGuildV1GuildsMeGetInfiniteQueryError = ErrorType<unknown>


export function useGetGuildV1GuildsMeGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getGuildV1GuildsMeGet>>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getGuildV1GuildsMeGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGuildV1GuildsMeGet>>,
          TError,
          Awaited<ReturnType<typeof getGuildV1GuildsMeGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGuildV1GuildsMeGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getGuildV1GuildsMeGet>>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getGuildV1GuildsMeGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGuildV1GuildsMeGet>>,
          TError,
          Awaited<ReturnType<typeof getGuildV1GuildsMeGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGuildV1GuildsMeGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getGuildV1GuildsMeGet>>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getGuildV1GuildsMeGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Guild
 */

export function useGetGuildV1GuildsMeGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getGuildV1GuildsMeGet>>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getGuildV1GuildsMeGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetGuildV1GuildsMeGetInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetGuildV1GuildsMeGetQueryOptions = <TData = Awaited<ReturnType<typeof getGuildV1GuildsMeGet>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGuildV1GuildsMeGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGuildV1GuildsMeGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGuildV1GuildsMeGet>>> = ({ signal }) => getGuildV1GuildsMeGet({ signal, ...requestOptions });





   return  { queryKey, queryFn,   staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getGuildV1GuildsMeGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetGuildV1GuildsMeGetQueryResult = NonNullable<Awaited<ReturnType<typeof getGuildV1GuildsMeGet>>>
export type GetGuildV1GuildsMeGetQueryError = ErrorType<unknown>


export function useGetGuildV1GuildsMeGet<TData = Awaited<ReturnType<typeof getGuildV1GuildsMeGet>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGuildV1GuildsMeGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGuildV1GuildsMeGet>>,
          TError,
          Awaited<ReturnType<typeof getGuildV1GuildsMeGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGuildV1GuildsMeGet<TData = Awaited<ReturnType<typeof getGuildV1GuildsMeGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGuildV1GuildsMeGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGuildV1GuildsMeGet>>,
          TError,
          Awaited<ReturnType<typeof getGuildV1GuildsMeGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGuildV1GuildsMeGet<TData = Awaited<ReturnType<typeof getGuildV1GuildsMeGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGuildV1GuildsMeGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Guild
 */

export function useGetGuildV1GuildsMeGet<TData = Awaited<ReturnType<typeof getGuildV1GuildsMeGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGuildV1GuildsMeGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetGuildV1GuildsMeGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Partially updates guild information. Both `PATCH` and `PUT` work the same way.
 * @summary Partial Update Guild
 */
export const getPartialUpdateGuildV1GuildsMePutUrl = () => {




  return `/v1/guilds/me`
}

export const partialUpdateGuildV1GuildsMePut = async (guildUpdate: GuildUpdate, options?: RequestInit): Promise<GuildOut> => {

  return nexuscoreFetcher<GuildOut>(getPartialUpdateGuildV1GuildsMePutUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      guildUpdate,)
  }
);}




export const getPartialUpdateGuildV1GuildsMePutMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof partialUpdateGuildV1GuildsMePut>>, TError,{data: GuildUpdate}, TContext>, request?: SecondParameter<typeof nexuscoreFetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof partialUpdateGuildV1GuildsMePut>>, TError,{data: GuildUpdate}, TContext> => {

const mutationKey = ['partialUpdateGuildV1GuildsMePut'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof partialUpdateGuildV1GuildsMePut>>, {data: GuildUpdate}> = (props) => {
          const {data} = props ?? {};

          return  partialUpdateGuildV1GuildsMePut(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PartialUpdateGuildV1GuildsMePutMutationResult = NonNullable<Awaited<ReturnType<typeof partialUpdateGuildV1GuildsMePut>>>
    export type PartialUpdateGuildV1GuildsMePutMutationBody = GuildUpdate
    export type PartialUpdateGuildV1GuildsMePutMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Partial Update Guild
 */
export const usePartialUpdateGuildV1GuildsMePut = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof partialUpdateGuildV1GuildsMePut>>, TError,{data: GuildUpdate}, TContext>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof partialUpdateGuildV1GuildsMePut>>,
        TError,
        {data: GuildUpdate},
        TContext
      > => {
      return useMutation(getPartialUpdateGuildV1GuildsMePutMutationOptions(options), queryClient);
    }
    /**
 * Partially updates guild information. Both `PATCH` and `PUT` work the same way.
 * @summary Partial Update Guild
 */
export const getPartialUpdateGuildV1GuildsMePatchUrl = () => {




  return `/v1/guilds/me`
}

export const partialUpdateGuildV1GuildsMePatch = async (guildUpdate: GuildUpdate, options?: RequestInit): Promise<GuildOut> => {

  return nexuscoreFetcher<GuildOut>(getPartialUpdateGuildV1GuildsMePatchUrl(),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      guildUpdate,)
  }
);}




export const getPartialUpdateGuildV1GuildsMePatchMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof partialUpdateGuildV1GuildsMePatch>>, TError,{data: GuildUpdate}, TContext>, request?: SecondParameter<typeof nexuscoreFetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof partialUpdateGuildV1GuildsMePatch>>, TError,{data: GuildUpdate}, TContext> => {

const mutationKey = ['partialUpdateGuildV1GuildsMePatch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof partialUpdateGuildV1GuildsMePatch>>, {data: GuildUpdate}> = (props) => {
          const {data} = props ?? {};

          return  partialUpdateGuildV1GuildsMePatch(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PartialUpdateGuildV1GuildsMePatchMutationResult = NonNullable<Awaited<ReturnType<typeof partialUpdateGuildV1GuildsMePatch>>>
    export type PartialUpdateGuildV1GuildsMePatchMutationBody = GuildUpdate
    export type PartialUpdateGuildV1GuildsMePatchMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Partial Update Guild
 */
export const usePartialUpdateGuildV1GuildsMePatch = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof partialUpdateGuildV1GuildsMePatch>>, TError,{data: GuildUpdate}, TContext>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof partialUpdateGuildV1GuildsMePatch>>,
        TError,
        {data: GuildUpdate},
        TContext
      > => {
      return useMutation(getPartialUpdateGuildV1GuildsMePatchMutationOptions(options), queryClient);
    }
    /**
 * Returns a list of features enabled for the authenticated guild.
 * @deprecated
 * @summary List Features
 */
export const getListFeaturesV1GuildsMeFeaturesGetUrl = () => {




  return `/v1/guilds/me/features`
}

export const listFeaturesV1GuildsMeFeaturesGet = async ( options?: RequestInit): Promise<FeatureOut[]> => {

  return nexuscoreFetcher<FeatureOut[]>(getListFeaturesV1GuildsMeFeaturesGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListFeaturesV1GuildsMeFeaturesGetInfiniteQueryKey = () => {
    return [
    'infinite', `/v1/guilds/me/features`
    ] as const;
    }

export const getListFeaturesV1GuildsMeFeaturesGetQueryKey = () => {
    return [
    `/v1/guilds/me/features`
    ] as const;
    }


export const getListFeaturesV1GuildsMeFeaturesGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof listFeaturesV1GuildsMeFeaturesGet>>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listFeaturesV1GuildsMeFeaturesGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListFeaturesV1GuildsMeFeaturesGetInfiniteQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listFeaturesV1GuildsMeFeaturesGet>>> = ({ signal }) => listFeaturesV1GuildsMeFeaturesGet({ signal, ...requestOptions });





   return  { queryKey, queryFn,   staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof listFeaturesV1GuildsMeFeaturesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListFeaturesV1GuildsMeFeaturesGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof listFeaturesV1GuildsMeFeaturesGet>>>
export type ListFeaturesV1GuildsMeFeaturesGetInfiniteQueryError = ErrorType<unknown>


export function useListFeaturesV1GuildsMeFeaturesGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listFeaturesV1GuildsMeFeaturesGet>>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listFeaturesV1GuildsMeFeaturesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFeaturesV1GuildsMeFeaturesGet>>,
          TError,
          Awaited<ReturnType<typeof listFeaturesV1GuildsMeFeaturesGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListFeaturesV1GuildsMeFeaturesGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listFeaturesV1GuildsMeFeaturesGet>>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listFeaturesV1GuildsMeFeaturesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFeaturesV1GuildsMeFeaturesGet>>,
          TError,
          Awaited<ReturnType<typeof listFeaturesV1GuildsMeFeaturesGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListFeaturesV1GuildsMeFeaturesGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listFeaturesV1GuildsMeFeaturesGet>>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listFeaturesV1GuildsMeFeaturesGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @deprecated
 * @summary List Features
 */

export function useListFeaturesV1GuildsMeFeaturesGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listFeaturesV1GuildsMeFeaturesGet>>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listFeaturesV1GuildsMeFeaturesGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListFeaturesV1GuildsMeFeaturesGetInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getListFeaturesV1GuildsMeFeaturesGetQueryOptions = <TData = Awaited<ReturnType<typeof listFeaturesV1GuildsMeFeaturesGet>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFeaturesV1GuildsMeFeaturesGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListFeaturesV1GuildsMeFeaturesGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listFeaturesV1GuildsMeFeaturesGet>>> = ({ signal }) => listFeaturesV1GuildsMeFeaturesGet({ signal, ...requestOptions });





   return  { queryKey, queryFn,   staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listFeaturesV1GuildsMeFeaturesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListFeaturesV1GuildsMeFeaturesGetQueryResult = NonNullable<Awaited<ReturnType<typeof listFeaturesV1GuildsMeFeaturesGet>>>
export type ListFeaturesV1GuildsMeFeaturesGetQueryError = ErrorType<unknown>


export function useListFeaturesV1GuildsMeFeaturesGet<TData = Awaited<ReturnType<typeof listFeaturesV1GuildsMeFeaturesGet>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFeaturesV1GuildsMeFeaturesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFeaturesV1GuildsMeFeaturesGet>>,
          TError,
          Awaited<ReturnType<typeof listFeaturesV1GuildsMeFeaturesGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListFeaturesV1GuildsMeFeaturesGet<TData = Awaited<ReturnType<typeof listFeaturesV1GuildsMeFeaturesGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFeaturesV1GuildsMeFeaturesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFeaturesV1GuildsMeFeaturesGet>>,
          TError,
          Awaited<ReturnType<typeof listFeaturesV1GuildsMeFeaturesGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListFeaturesV1GuildsMeFeaturesGet<TData = Awaited<ReturnType<typeof listFeaturesV1GuildsMeFeaturesGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFeaturesV1GuildsMeFeaturesGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @deprecated
 * @summary List Features
 */

export function useListFeaturesV1GuildsMeFeaturesGet<TData = Awaited<ReturnType<typeof listFeaturesV1GuildsMeFeaturesGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFeaturesV1GuildsMeFeaturesGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListFeaturesV1GuildsMeFeaturesGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * This returns a list of the guild's channels
 * @deprecated
 * @summary List Channels
 */
export const getListChannelsV1GuildsMeChannelsGetUrl = () => {




  return `/v1/guilds/me/channels`
}

export const listChannelsV1GuildsMeChannelsGet = async ( options?: RequestInit): Promise<ChannelOut[]> => {

  return nexuscoreFetcher<ChannelOut[]>(getListChannelsV1GuildsMeChannelsGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListChannelsV1GuildsMeChannelsGetInfiniteQueryKey = () => {
    return [
    'infinite', `/v1/guilds/me/channels`
    ] as const;
    }

export const getListChannelsV1GuildsMeChannelsGetQueryKey = () => {
    return [
    `/v1/guilds/me/channels`
    ] as const;
    }


export const getListChannelsV1GuildsMeChannelsGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof listChannelsV1GuildsMeChannelsGet>>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listChannelsV1GuildsMeChannelsGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListChannelsV1GuildsMeChannelsGetInfiniteQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listChannelsV1GuildsMeChannelsGet>>> = ({ signal }) => listChannelsV1GuildsMeChannelsGet({ signal, ...requestOptions });





   return  { queryKey, queryFn,   staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof listChannelsV1GuildsMeChannelsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListChannelsV1GuildsMeChannelsGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof listChannelsV1GuildsMeChannelsGet>>>
export type ListChannelsV1GuildsMeChannelsGetInfiniteQueryError = ErrorType<unknown>


export function useListChannelsV1GuildsMeChannelsGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listChannelsV1GuildsMeChannelsGet>>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listChannelsV1GuildsMeChannelsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listChannelsV1GuildsMeChannelsGet>>,
          TError,
          Awaited<ReturnType<typeof listChannelsV1GuildsMeChannelsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListChannelsV1GuildsMeChannelsGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listChannelsV1GuildsMeChannelsGet>>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listChannelsV1GuildsMeChannelsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listChannelsV1GuildsMeChannelsGet>>,
          TError,
          Awaited<ReturnType<typeof listChannelsV1GuildsMeChannelsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListChannelsV1GuildsMeChannelsGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listChannelsV1GuildsMeChannelsGet>>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listChannelsV1GuildsMeChannelsGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @deprecated
 * @summary List Channels
 */

export function useListChannelsV1GuildsMeChannelsGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listChannelsV1GuildsMeChannelsGet>>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listChannelsV1GuildsMeChannelsGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListChannelsV1GuildsMeChannelsGetInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getListChannelsV1GuildsMeChannelsGetQueryOptions = <TData = Awaited<ReturnType<typeof listChannelsV1GuildsMeChannelsGet>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listChannelsV1GuildsMeChannelsGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListChannelsV1GuildsMeChannelsGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listChannelsV1GuildsMeChannelsGet>>> = ({ signal }) => listChannelsV1GuildsMeChannelsGet({ signal, ...requestOptions });





   return  { queryKey, queryFn,   staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listChannelsV1GuildsMeChannelsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListChannelsV1GuildsMeChannelsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listChannelsV1GuildsMeChannelsGet>>>
export type ListChannelsV1GuildsMeChannelsGetQueryError = ErrorType<unknown>


export function useListChannelsV1GuildsMeChannelsGet<TData = Awaited<ReturnType<typeof listChannelsV1GuildsMeChannelsGet>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listChannelsV1GuildsMeChannelsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listChannelsV1GuildsMeChannelsGet>>,
          TError,
          Awaited<ReturnType<typeof listChannelsV1GuildsMeChannelsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListChannelsV1GuildsMeChannelsGet<TData = Awaited<ReturnType<typeof listChannelsV1GuildsMeChannelsGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listChannelsV1GuildsMeChannelsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listChannelsV1GuildsMeChannelsGet>>,
          TError,
          Awaited<ReturnType<typeof listChannelsV1GuildsMeChannelsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListChannelsV1GuildsMeChannelsGet<TData = Awaited<ReturnType<typeof listChannelsV1GuildsMeChannelsGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listChannelsV1GuildsMeChannelsGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @deprecated
 * @summary List Channels
 */

export function useListChannelsV1GuildsMeChannelsGet<TData = Awaited<ReturnType<typeof listChannelsV1GuildsMeChannelsGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listChannelsV1GuildsMeChannelsGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListChannelsV1GuildsMeChannelsGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * This returns the guild's playtime summary. Playtime is in seconds.

> [!warning]
> The playtime analysis is currently a work in progress, and may not have all data.
> Data shape might change in the future.
 * @summary Get Guild Playtime
 */
export const getGetGuildPlaytimeV1GuildsMePlaytimeGetUrl = () => {




  return `/v1/guilds/me/playtime`
}

export const getGuildPlaytimeV1GuildsMePlaytimeGet = async ( options?: RequestInit): Promise<GuildPlaytimeAnalysis> => {

  return nexuscoreFetcher<GuildPlaytimeAnalysis>(getGetGuildPlaytimeV1GuildsMePlaytimeGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetGuildPlaytimeV1GuildsMePlaytimeGetInfiniteQueryKey = () => {
    return [
    'infinite', `/v1/guilds/me/playtime`
    ] as const;
    }

export const getGetGuildPlaytimeV1GuildsMePlaytimeGetQueryKey = () => {
    return [
    `/v1/guilds/me/playtime`
    ] as const;
    }


export const getGetGuildPlaytimeV1GuildsMePlaytimeGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getGuildPlaytimeV1GuildsMePlaytimeGet>>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getGuildPlaytimeV1GuildsMePlaytimeGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGuildPlaytimeV1GuildsMePlaytimeGetInfiniteQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGuildPlaytimeV1GuildsMePlaytimeGet>>> = ({ signal }) => getGuildPlaytimeV1GuildsMePlaytimeGet({ signal, ...requestOptions });





   return  { queryKey, queryFn,   staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getGuildPlaytimeV1GuildsMePlaytimeGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetGuildPlaytimeV1GuildsMePlaytimeGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getGuildPlaytimeV1GuildsMePlaytimeGet>>>
export type GetGuildPlaytimeV1GuildsMePlaytimeGetInfiniteQueryError = ErrorType<unknown>


export function useGetGuildPlaytimeV1GuildsMePlaytimeGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getGuildPlaytimeV1GuildsMePlaytimeGet>>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getGuildPlaytimeV1GuildsMePlaytimeGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGuildPlaytimeV1GuildsMePlaytimeGet>>,
          TError,
          Awaited<ReturnType<typeof getGuildPlaytimeV1GuildsMePlaytimeGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGuildPlaytimeV1GuildsMePlaytimeGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getGuildPlaytimeV1GuildsMePlaytimeGet>>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getGuildPlaytimeV1GuildsMePlaytimeGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGuildPlaytimeV1GuildsMePlaytimeGet>>,
          TError,
          Awaited<ReturnType<typeof getGuildPlaytimeV1GuildsMePlaytimeGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGuildPlaytimeV1GuildsMePlaytimeGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getGuildPlaytimeV1GuildsMePlaytimeGet>>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getGuildPlaytimeV1GuildsMePlaytimeGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Guild Playtime
 */

export function useGetGuildPlaytimeV1GuildsMePlaytimeGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getGuildPlaytimeV1GuildsMePlaytimeGet>>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getGuildPlaytimeV1GuildsMePlaytimeGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetGuildPlaytimeV1GuildsMePlaytimeGetInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetGuildPlaytimeV1GuildsMePlaytimeGetQueryOptions = <TData = Awaited<ReturnType<typeof getGuildPlaytimeV1GuildsMePlaytimeGet>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGuildPlaytimeV1GuildsMePlaytimeGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGuildPlaytimeV1GuildsMePlaytimeGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGuildPlaytimeV1GuildsMePlaytimeGet>>> = ({ signal }) => getGuildPlaytimeV1GuildsMePlaytimeGet({ signal, ...requestOptions });





   return  { queryKey, queryFn,   staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getGuildPlaytimeV1GuildsMePlaytimeGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetGuildPlaytimeV1GuildsMePlaytimeGetQueryResult = NonNullable<Awaited<ReturnType<typeof getGuildPlaytimeV1GuildsMePlaytimeGet>>>
export type GetGuildPlaytimeV1GuildsMePlaytimeGetQueryError = ErrorType<unknown>


export function useGetGuildPlaytimeV1GuildsMePlaytimeGet<TData = Awaited<ReturnType<typeof getGuildPlaytimeV1GuildsMePlaytimeGet>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGuildPlaytimeV1GuildsMePlaytimeGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGuildPlaytimeV1GuildsMePlaytimeGet>>,
          TError,
          Awaited<ReturnType<typeof getGuildPlaytimeV1GuildsMePlaytimeGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGuildPlaytimeV1GuildsMePlaytimeGet<TData = Awaited<ReturnType<typeof getGuildPlaytimeV1GuildsMePlaytimeGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGuildPlaytimeV1GuildsMePlaytimeGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGuildPlaytimeV1GuildsMePlaytimeGet>>,
          TError,
          Awaited<ReturnType<typeof getGuildPlaytimeV1GuildsMePlaytimeGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGuildPlaytimeV1GuildsMePlaytimeGet<TData = Awaited<ReturnType<typeof getGuildPlaytimeV1GuildsMePlaytimeGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGuildPlaytimeV1GuildsMePlaytimeGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Guild Playtime
 */

export function useGetGuildPlaytimeV1GuildsMePlaytimeGet<TData = Awaited<ReturnType<typeof getGuildPlaytimeV1GuildsMePlaytimeGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGuildPlaytimeV1GuildsMePlaytimeGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetGuildPlaytimeV1GuildsMePlaytimeGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Returns a list of all players currently connected to Geode.
 * @summary Get Online Members
 */
export const getGetOnlineMembersV1GuildsMeOnlineGetUrl = () => {




  return `/v1/guilds/me/online`
}

export const getOnlineMembersV1GuildsMeOnlineGet = async ( options?: RequestInit): Promise<OnlineMember[]> => {

  return nexuscoreFetcher<OnlineMember[]>(getGetOnlineMembersV1GuildsMeOnlineGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetOnlineMembersV1GuildsMeOnlineGetInfiniteQueryKey = () => {
    return [
    'infinite', `/v1/guilds/me/online`
    ] as const;
    }

export const getGetOnlineMembersV1GuildsMeOnlineGetQueryKey = () => {
    return [
    `/v1/guilds/me/online`
    ] as const;
    }


export const getGetOnlineMembersV1GuildsMeOnlineGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getOnlineMembersV1GuildsMeOnlineGet>>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getOnlineMembersV1GuildsMeOnlineGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOnlineMembersV1GuildsMeOnlineGetInfiniteQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOnlineMembersV1GuildsMeOnlineGet>>> = ({ signal }) => getOnlineMembersV1GuildsMeOnlineGet({ signal, ...requestOptions });





   return  { queryKey, queryFn,   staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getOnlineMembersV1GuildsMeOnlineGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOnlineMembersV1GuildsMeOnlineGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getOnlineMembersV1GuildsMeOnlineGet>>>
export type GetOnlineMembersV1GuildsMeOnlineGetInfiniteQueryError = ErrorType<unknown>


export function useGetOnlineMembersV1GuildsMeOnlineGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getOnlineMembersV1GuildsMeOnlineGet>>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getOnlineMembersV1GuildsMeOnlineGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOnlineMembersV1GuildsMeOnlineGet>>,
          TError,
          Awaited<ReturnType<typeof getOnlineMembersV1GuildsMeOnlineGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOnlineMembersV1GuildsMeOnlineGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getOnlineMembersV1GuildsMeOnlineGet>>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getOnlineMembersV1GuildsMeOnlineGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOnlineMembersV1GuildsMeOnlineGet>>,
          TError,
          Awaited<ReturnType<typeof getOnlineMembersV1GuildsMeOnlineGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOnlineMembersV1GuildsMeOnlineGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getOnlineMembersV1GuildsMeOnlineGet>>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getOnlineMembersV1GuildsMeOnlineGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Online Members
 */

export function useGetOnlineMembersV1GuildsMeOnlineGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getOnlineMembersV1GuildsMeOnlineGet>>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getOnlineMembersV1GuildsMeOnlineGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOnlineMembersV1GuildsMeOnlineGetInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetOnlineMembersV1GuildsMeOnlineGetQueryOptions = <TData = Awaited<ReturnType<typeof getOnlineMembersV1GuildsMeOnlineGet>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOnlineMembersV1GuildsMeOnlineGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOnlineMembersV1GuildsMeOnlineGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOnlineMembersV1GuildsMeOnlineGet>>> = ({ signal }) => getOnlineMembersV1GuildsMeOnlineGet({ signal, ...requestOptions });





   return  { queryKey, queryFn,   staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOnlineMembersV1GuildsMeOnlineGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOnlineMembersV1GuildsMeOnlineGetQueryResult = NonNullable<Awaited<ReturnType<typeof getOnlineMembersV1GuildsMeOnlineGet>>>
export type GetOnlineMembersV1GuildsMeOnlineGetQueryError = ErrorType<unknown>


export function useGetOnlineMembersV1GuildsMeOnlineGet<TData = Awaited<ReturnType<typeof getOnlineMembersV1GuildsMeOnlineGet>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOnlineMembersV1GuildsMeOnlineGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOnlineMembersV1GuildsMeOnlineGet>>,
          TError,
          Awaited<ReturnType<typeof getOnlineMembersV1GuildsMeOnlineGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOnlineMembersV1GuildsMeOnlineGet<TData = Awaited<ReturnType<typeof getOnlineMembersV1GuildsMeOnlineGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOnlineMembersV1GuildsMeOnlineGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOnlineMembersV1GuildsMeOnlineGet>>,
          TError,
          Awaited<ReturnType<typeof getOnlineMembersV1GuildsMeOnlineGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOnlineMembersV1GuildsMeOnlineGet<TData = Awaited<ReturnType<typeof getOnlineMembersV1GuildsMeOnlineGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOnlineMembersV1GuildsMeOnlineGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Online Members
 */

export function useGetOnlineMembersV1GuildsMeOnlineGet<TData = Awaited<ReturnType<typeof getOnlineMembersV1GuildsMeOnlineGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOnlineMembersV1GuildsMeOnlineGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOnlineMembersV1GuildsMeOnlineGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Creates a connection event.
 * @summary Create Connection
 */
export const getCreateConnectionV1GuildsMeConnectionPostUrl = () => {




  return `/v1/guilds/me/connection`
}

export const createConnectionV1GuildsMeConnectionPost = async (connectionIn: ConnectionIn, options?: RequestInit): Promise<ConnectionOut> => {

  return nexuscoreFetcher<ConnectionOut>(getCreateConnectionV1GuildsMeConnectionPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      connectionIn,)
  }
);}




export const getCreateConnectionV1GuildsMeConnectionPostMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createConnectionV1GuildsMeConnectionPost>>, TError,{data: ConnectionIn}, TContext>, request?: SecondParameter<typeof nexuscoreFetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof createConnectionV1GuildsMeConnectionPost>>, TError,{data: ConnectionIn}, TContext> => {

const mutationKey = ['createConnectionV1GuildsMeConnectionPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createConnectionV1GuildsMeConnectionPost>>, {data: ConnectionIn}> = (props) => {
          const {data} = props ?? {};

          return  createConnectionV1GuildsMeConnectionPost(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateConnectionV1GuildsMeConnectionPostMutationResult = NonNullable<Awaited<ReturnType<typeof createConnectionV1GuildsMeConnectionPost>>>
    export type CreateConnectionV1GuildsMeConnectionPostMutationBody = ConnectionIn
    export type CreateConnectionV1GuildsMeConnectionPostMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Create Connection
 */
export const useCreateConnectionV1GuildsMeConnectionPost = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createConnectionV1GuildsMeConnectionPost>>, TError,{data: ConnectionIn}, TContext>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createConnectionV1GuildsMeConnectionPost>>,
        TError,
        {data: ConnectionIn},
        TContext
      > => {
      return useMutation(getCreateConnectionV1GuildsMeConnectionPostMutationOptions(options), queryClient);
    }
    /**
 * Creates an interaction event.
 * @summary Create Interaction
 */
export const getCreateInteractionV1GuildsMeInteractionPostUrl = () => {




  return `/v1/guilds/me/interaction`
}

export const createInteractionV1GuildsMeInteractionPost = async (interactionIn: InteractionIn, options?: RequestInit): Promise<InteractionOut> => {

  return nexuscoreFetcher<InteractionOut>(getCreateInteractionV1GuildsMeInteractionPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      interactionIn,)
  }
);}




export const getCreateInteractionV1GuildsMeInteractionPostMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createInteractionV1GuildsMeInteractionPost>>, TError,{data: InteractionIn}, TContext>, request?: SecondParameter<typeof nexuscoreFetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof createInteractionV1GuildsMeInteractionPost>>, TError,{data: InteractionIn}, TContext> => {

const mutationKey = ['createInteractionV1GuildsMeInteractionPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createInteractionV1GuildsMeInteractionPost>>, {data: InteractionIn}> = (props) => {
          const {data} = props ?? {};

          return  createInteractionV1GuildsMeInteractionPost(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateInteractionV1GuildsMeInteractionPostMutationResult = NonNullable<Awaited<ReturnType<typeof createInteractionV1GuildsMeInteractionPost>>>
    export type CreateInteractionV1GuildsMeInteractionPostMutationBody = InteractionIn
    export type CreateInteractionV1GuildsMeInteractionPostMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Create Interaction
 */
export const useCreateInteractionV1GuildsMeInteractionPost = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createInteractionV1GuildsMeInteractionPost>>, TError,{data: InteractionIn}, TContext>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createInteractionV1GuildsMeInteractionPost>>,
        TError,
        {data: InteractionIn},
        TContext
      > => {
      return useMutation(getCreateInteractionV1GuildsMeInteractionPostMutationOptions(options), queryClient);
    }
    /**
 * Filter interactions by various criteria.
 * @summary List Interactions
 */
export const getListInteractionsV1GuildsMeInteractionsGetUrl = (params?: ListInteractionsV1GuildsMeInteractionsGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/guilds/me/interactions?${stringifiedParams}` : `/v1/guilds/me/interactions`
}

export const listInteractionsV1GuildsMeInteractionsGet = async (params?: ListInteractionsV1GuildsMeInteractionsGetParams, options?: RequestInit): Promise<InteractionOut[]> => {

  return nexuscoreFetcher<InteractionOut[]>(getListInteractionsV1GuildsMeInteractionsGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListInteractionsV1GuildsMeInteractionsGetInfiniteQueryKey = (params?: ListInteractionsV1GuildsMeInteractionsGetParams,) => {
    return [
    'infinite', `/v1/guilds/me/interactions`, ...(params ? [params] : [])
    ] as const;
    }

export const getListInteractionsV1GuildsMeInteractionsGetQueryKey = (params?: ListInteractionsV1GuildsMeInteractionsGetParams,) => {
    return [
    `/v1/guilds/me/interactions`, ...(params ? [params] : [])
    ] as const;
    }


export const getListInteractionsV1GuildsMeInteractionsGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof listInteractionsV1GuildsMeInteractionsGet>>, ListInteractionsV1GuildsMeInteractionsGetParams['page']>, TError = ErrorType<HTTPValidationError>>(params?: ListInteractionsV1GuildsMeInteractionsGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listInteractionsV1GuildsMeInteractionsGet>>, TError, TData, QueryKey, ListInteractionsV1GuildsMeInteractionsGetParams['page']>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListInteractionsV1GuildsMeInteractionsGetInfiniteQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listInteractionsV1GuildsMeInteractionsGet>>, QueryKey, ListInteractionsV1GuildsMeInteractionsGetParams['page']> = ({ signal, pageParam }) => listInteractionsV1GuildsMeInteractionsGet({...params, 'page': pageParam || params?.['page']}, { signal, ...requestOptions });





   return  { queryKey, queryFn,   staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof listInteractionsV1GuildsMeInteractionsGet>>, TError, TData, QueryKey, ListInteractionsV1GuildsMeInteractionsGetParams['page']> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListInteractionsV1GuildsMeInteractionsGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof listInteractionsV1GuildsMeInteractionsGet>>>
export type ListInteractionsV1GuildsMeInteractionsGetInfiniteQueryError = ErrorType<HTTPValidationError>


export function useListInteractionsV1GuildsMeInteractionsGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listInteractionsV1GuildsMeInteractionsGet>>, ListInteractionsV1GuildsMeInteractionsGetParams['page']>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  ListInteractionsV1GuildsMeInteractionsGetParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listInteractionsV1GuildsMeInteractionsGet>>, TError, TData, QueryKey, ListInteractionsV1GuildsMeInteractionsGetParams['page']>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listInteractionsV1GuildsMeInteractionsGet>>,
          TError,
          Awaited<ReturnType<typeof listInteractionsV1GuildsMeInteractionsGet>>, QueryKey
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListInteractionsV1GuildsMeInteractionsGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listInteractionsV1GuildsMeInteractionsGet>>, ListInteractionsV1GuildsMeInteractionsGetParams['page']>, TError = ErrorType<HTTPValidationError>>(
 params?: ListInteractionsV1GuildsMeInteractionsGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listInteractionsV1GuildsMeInteractionsGet>>, TError, TData, QueryKey, ListInteractionsV1GuildsMeInteractionsGetParams['page']>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listInteractionsV1GuildsMeInteractionsGet>>,
          TError,
          Awaited<ReturnType<typeof listInteractionsV1GuildsMeInteractionsGet>>, QueryKey
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListInteractionsV1GuildsMeInteractionsGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listInteractionsV1GuildsMeInteractionsGet>>, ListInteractionsV1GuildsMeInteractionsGetParams['page']>, TError = ErrorType<HTTPValidationError>>(
 params?: ListInteractionsV1GuildsMeInteractionsGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listInteractionsV1GuildsMeInteractionsGet>>, TError, TData, QueryKey, ListInteractionsV1GuildsMeInteractionsGetParams['page']>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Interactions
 */

export function useListInteractionsV1GuildsMeInteractionsGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listInteractionsV1GuildsMeInteractionsGet>>, ListInteractionsV1GuildsMeInteractionsGetParams['page']>, TError = ErrorType<HTTPValidationError>>(
 params?: ListInteractionsV1GuildsMeInteractionsGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listInteractionsV1GuildsMeInteractionsGet>>, TError, TData, QueryKey, ListInteractionsV1GuildsMeInteractionsGetParams['page']>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListInteractionsV1GuildsMeInteractionsGetInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getListInteractionsV1GuildsMeInteractionsGetQueryOptions = <TData = Awaited<ReturnType<typeof listInteractionsV1GuildsMeInteractionsGet>>, TError = ErrorType<HTTPValidationError>>(params?: ListInteractionsV1GuildsMeInteractionsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listInteractionsV1GuildsMeInteractionsGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListInteractionsV1GuildsMeInteractionsGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listInteractionsV1GuildsMeInteractionsGet>>> = ({ signal }) => listInteractionsV1GuildsMeInteractionsGet(params, { signal, ...requestOptions });





   return  { queryKey, queryFn,   staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listInteractionsV1GuildsMeInteractionsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListInteractionsV1GuildsMeInteractionsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listInteractionsV1GuildsMeInteractionsGet>>>
export type ListInteractionsV1GuildsMeInteractionsGetQueryError = ErrorType<HTTPValidationError>


export function useListInteractionsV1GuildsMeInteractionsGet<TData = Awaited<ReturnType<typeof listInteractionsV1GuildsMeInteractionsGet>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  ListInteractionsV1GuildsMeInteractionsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listInteractionsV1GuildsMeInteractionsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listInteractionsV1GuildsMeInteractionsGet>>,
          TError,
          Awaited<ReturnType<typeof listInteractionsV1GuildsMeInteractionsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListInteractionsV1GuildsMeInteractionsGet<TData = Awaited<ReturnType<typeof listInteractionsV1GuildsMeInteractionsGet>>, TError = ErrorType<HTTPValidationError>>(
 params?: ListInteractionsV1GuildsMeInteractionsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listInteractionsV1GuildsMeInteractionsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listInteractionsV1GuildsMeInteractionsGet>>,
          TError,
          Awaited<ReturnType<typeof listInteractionsV1GuildsMeInteractionsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListInteractionsV1GuildsMeInteractionsGet<TData = Awaited<ReturnType<typeof listInteractionsV1GuildsMeInteractionsGet>>, TError = ErrorType<HTTPValidationError>>(
 params?: ListInteractionsV1GuildsMeInteractionsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listInteractionsV1GuildsMeInteractionsGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Interactions
 */

export function useListInteractionsV1GuildsMeInteractionsGet<TData = Awaited<ReturnType<typeof listInteractionsV1GuildsMeInteractionsGet>>, TError = ErrorType<HTTPValidationError>>(
 params?: ListInteractionsV1GuildsMeInteractionsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listInteractionsV1GuildsMeInteractionsGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListInteractionsV1GuildsMeInteractionsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






