/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  PresignIn,
  PresignOut
} from '../model';

import { nexuscoreFetcher } from '../../../lib/nexuscore-fetcher';
import type { ErrorType } from '../../../lib/nexuscore-fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get Presigned Upload Url
 */
export const getGetPresignedUploadUrlV1ImagesPresignPostUrl = () => {




  return `/v1/images/presign`
}

export const getPresignedUploadUrlV1ImagesPresignPost = async (presignIn: PresignIn, options?: RequestInit): Promise<PresignOut> => {

  return nexuscoreFetcher<PresignOut>(getGetPresignedUploadUrlV1ImagesPresignPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      presignIn,)
  }
);}




export const getGetPresignedUploadUrlV1ImagesPresignPostMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getPresignedUploadUrlV1ImagesPresignPost>>, TError,{data: PresignIn}, TContext>, request?: SecondParameter<typeof nexuscoreFetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof getPresignedUploadUrlV1ImagesPresignPost>>, TError,{data: PresignIn}, TContext> => {

const mutationKey = ['getPresignedUploadUrlV1ImagesPresignPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getPresignedUploadUrlV1ImagesPresignPost>>, {data: PresignIn}> = (props) => {
          const {data} = props ?? {};

          return  getPresignedUploadUrlV1ImagesPresignPost(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetPresignedUploadUrlV1ImagesPresignPostMutationResult = NonNullable<Awaited<ReturnType<typeof getPresignedUploadUrlV1ImagesPresignPost>>>
    export type GetPresignedUploadUrlV1ImagesPresignPostMutationBody = PresignIn
    export type GetPresignedUploadUrlV1ImagesPresignPostMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Get Presigned Upload Url
 */
export const useGetPresignedUploadUrlV1ImagesPresignPost = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getPresignedUploadUrlV1ImagesPresignPost>>, TError,{data: PresignIn}, TContext>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getPresignedUploadUrlV1ImagesPresignPost>>,
        TError,
        {data: PresignIn},
        TContext
      > => {
      return useMutation(getGetPresignedUploadUrlV1ImagesPresignPostMutationOptions(options), queryClient);
    }
