version: "3.9"
services:
  nextjs:
    build:
      context: ./
      dockerfile: nextjs.Dockerfile
    container_name: nextjs
    ports:
      - "3000:3000"
    restart: always
  nginx:
    container_name: 'nginx'
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem
      - /etc/letsencrypt/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
      - /etc/letsencrypt/live/everthorn.net/fullchain.pem:/etc/letsencrypt/live/everthorn.net/fullchain.pem
      - /etc/letsencrypt/live/everthorn.net/privkey.pem:/etc/letsencrypt/live/everthorn.net/privkey.pem
    restart: always