/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  InvalidateOptions,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  ProjectIn,
  ProjectOut,
  ProjectUpdate,
  StatusIn,
  StatusOut
} from '../model';

import { nexuscoreFetcher } from '../../../lib/nexuscore-fetcher.ts';
import type { ErrorType } from '../../../lib/nexuscore-fetcher.ts';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getListProjectsV1GuildsMeProjectsGetUrl = () => {




  return `/v1/guilds/me/projects`
}

/**
 * Get a list of Projects
 * @summary List Projects
 */
export const listProjectsV1GuildsMeProjectsGet = async ( options?: Parameters<typeof nexuscoreFetcher>[1]): Promise<ProjectOut[]> => {

  return nexuscoreFetcher<ProjectOut[]>(getListProjectsV1GuildsMeProjectsGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListProjectsV1GuildsMeProjectsGetQueryKey = () => {
    return [
    `/v1/guilds/me/projects`
    ] as const;
    }


export const getListProjectsV1GuildsMeProjectsGetQueryOptions = <TData = Awaited<ReturnType<typeof listProjectsV1GuildsMeProjectsGet>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProjectsV1GuildsMeProjectsGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListProjectsV1GuildsMeProjectsGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listProjectsV1GuildsMeProjectsGet>>> = ({ signal }) => listProjectsV1GuildsMeProjectsGet({ signal, ...requestOptions });





   return  { queryKey, queryFn,   staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listProjectsV1GuildsMeProjectsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListProjectsV1GuildsMeProjectsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listProjectsV1GuildsMeProjectsGet>>>
export type ListProjectsV1GuildsMeProjectsGetQueryError = ErrorType<unknown>


export function useListProjectsV1GuildsMeProjectsGet<TData = Awaited<ReturnType<typeof listProjectsV1GuildsMeProjectsGet>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProjectsV1GuildsMeProjectsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listProjectsV1GuildsMeProjectsGet>>,
          TError,
          Awaited<ReturnType<typeof listProjectsV1GuildsMeProjectsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListProjectsV1GuildsMeProjectsGet<TData = Awaited<ReturnType<typeof listProjectsV1GuildsMeProjectsGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProjectsV1GuildsMeProjectsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listProjectsV1GuildsMeProjectsGet>>,
          TError,
          Awaited<ReturnType<typeof listProjectsV1GuildsMeProjectsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListProjectsV1GuildsMeProjectsGet<TData = Awaited<ReturnType<typeof listProjectsV1GuildsMeProjectsGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProjectsV1GuildsMeProjectsGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Projects
 */

export function useListProjectsV1GuildsMeProjectsGet<TData = Awaited<ReturnType<typeof listProjectsV1GuildsMeProjectsGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProjectsV1GuildsMeProjectsGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListProjectsV1GuildsMeProjectsGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}


/**
 * @summary List Projects
 */
export const invalidateListProjectsV1GuildsMeProjectsGet = async (
 queryClient: QueryClient,  options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getListProjectsV1GuildsMeProjectsGetQueryKey() }, options);

  return queryClient;
}




export const getCreateProjectV1GuildsMeProjectsPostUrl = () => {




  return `/v1/guilds/me/projects`
}

/**
 * Creates a new project with a status, members and content.
 * @summary Create Project
 */
export const createProjectV1GuildsMeProjectsPost = async (projectIn: ProjectIn, options?: Parameters<typeof nexuscoreFetcher>[1]): Promise<ProjectOut> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return nexuscoreFetcher<ProjectOut>(getCreateProjectV1GuildsMeProjectsPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(projectIn)
  }
);}





export const getCreateProjectV1GuildsMeProjectsPostQueryKey = (projectIn?: ProjectIn,) => {
    return [
    'POST', `/v1/guilds/me/projects`, projectIn
    ] as const;
    }


export const getCreateProjectV1GuildsMeProjectsPostQueryOptions = <TData = Awaited<ReturnType<typeof createProjectV1GuildsMeProjectsPost>>, TError = ErrorType<HTTPValidationError>>(projectIn: ProjectIn, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createProjectV1GuildsMeProjectsPost>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCreateProjectV1GuildsMeProjectsPostQueryKey(projectIn);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof createProjectV1GuildsMeProjectsPost>>> = ({ signal }) => createProjectV1GuildsMeProjectsPost(projectIn, { signal, ...requestOptions });





   return  { queryKey, queryFn,   staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof createProjectV1GuildsMeProjectsPost>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CreateProjectV1GuildsMeProjectsPostQueryResult = NonNullable<Awaited<ReturnType<typeof createProjectV1GuildsMeProjectsPost>>>
export type CreateProjectV1GuildsMeProjectsPostQueryError = ErrorType<HTTPValidationError>


export function useCreateProjectV1GuildsMeProjectsPost<TData = Awaited<ReturnType<typeof createProjectV1GuildsMeProjectsPost>>, TError = ErrorType<HTTPValidationError>>(
 projectIn: ProjectIn, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof createProjectV1GuildsMeProjectsPost>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof createProjectV1GuildsMeProjectsPost>>,
          TError,
          Awaited<ReturnType<typeof createProjectV1GuildsMeProjectsPost>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreateProjectV1GuildsMeProjectsPost<TData = Awaited<ReturnType<typeof createProjectV1GuildsMeProjectsPost>>, TError = ErrorType<HTTPValidationError>>(
 projectIn: ProjectIn, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createProjectV1GuildsMeProjectsPost>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof createProjectV1GuildsMeProjectsPost>>,
          TError,
          Awaited<ReturnType<typeof createProjectV1GuildsMeProjectsPost>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreateProjectV1GuildsMeProjectsPost<TData = Awaited<ReturnType<typeof createProjectV1GuildsMeProjectsPost>>, TError = ErrorType<HTTPValidationError>>(
 projectIn: ProjectIn, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createProjectV1GuildsMeProjectsPost>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Create Project
 */

export function useCreateProjectV1GuildsMeProjectsPost<TData = Awaited<ReturnType<typeof createProjectV1GuildsMeProjectsPost>>, TError = ErrorType<HTTPValidationError>>(
 projectIn: ProjectIn, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createProjectV1GuildsMeProjectsPost>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCreateProjectV1GuildsMeProjectsPostQueryOptions(projectIn,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}


/**
 * @summary Create Project
 */
export const invalidateCreateProjectV1GuildsMeProjectsPost = async (
 queryClient: QueryClient, projectIn: ProjectIn, options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getCreateProjectV1GuildsMeProjectsPostQueryKey(projectIn) }, options);

  return queryClient;
}




export const getGetProjectV1GuildsMeProjectsProjectIdGetUrl = (projectId: string,) => {




  return `/v1/guilds/me/projects/${projectId}`
}

/**
 * Returns the project specified
 * @summary Get Project
 */
export const getProjectV1GuildsMeProjectsProjectIdGet = async (projectId: string, options?: Parameters<typeof nexuscoreFetcher>[1]): Promise<ProjectOut> => {

  return nexuscoreFetcher<ProjectOut>(getGetProjectV1GuildsMeProjectsProjectIdGetUrl(projectId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetProjectV1GuildsMeProjectsProjectIdGetQueryKey = (projectId: string,) => {
    return [
    `/v1/guilds/me/projects/${projectId}`
    ] as const;
    }


export const getGetProjectV1GuildsMeProjectsProjectIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getProjectV1GuildsMeProjectsProjectIdGet>>, TError = ErrorType<HTTPValidationError>>(projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectV1GuildsMeProjectsProjectIdGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProjectV1GuildsMeProjectsProjectIdGetQueryKey(projectId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProjectV1GuildsMeProjectsProjectIdGet>>> = ({ signal }) => getProjectV1GuildsMeProjectsProjectIdGet(projectId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: projectId !== null && projectId !== undefined,  staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProjectV1GuildsMeProjectsProjectIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProjectV1GuildsMeProjectsProjectIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getProjectV1GuildsMeProjectsProjectIdGet>>>
export type GetProjectV1GuildsMeProjectsProjectIdGetQueryError = ErrorType<HTTPValidationError>


export function useGetProjectV1GuildsMeProjectsProjectIdGet<TData = Awaited<ReturnType<typeof getProjectV1GuildsMeProjectsProjectIdGet>>, TError = ErrorType<HTTPValidationError>>(
 projectId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectV1GuildsMeProjectsProjectIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectV1GuildsMeProjectsProjectIdGet>>,
          TError,
          Awaited<ReturnType<typeof getProjectV1GuildsMeProjectsProjectIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProjectV1GuildsMeProjectsProjectIdGet<TData = Awaited<ReturnType<typeof getProjectV1GuildsMeProjectsProjectIdGet>>, TError = ErrorType<HTTPValidationError>>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectV1GuildsMeProjectsProjectIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectV1GuildsMeProjectsProjectIdGet>>,
          TError,
          Awaited<ReturnType<typeof getProjectV1GuildsMeProjectsProjectIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProjectV1GuildsMeProjectsProjectIdGet<TData = Awaited<ReturnType<typeof getProjectV1GuildsMeProjectsProjectIdGet>>, TError = ErrorType<HTTPValidationError>>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectV1GuildsMeProjectsProjectIdGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Project
 */

export function useGetProjectV1GuildsMeProjectsProjectIdGet<TData = Awaited<ReturnType<typeof getProjectV1GuildsMeProjectsProjectIdGet>>, TError = ErrorType<HTTPValidationError>>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectV1GuildsMeProjectsProjectIdGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProjectV1GuildsMeProjectsProjectIdGetQueryOptions(projectId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}


/**
 * @summary Get Project
 */
export const invalidateGetProjectV1GuildsMeProjectsProjectIdGet = async (
 queryClient: QueryClient, projectId: string, options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getGetProjectV1GuildsMeProjectsProjectIdGetQueryKey(projectId) }, options);

  return queryClient;
}




export const getPartialUpdateProjectV1GuildsMeProjectsProjectIdPatchUrl = (projectId: string,) => {




  return `/v1/guilds/me/projects/${projectId}`
}

/**
 * Update the project.
 * @summary Partial Update Project
 */
export const partialUpdateProjectV1GuildsMeProjectsProjectIdPatch = async (projectId: string,
    projectUpdate: ProjectUpdate, options?: Parameters<typeof nexuscoreFetcher>[1]): Promise<ProjectOut> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return nexuscoreFetcher<ProjectOut>(getPartialUpdateProjectV1GuildsMeProjectsProjectIdPatchUrl(projectId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(projectUpdate)
  }
);}





export const getPartialUpdateProjectV1GuildsMeProjectsProjectIdPatchQueryKey = (projectId: string,
    projectUpdate?: ProjectUpdate,) => {
    return [
    'PATCH', `/v1/guilds/me/projects/${projectId}`, projectUpdate
    ] as const;
    }


export const getPartialUpdateProjectV1GuildsMeProjectsProjectIdPatchQueryOptions = <TData = Awaited<ReturnType<typeof partialUpdateProjectV1GuildsMeProjectsProjectIdPatch>>, TError = ErrorType<HTTPValidationError>>(projectId: string,
    projectUpdate: ProjectUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateProjectV1GuildsMeProjectsProjectIdPatch>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPartialUpdateProjectV1GuildsMeProjectsProjectIdPatchQueryKey(projectId,projectUpdate);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof partialUpdateProjectV1GuildsMeProjectsProjectIdPatch>>> = ({ signal }) => partialUpdateProjectV1GuildsMeProjectsProjectIdPatch(projectId,projectUpdate, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: projectId !== null && projectId !== undefined,  staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof partialUpdateProjectV1GuildsMeProjectsProjectIdPatch>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PartialUpdateProjectV1GuildsMeProjectsProjectIdPatchQueryResult = NonNullable<Awaited<ReturnType<typeof partialUpdateProjectV1GuildsMeProjectsProjectIdPatch>>>
export type PartialUpdateProjectV1GuildsMeProjectsProjectIdPatchQueryError = ErrorType<HTTPValidationError>


export function usePartialUpdateProjectV1GuildsMeProjectsProjectIdPatch<TData = Awaited<ReturnType<typeof partialUpdateProjectV1GuildsMeProjectsProjectIdPatch>>, TError = ErrorType<HTTPValidationError>>(
 projectId: string,
    projectUpdate: ProjectUpdate, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateProjectV1GuildsMeProjectsProjectIdPatch>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof partialUpdateProjectV1GuildsMeProjectsProjectIdPatch>>,
          TError,
          Awaited<ReturnType<typeof partialUpdateProjectV1GuildsMeProjectsProjectIdPatch>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePartialUpdateProjectV1GuildsMeProjectsProjectIdPatch<TData = Awaited<ReturnType<typeof partialUpdateProjectV1GuildsMeProjectsProjectIdPatch>>, TError = ErrorType<HTTPValidationError>>(
 projectId: string,
    projectUpdate: ProjectUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateProjectV1GuildsMeProjectsProjectIdPatch>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof partialUpdateProjectV1GuildsMeProjectsProjectIdPatch>>,
          TError,
          Awaited<ReturnType<typeof partialUpdateProjectV1GuildsMeProjectsProjectIdPatch>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePartialUpdateProjectV1GuildsMeProjectsProjectIdPatch<TData = Awaited<ReturnType<typeof partialUpdateProjectV1GuildsMeProjectsProjectIdPatch>>, TError = ErrorType<HTTPValidationError>>(
 projectId: string,
    projectUpdate: ProjectUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateProjectV1GuildsMeProjectsProjectIdPatch>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Partial Update Project
 */

export function usePartialUpdateProjectV1GuildsMeProjectsProjectIdPatch<TData = Awaited<ReturnType<typeof partialUpdateProjectV1GuildsMeProjectsProjectIdPatch>>, TError = ErrorType<HTTPValidationError>>(
 projectId: string,
    projectUpdate: ProjectUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateProjectV1GuildsMeProjectsProjectIdPatch>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPartialUpdateProjectV1GuildsMeProjectsProjectIdPatchQueryOptions(projectId,projectUpdate,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}


/**
 * @summary Partial Update Project
 */
export const invalidatePartialUpdateProjectV1GuildsMeProjectsProjectIdPatch = async (
 queryClient: QueryClient, projectId: string,
    projectUpdate: ProjectUpdate, options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getPartialUpdateProjectV1GuildsMeProjectsProjectIdPatchQueryKey(projectId,projectUpdate) }, options);

  return queryClient;
}




export const getPartialUpdateProjectV1GuildsMeProjectsProjectIdPutUrl = (projectId: string,) => {




  return `/v1/guilds/me/projects/${projectId}`
}

/**
 * Update the project.
 * @summary Partial Update Project
 */
export const partialUpdateProjectV1GuildsMeProjectsProjectIdPut = async (projectId: string,
    projectUpdate: ProjectUpdate, options?: Parameters<typeof nexuscoreFetcher>[1]): Promise<ProjectOut> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return nexuscoreFetcher<ProjectOut>(getPartialUpdateProjectV1GuildsMeProjectsProjectIdPutUrl(projectId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(projectUpdate)
  }
);}





export const getPartialUpdateProjectV1GuildsMeProjectsProjectIdPutQueryKey = (projectId: string,
    projectUpdate?: ProjectUpdate,) => {
    return [
    'PUT', `/v1/guilds/me/projects/${projectId}`, projectUpdate
    ] as const;
    }


export const getPartialUpdateProjectV1GuildsMeProjectsProjectIdPutQueryOptions = <TData = Awaited<ReturnType<typeof partialUpdateProjectV1GuildsMeProjectsProjectIdPut>>, TError = ErrorType<HTTPValidationError>>(projectId: string,
    projectUpdate: ProjectUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateProjectV1GuildsMeProjectsProjectIdPut>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPartialUpdateProjectV1GuildsMeProjectsProjectIdPutQueryKey(projectId,projectUpdate);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof partialUpdateProjectV1GuildsMeProjectsProjectIdPut>>> = ({ signal }) => partialUpdateProjectV1GuildsMeProjectsProjectIdPut(projectId,projectUpdate, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: projectId !== null && projectId !== undefined,  staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof partialUpdateProjectV1GuildsMeProjectsProjectIdPut>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PartialUpdateProjectV1GuildsMeProjectsProjectIdPutQueryResult = NonNullable<Awaited<ReturnType<typeof partialUpdateProjectV1GuildsMeProjectsProjectIdPut>>>
export type PartialUpdateProjectV1GuildsMeProjectsProjectIdPutQueryError = ErrorType<HTTPValidationError>


export function usePartialUpdateProjectV1GuildsMeProjectsProjectIdPut<TData = Awaited<ReturnType<typeof partialUpdateProjectV1GuildsMeProjectsProjectIdPut>>, TError = ErrorType<HTTPValidationError>>(
 projectId: string,
    projectUpdate: ProjectUpdate, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateProjectV1GuildsMeProjectsProjectIdPut>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof partialUpdateProjectV1GuildsMeProjectsProjectIdPut>>,
          TError,
          Awaited<ReturnType<typeof partialUpdateProjectV1GuildsMeProjectsProjectIdPut>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePartialUpdateProjectV1GuildsMeProjectsProjectIdPut<TData = Awaited<ReturnType<typeof partialUpdateProjectV1GuildsMeProjectsProjectIdPut>>, TError = ErrorType<HTTPValidationError>>(
 projectId: string,
    projectUpdate: ProjectUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateProjectV1GuildsMeProjectsProjectIdPut>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof partialUpdateProjectV1GuildsMeProjectsProjectIdPut>>,
          TError,
          Awaited<ReturnType<typeof partialUpdateProjectV1GuildsMeProjectsProjectIdPut>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePartialUpdateProjectV1GuildsMeProjectsProjectIdPut<TData = Awaited<ReturnType<typeof partialUpdateProjectV1GuildsMeProjectsProjectIdPut>>, TError = ErrorType<HTTPValidationError>>(
 projectId: string,
    projectUpdate: ProjectUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateProjectV1GuildsMeProjectsProjectIdPut>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Partial Update Project
 */

export function usePartialUpdateProjectV1GuildsMeProjectsProjectIdPut<TData = Awaited<ReturnType<typeof partialUpdateProjectV1GuildsMeProjectsProjectIdPut>>, TError = ErrorType<HTTPValidationError>>(
 projectId: string,
    projectUpdate: ProjectUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateProjectV1GuildsMeProjectsProjectIdPut>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPartialUpdateProjectV1GuildsMeProjectsProjectIdPutQueryOptions(projectId,projectUpdate,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}


/**
 * @summary Partial Update Project
 */
export const invalidatePartialUpdateProjectV1GuildsMeProjectsProjectIdPut = async (
 queryClient: QueryClient, projectId: string,
    projectUpdate: ProjectUpdate, options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getPartialUpdateProjectV1GuildsMeProjectsProjectIdPutQueryKey(projectId,projectUpdate) }, options);

  return queryClient;
}




export const getGetProjectStatusV1GuildsMeProjectsProjectIdStatusGetUrl = (projectId: string,) => {




  return `/v1/guilds/me/projects/${projectId}/status`
}

/**
 * Returns the project's status
 * @deprecated
 * @summary Get Project Status
 */
export const getProjectStatusV1GuildsMeProjectsProjectIdStatusGet = async (projectId: string, options?: Parameters<typeof nexuscoreFetcher>[1]): Promise<StatusOut> => {

  return nexuscoreFetcher<StatusOut>(getGetProjectStatusV1GuildsMeProjectsProjectIdStatusGetUrl(projectId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetProjectStatusV1GuildsMeProjectsProjectIdStatusGetQueryKey = (projectId: string,) => {
    return [
    `/v1/guilds/me/projects/${projectId}/status`
    ] as const;
    }


export const getGetProjectStatusV1GuildsMeProjectsProjectIdStatusGetQueryOptions = <TData = Awaited<ReturnType<typeof getProjectStatusV1GuildsMeProjectsProjectIdStatusGet>>, TError = ErrorType<HTTPValidationError>>(projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectStatusV1GuildsMeProjectsProjectIdStatusGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProjectStatusV1GuildsMeProjectsProjectIdStatusGetQueryKey(projectId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProjectStatusV1GuildsMeProjectsProjectIdStatusGet>>> = ({ signal }) => getProjectStatusV1GuildsMeProjectsProjectIdStatusGet(projectId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: projectId !== null && projectId !== undefined,  staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProjectStatusV1GuildsMeProjectsProjectIdStatusGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProjectStatusV1GuildsMeProjectsProjectIdStatusGetQueryResult = NonNullable<Awaited<ReturnType<typeof getProjectStatusV1GuildsMeProjectsProjectIdStatusGet>>>
export type GetProjectStatusV1GuildsMeProjectsProjectIdStatusGetQueryError = ErrorType<HTTPValidationError>


export function useGetProjectStatusV1GuildsMeProjectsProjectIdStatusGet<TData = Awaited<ReturnType<typeof getProjectStatusV1GuildsMeProjectsProjectIdStatusGet>>, TError = ErrorType<HTTPValidationError>>(
 projectId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectStatusV1GuildsMeProjectsProjectIdStatusGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectStatusV1GuildsMeProjectsProjectIdStatusGet>>,
          TError,
          Awaited<ReturnType<typeof getProjectStatusV1GuildsMeProjectsProjectIdStatusGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProjectStatusV1GuildsMeProjectsProjectIdStatusGet<TData = Awaited<ReturnType<typeof getProjectStatusV1GuildsMeProjectsProjectIdStatusGet>>, TError = ErrorType<HTTPValidationError>>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectStatusV1GuildsMeProjectsProjectIdStatusGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectStatusV1GuildsMeProjectsProjectIdStatusGet>>,
          TError,
          Awaited<ReturnType<typeof getProjectStatusV1GuildsMeProjectsProjectIdStatusGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProjectStatusV1GuildsMeProjectsProjectIdStatusGet<TData = Awaited<ReturnType<typeof getProjectStatusV1GuildsMeProjectsProjectIdStatusGet>>, TError = ErrorType<HTTPValidationError>>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectStatusV1GuildsMeProjectsProjectIdStatusGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @deprecated
 * @summary Get Project Status
 */

export function useGetProjectStatusV1GuildsMeProjectsProjectIdStatusGet<TData = Awaited<ReturnType<typeof getProjectStatusV1GuildsMeProjectsProjectIdStatusGet>>, TError = ErrorType<HTTPValidationError>>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectStatusV1GuildsMeProjectsProjectIdStatusGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProjectStatusV1GuildsMeProjectsProjectIdStatusGetQueryOptions(projectId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}


/**
 * @deprecated
 * @summary Get Project Status
 */
export const invalidateGetProjectStatusV1GuildsMeProjectsProjectIdStatusGet = async (
 queryClient: QueryClient, projectId: string, options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getGetProjectStatusV1GuildsMeProjectsProjectIdStatusGetQueryKey(projectId) }, options);

  return queryClient;
}




export const getCreateProjectStatusV1GuildsMeProjectsProjectIdStatusPostUrl = (projectId: string,) => {




  return `/v1/guilds/me/projects/${projectId}/status`
}

/**
 * New Project Status
 *
 * Insert a new project status.
 * @summary Create Project Status
 */
export const createProjectStatusV1GuildsMeProjectsProjectIdStatusPost = async (projectId: string,
    statusIn: StatusIn, options?: Parameters<typeof nexuscoreFetcher>[1]): Promise<StatusOut> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return nexuscoreFetcher<StatusOut>(getCreateProjectStatusV1GuildsMeProjectsProjectIdStatusPostUrl(projectId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(statusIn)
  }
);}





export const getCreateProjectStatusV1GuildsMeProjectsProjectIdStatusPostQueryKey = (projectId: string,
    statusIn?: StatusIn,) => {
    return [
    'POST', `/v1/guilds/me/projects/${projectId}/status`, statusIn
    ] as const;
    }


export const getCreateProjectStatusV1GuildsMeProjectsProjectIdStatusPostQueryOptions = <TData = Awaited<ReturnType<typeof createProjectStatusV1GuildsMeProjectsProjectIdStatusPost>>, TError = ErrorType<HTTPValidationError>>(projectId: string,
    statusIn: StatusIn, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createProjectStatusV1GuildsMeProjectsProjectIdStatusPost>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCreateProjectStatusV1GuildsMeProjectsProjectIdStatusPostQueryKey(projectId,statusIn);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof createProjectStatusV1GuildsMeProjectsProjectIdStatusPost>>> = ({ signal }) => createProjectStatusV1GuildsMeProjectsProjectIdStatusPost(projectId,statusIn, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: projectId !== null && projectId !== undefined,  staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof createProjectStatusV1GuildsMeProjectsProjectIdStatusPost>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CreateProjectStatusV1GuildsMeProjectsProjectIdStatusPostQueryResult = NonNullable<Awaited<ReturnType<typeof createProjectStatusV1GuildsMeProjectsProjectIdStatusPost>>>
export type CreateProjectStatusV1GuildsMeProjectsProjectIdStatusPostQueryError = ErrorType<HTTPValidationError>


export function useCreateProjectStatusV1GuildsMeProjectsProjectIdStatusPost<TData = Awaited<ReturnType<typeof createProjectStatusV1GuildsMeProjectsProjectIdStatusPost>>, TError = ErrorType<HTTPValidationError>>(
 projectId: string,
    statusIn: StatusIn, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof createProjectStatusV1GuildsMeProjectsProjectIdStatusPost>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof createProjectStatusV1GuildsMeProjectsProjectIdStatusPost>>,
          TError,
          Awaited<ReturnType<typeof createProjectStatusV1GuildsMeProjectsProjectIdStatusPost>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreateProjectStatusV1GuildsMeProjectsProjectIdStatusPost<TData = Awaited<ReturnType<typeof createProjectStatusV1GuildsMeProjectsProjectIdStatusPost>>, TError = ErrorType<HTTPValidationError>>(
 projectId: string,
    statusIn: StatusIn, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createProjectStatusV1GuildsMeProjectsProjectIdStatusPost>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof createProjectStatusV1GuildsMeProjectsProjectIdStatusPost>>,
          TError,
          Awaited<ReturnType<typeof createProjectStatusV1GuildsMeProjectsProjectIdStatusPost>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreateProjectStatusV1GuildsMeProjectsProjectIdStatusPost<TData = Awaited<ReturnType<typeof createProjectStatusV1GuildsMeProjectsProjectIdStatusPost>>, TError = ErrorType<HTTPValidationError>>(
 projectId: string,
    statusIn: StatusIn, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createProjectStatusV1GuildsMeProjectsProjectIdStatusPost>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Create Project Status
 */

export function useCreateProjectStatusV1GuildsMeProjectsProjectIdStatusPost<TData = Awaited<ReturnType<typeof createProjectStatusV1GuildsMeProjectsProjectIdStatusPost>>, TError = ErrorType<HTTPValidationError>>(
 projectId: string,
    statusIn: StatusIn, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createProjectStatusV1GuildsMeProjectsProjectIdStatusPost>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCreateProjectStatusV1GuildsMeProjectsProjectIdStatusPostQueryOptions(projectId,statusIn,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}


/**
 * @summary Create Project Status
 */
export const invalidateCreateProjectStatusV1GuildsMeProjectsProjectIdStatusPost = async (
 queryClient: QueryClient, projectId: string,
    statusIn: StatusIn, options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getCreateProjectStatusV1GuildsMeProjectsProjectIdStatusPostQueryKey(projectId,statusIn) }, options);

  return queryClient;
}




