/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  InvalidateOptions,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  ListQuestsV1GuildsMeQuestsGetParams,
  QuestIn,
  QuestOut,
  QuestProgressIn,
  QuestProgressOut,
  QuestProgressUpdate,
  QuestStatisticsOut,
  QuestUpdate
} from '../model';

import { nexuscoreFetcher } from '../../../lib/nexuscore-fetcher.ts';
import type { ErrorType } from '../../../lib/nexuscore-fetcher.ts';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getCreateQuestV1GuildsMeQuestsPostUrl = () => {




  return `/v1/guilds/me/quests`
}

/**
 * Create New Quest
 *
 * Creates a new quest based on the information provided.
 * Some fields are optional and can be `null` while others are required.
 * Check the schema for more info on that.
 * @summary Create Quest
 */
export const createQuestV1GuildsMeQuestsPost = async (questIn: QuestIn, options?: Parameters<typeof nexuscoreFetcher>[1]): Promise<QuestOut> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return nexuscoreFetcher<QuestOut>(getCreateQuestV1GuildsMeQuestsPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(questIn)
  }
);}





export const getCreateQuestV1GuildsMeQuestsPostQueryKey = (questIn?: QuestIn,) => {
    return [
    'POST', `/v1/guilds/me/quests`, questIn
    ] as const;
    }


export const getCreateQuestV1GuildsMeQuestsPostQueryOptions = <TData = Awaited<ReturnType<typeof createQuestV1GuildsMeQuestsPost>>, TError = ErrorType<HTTPValidationError>>(questIn: QuestIn, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createQuestV1GuildsMeQuestsPost>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCreateQuestV1GuildsMeQuestsPostQueryKey(questIn);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof createQuestV1GuildsMeQuestsPost>>> = ({ signal }) => createQuestV1GuildsMeQuestsPost(questIn, { signal, ...requestOptions });





   return  { queryKey, queryFn,   staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof createQuestV1GuildsMeQuestsPost>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CreateQuestV1GuildsMeQuestsPostQueryResult = NonNullable<Awaited<ReturnType<typeof createQuestV1GuildsMeQuestsPost>>>
export type CreateQuestV1GuildsMeQuestsPostQueryError = ErrorType<HTTPValidationError>


export function useCreateQuestV1GuildsMeQuestsPost<TData = Awaited<ReturnType<typeof createQuestV1GuildsMeQuestsPost>>, TError = ErrorType<HTTPValidationError>>(
 questIn: QuestIn, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof createQuestV1GuildsMeQuestsPost>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof createQuestV1GuildsMeQuestsPost>>,
          TError,
          Awaited<ReturnType<typeof createQuestV1GuildsMeQuestsPost>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreateQuestV1GuildsMeQuestsPost<TData = Awaited<ReturnType<typeof createQuestV1GuildsMeQuestsPost>>, TError = ErrorType<HTTPValidationError>>(
 questIn: QuestIn, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createQuestV1GuildsMeQuestsPost>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof createQuestV1GuildsMeQuestsPost>>,
          TError,
          Awaited<ReturnType<typeof createQuestV1GuildsMeQuestsPost>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreateQuestV1GuildsMeQuestsPost<TData = Awaited<ReturnType<typeof createQuestV1GuildsMeQuestsPost>>, TError = ErrorType<HTTPValidationError>>(
 questIn: QuestIn, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createQuestV1GuildsMeQuestsPost>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Create Quest
 */

export function useCreateQuestV1GuildsMeQuestsPost<TData = Awaited<ReturnType<typeof createQuestV1GuildsMeQuestsPost>>, TError = ErrorType<HTTPValidationError>>(
 questIn: QuestIn, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createQuestV1GuildsMeQuestsPost>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCreateQuestV1GuildsMeQuestsPostQueryOptions(questIn,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}


/**
 * @summary Create Quest
 */
export const invalidateCreateQuestV1GuildsMeQuestsPost = async (
 queryClient: QueryClient, questIn: QuestIn, options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getCreateQuestV1GuildsMeQuestsPostQueryKey(questIn) }, options);

  return queryClient;
}




export const getListQuestsV1GuildsMeQuestsGetUrl = (params?: ListQuestsV1GuildsMeQuestsGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["creator_thorny_ids","quest_types"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? 'null' : String(v));
      });
      return;
    }

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/guilds/me/quests?${stringifiedParams}` : `/v1/guilds/me/quests`
}

/**
 * Get a list of Quests
 * @summary List Quests
 */
export const listQuestsV1GuildsMeQuestsGet = async (params?: ListQuestsV1GuildsMeQuestsGetParams, options?: Parameters<typeof nexuscoreFetcher>[1]): Promise<QuestOut[]> => {

  return nexuscoreFetcher<QuestOut[]>(getListQuestsV1GuildsMeQuestsGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListQuestsV1GuildsMeQuestsGetInfiniteQueryKey = (params?: ListQuestsV1GuildsMeQuestsGetParams,) => {
    return [
    'infinite', `/v1/guilds/me/quests`, ...(params ? [params] : [])
    ] as const;
    }

export const getListQuestsV1GuildsMeQuestsGetQueryKey = (params?: ListQuestsV1GuildsMeQuestsGetParams,) => {
    return [
    `/v1/guilds/me/quests`, ...(params ? [params] : [])
    ] as const;
    }


export const getListQuestsV1GuildsMeQuestsGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof listQuestsV1GuildsMeQuestsGet>>, ListQuestsV1GuildsMeQuestsGetParams['page']>, TError = ErrorType<HTTPValidationError>>(params?: ListQuestsV1GuildsMeQuestsGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listQuestsV1GuildsMeQuestsGet>>, TError, TData, QueryKey, ListQuestsV1GuildsMeQuestsGetParams['page']>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListQuestsV1GuildsMeQuestsGetInfiniteQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listQuestsV1GuildsMeQuestsGet>>, QueryKey, ListQuestsV1GuildsMeQuestsGetParams['page']> = ({ signal, pageParam }) => listQuestsV1GuildsMeQuestsGet({...params, 'page': pageParam ?? params?.['page']}, { signal, ...requestOptions });





   return  { queryKey, queryFn,   staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof listQuestsV1GuildsMeQuestsGet>>, TError, TData, QueryKey, ListQuestsV1GuildsMeQuestsGetParams['page']> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListQuestsV1GuildsMeQuestsGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof listQuestsV1GuildsMeQuestsGet>>>
export type ListQuestsV1GuildsMeQuestsGetInfiniteQueryError = ErrorType<HTTPValidationError>


export function useListQuestsV1GuildsMeQuestsGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listQuestsV1GuildsMeQuestsGet>>, ListQuestsV1GuildsMeQuestsGetParams['page']>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  ListQuestsV1GuildsMeQuestsGetParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listQuestsV1GuildsMeQuestsGet>>, TError, TData, QueryKey, ListQuestsV1GuildsMeQuestsGetParams['page']>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listQuestsV1GuildsMeQuestsGet>>,
          TError,
          Awaited<ReturnType<typeof listQuestsV1GuildsMeQuestsGet>>, QueryKey
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListQuestsV1GuildsMeQuestsGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listQuestsV1GuildsMeQuestsGet>>, ListQuestsV1GuildsMeQuestsGetParams['page']>, TError = ErrorType<HTTPValidationError>>(
 params?: ListQuestsV1GuildsMeQuestsGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listQuestsV1GuildsMeQuestsGet>>, TError, TData, QueryKey, ListQuestsV1GuildsMeQuestsGetParams['page']>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listQuestsV1GuildsMeQuestsGet>>,
          TError,
          Awaited<ReturnType<typeof listQuestsV1GuildsMeQuestsGet>>, QueryKey
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListQuestsV1GuildsMeQuestsGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listQuestsV1GuildsMeQuestsGet>>, ListQuestsV1GuildsMeQuestsGetParams['page']>, TError = ErrorType<HTTPValidationError>>(
 params?: ListQuestsV1GuildsMeQuestsGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listQuestsV1GuildsMeQuestsGet>>, TError, TData, QueryKey, ListQuestsV1GuildsMeQuestsGetParams['page']>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Quests
 */

export function useListQuestsV1GuildsMeQuestsGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listQuestsV1GuildsMeQuestsGet>>, ListQuestsV1GuildsMeQuestsGetParams['page']>, TError = ErrorType<HTTPValidationError>>(
 params?: ListQuestsV1GuildsMeQuestsGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listQuestsV1GuildsMeQuestsGet>>, TError, TData, QueryKey, ListQuestsV1GuildsMeQuestsGetParams['page']>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListQuestsV1GuildsMeQuestsGetInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}


/**
 * @summary List Quests
 */
export const invalidateListQuestsV1GuildsMeQuestsGetInfinite = async (
 queryClient: QueryClient, params?: ListQuestsV1GuildsMeQuestsGetParams, options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getListQuestsV1GuildsMeQuestsGetInfiniteQueryKey(params) }, options);

  return queryClient;
}




export const getListQuestsV1GuildsMeQuestsGetQueryOptions = <TData = Awaited<ReturnType<typeof listQuestsV1GuildsMeQuestsGet>>, TError = ErrorType<HTTPValidationError>>(params?: ListQuestsV1GuildsMeQuestsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listQuestsV1GuildsMeQuestsGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListQuestsV1GuildsMeQuestsGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listQuestsV1GuildsMeQuestsGet>>> = ({ signal }) => listQuestsV1GuildsMeQuestsGet(params, { signal, ...requestOptions });





   return  { queryKey, queryFn,   staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listQuestsV1GuildsMeQuestsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListQuestsV1GuildsMeQuestsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listQuestsV1GuildsMeQuestsGet>>>
export type ListQuestsV1GuildsMeQuestsGetQueryError = ErrorType<HTTPValidationError>


export function useListQuestsV1GuildsMeQuestsGet<TData = Awaited<ReturnType<typeof listQuestsV1GuildsMeQuestsGet>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  ListQuestsV1GuildsMeQuestsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listQuestsV1GuildsMeQuestsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listQuestsV1GuildsMeQuestsGet>>,
          TError,
          Awaited<ReturnType<typeof listQuestsV1GuildsMeQuestsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListQuestsV1GuildsMeQuestsGet<TData = Awaited<ReturnType<typeof listQuestsV1GuildsMeQuestsGet>>, TError = ErrorType<HTTPValidationError>>(
 params?: ListQuestsV1GuildsMeQuestsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listQuestsV1GuildsMeQuestsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listQuestsV1GuildsMeQuestsGet>>,
          TError,
          Awaited<ReturnType<typeof listQuestsV1GuildsMeQuestsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListQuestsV1GuildsMeQuestsGet<TData = Awaited<ReturnType<typeof listQuestsV1GuildsMeQuestsGet>>, TError = ErrorType<HTTPValidationError>>(
 params?: ListQuestsV1GuildsMeQuestsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listQuestsV1GuildsMeQuestsGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Quests
 */

export function useListQuestsV1GuildsMeQuestsGet<TData = Awaited<ReturnType<typeof listQuestsV1GuildsMeQuestsGet>>, TError = ErrorType<HTTPValidationError>>(
 params?: ListQuestsV1GuildsMeQuestsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listQuestsV1GuildsMeQuestsGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListQuestsV1GuildsMeQuestsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}


/**
 * @summary List Quests
 */
export const invalidateListQuestsV1GuildsMeQuestsGet = async (
 queryClient: QueryClient, params?: ListQuestsV1GuildsMeQuestsGetParams, options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getListQuestsV1GuildsMeQuestsGetQueryKey(params) }, options);

  return queryClient;
}




export const getGetQuestV1GuildsMeQuestsQuestIdGetUrl = (questId: number,) => {




  return `/v1/guilds/me/quests/${questId}`
}

/**
 * Get Quest
 *
 * Returns a specific quest, objectives and rewards
 * @summary Get Quest
 */
export const getQuestV1GuildsMeQuestsQuestIdGet = async (questId: number, options?: Parameters<typeof nexuscoreFetcher>[1]): Promise<QuestOut> => {

  return nexuscoreFetcher<QuestOut>(getGetQuestV1GuildsMeQuestsQuestIdGetUrl(questId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetQuestV1GuildsMeQuestsQuestIdGetQueryKey = (questId: number,) => {
    return [
    `/v1/guilds/me/quests/${questId}`
    ] as const;
    }


export const getGetQuestV1GuildsMeQuestsQuestIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getQuestV1GuildsMeQuestsQuestIdGet>>, TError = ErrorType<HTTPValidationError>>(questId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestV1GuildsMeQuestsQuestIdGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetQuestV1GuildsMeQuestsQuestIdGetQueryKey(questId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getQuestV1GuildsMeQuestsQuestIdGet>>> = ({ signal }) => getQuestV1GuildsMeQuestsQuestIdGet(questId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: questId !== null && questId !== undefined,  staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getQuestV1GuildsMeQuestsQuestIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetQuestV1GuildsMeQuestsQuestIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getQuestV1GuildsMeQuestsQuestIdGet>>>
export type GetQuestV1GuildsMeQuestsQuestIdGetQueryError = ErrorType<HTTPValidationError>


export function useGetQuestV1GuildsMeQuestsQuestIdGet<TData = Awaited<ReturnType<typeof getQuestV1GuildsMeQuestsQuestIdGet>>, TError = ErrorType<HTTPValidationError>>(
 questId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestV1GuildsMeQuestsQuestIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestV1GuildsMeQuestsQuestIdGet>>,
          TError,
          Awaited<ReturnType<typeof getQuestV1GuildsMeQuestsQuestIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuestV1GuildsMeQuestsQuestIdGet<TData = Awaited<ReturnType<typeof getQuestV1GuildsMeQuestsQuestIdGet>>, TError = ErrorType<HTTPValidationError>>(
 questId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestV1GuildsMeQuestsQuestIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestV1GuildsMeQuestsQuestIdGet>>,
          TError,
          Awaited<ReturnType<typeof getQuestV1GuildsMeQuestsQuestIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuestV1GuildsMeQuestsQuestIdGet<TData = Awaited<ReturnType<typeof getQuestV1GuildsMeQuestsQuestIdGet>>, TError = ErrorType<HTTPValidationError>>(
 questId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestV1GuildsMeQuestsQuestIdGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Quest
 */

export function useGetQuestV1GuildsMeQuestsQuestIdGet<TData = Awaited<ReturnType<typeof getQuestV1GuildsMeQuestsQuestIdGet>>, TError = ErrorType<HTTPValidationError>>(
 questId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestV1GuildsMeQuestsQuestIdGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetQuestV1GuildsMeQuestsQuestIdGetQueryOptions(questId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}


/**
 * @summary Get Quest
 */
export const invalidateGetQuestV1GuildsMeQuestsQuestIdGet = async (
 queryClient: QueryClient, questId: number, options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getGetQuestV1GuildsMeQuestsQuestIdGetQueryKey(questId) }, options);

  return queryClient;
}




export const getPartialUpdateQuestV1GuildsMeQuestsQuestIdPutUrl = (questId: number,) => {




  return `/v1/guilds/me/quests/${questId}`
}

/**
 * Updates quest details and/or objectives. Objectives and rewards are additive-only:
 * include an `objective_id`/`reward_id` to update an existing entry, or omit it to create a new one.
 * Existing objectives and rewards not present in the payload are left untouched.
 * @summary Partial Update Quest
 */
export const partialUpdateQuestV1GuildsMeQuestsQuestIdPut = async (questId: number,
    questUpdate: QuestUpdate, options?: Parameters<typeof nexuscoreFetcher>[1]): Promise<QuestOut> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return nexuscoreFetcher<QuestOut>(getPartialUpdateQuestV1GuildsMeQuestsQuestIdPutUrl(questId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(questUpdate)
  }
);}





export const getPartialUpdateQuestV1GuildsMeQuestsQuestIdPutQueryKey = (questId: number,
    questUpdate?: QuestUpdate,) => {
    return [
    'PUT', `/v1/guilds/me/quests/${questId}`, questUpdate
    ] as const;
    }


export const getPartialUpdateQuestV1GuildsMeQuestsQuestIdPutQueryOptions = <TData = Awaited<ReturnType<typeof partialUpdateQuestV1GuildsMeQuestsQuestIdPut>>, TError = ErrorType<HTTPValidationError>>(questId: number,
    questUpdate: QuestUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateQuestV1GuildsMeQuestsQuestIdPut>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPartialUpdateQuestV1GuildsMeQuestsQuestIdPutQueryKey(questId,questUpdate);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof partialUpdateQuestV1GuildsMeQuestsQuestIdPut>>> = ({ signal }) => partialUpdateQuestV1GuildsMeQuestsQuestIdPut(questId,questUpdate, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: questId !== null && questId !== undefined,  staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof partialUpdateQuestV1GuildsMeQuestsQuestIdPut>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PartialUpdateQuestV1GuildsMeQuestsQuestIdPutQueryResult = NonNullable<Awaited<ReturnType<typeof partialUpdateQuestV1GuildsMeQuestsQuestIdPut>>>
export type PartialUpdateQuestV1GuildsMeQuestsQuestIdPutQueryError = ErrorType<HTTPValidationError>


export function usePartialUpdateQuestV1GuildsMeQuestsQuestIdPut<TData = Awaited<ReturnType<typeof partialUpdateQuestV1GuildsMeQuestsQuestIdPut>>, TError = ErrorType<HTTPValidationError>>(
 questId: number,
    questUpdate: QuestUpdate, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateQuestV1GuildsMeQuestsQuestIdPut>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof partialUpdateQuestV1GuildsMeQuestsQuestIdPut>>,
          TError,
          Awaited<ReturnType<typeof partialUpdateQuestV1GuildsMeQuestsQuestIdPut>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePartialUpdateQuestV1GuildsMeQuestsQuestIdPut<TData = Awaited<ReturnType<typeof partialUpdateQuestV1GuildsMeQuestsQuestIdPut>>, TError = ErrorType<HTTPValidationError>>(
 questId: number,
    questUpdate: QuestUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateQuestV1GuildsMeQuestsQuestIdPut>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof partialUpdateQuestV1GuildsMeQuestsQuestIdPut>>,
          TError,
          Awaited<ReturnType<typeof partialUpdateQuestV1GuildsMeQuestsQuestIdPut>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePartialUpdateQuestV1GuildsMeQuestsQuestIdPut<TData = Awaited<ReturnType<typeof partialUpdateQuestV1GuildsMeQuestsQuestIdPut>>, TError = ErrorType<HTTPValidationError>>(
 questId: number,
    questUpdate: QuestUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateQuestV1GuildsMeQuestsQuestIdPut>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Partial Update Quest
 */

export function usePartialUpdateQuestV1GuildsMeQuestsQuestIdPut<TData = Awaited<ReturnType<typeof partialUpdateQuestV1GuildsMeQuestsQuestIdPut>>, TError = ErrorType<HTTPValidationError>>(
 questId: number,
    questUpdate: QuestUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateQuestV1GuildsMeQuestsQuestIdPut>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPartialUpdateQuestV1GuildsMeQuestsQuestIdPutQueryOptions(questId,questUpdate,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}


/**
 * @summary Partial Update Quest
 */
export const invalidatePartialUpdateQuestV1GuildsMeQuestsQuestIdPut = async (
 queryClient: QueryClient, questId: number,
    questUpdate: QuestUpdate, options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getPartialUpdateQuestV1GuildsMeQuestsQuestIdPutQueryKey(questId,questUpdate) }, options);

  return queryClient;
}




export const getPartialUpdateQuestV1GuildsMeQuestsQuestIdPatchUrl = (questId: number,) => {




  return `/v1/guilds/me/quests/${questId}`
}

/**
 * Updates quest details and/or objectives. Objectives and rewards are additive-only:
 * include an `objective_id`/`reward_id` to update an existing entry, or omit it to create a new one.
 * Existing objectives and rewards not present in the payload are left untouched.
 * @summary Partial Update Quest
 */
export const partialUpdateQuestV1GuildsMeQuestsQuestIdPatch = async (questId: number,
    questUpdate: QuestUpdate, options?: Parameters<typeof nexuscoreFetcher>[1]): Promise<QuestOut> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return nexuscoreFetcher<QuestOut>(getPartialUpdateQuestV1GuildsMeQuestsQuestIdPatchUrl(questId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(questUpdate)
  }
);}





export const getPartialUpdateQuestV1GuildsMeQuestsQuestIdPatchQueryKey = (questId: number,
    questUpdate?: QuestUpdate,) => {
    return [
    'PATCH', `/v1/guilds/me/quests/${questId}`, questUpdate
    ] as const;
    }


export const getPartialUpdateQuestV1GuildsMeQuestsQuestIdPatchQueryOptions = <TData = Awaited<ReturnType<typeof partialUpdateQuestV1GuildsMeQuestsQuestIdPatch>>, TError = ErrorType<HTTPValidationError>>(questId: number,
    questUpdate: QuestUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateQuestV1GuildsMeQuestsQuestIdPatch>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPartialUpdateQuestV1GuildsMeQuestsQuestIdPatchQueryKey(questId,questUpdate);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof partialUpdateQuestV1GuildsMeQuestsQuestIdPatch>>> = ({ signal }) => partialUpdateQuestV1GuildsMeQuestsQuestIdPatch(questId,questUpdate, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: questId !== null && questId !== undefined,  staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof partialUpdateQuestV1GuildsMeQuestsQuestIdPatch>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PartialUpdateQuestV1GuildsMeQuestsQuestIdPatchQueryResult = NonNullable<Awaited<ReturnType<typeof partialUpdateQuestV1GuildsMeQuestsQuestIdPatch>>>
export type PartialUpdateQuestV1GuildsMeQuestsQuestIdPatchQueryError = ErrorType<HTTPValidationError>


export function usePartialUpdateQuestV1GuildsMeQuestsQuestIdPatch<TData = Awaited<ReturnType<typeof partialUpdateQuestV1GuildsMeQuestsQuestIdPatch>>, TError = ErrorType<HTTPValidationError>>(
 questId: number,
    questUpdate: QuestUpdate, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateQuestV1GuildsMeQuestsQuestIdPatch>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof partialUpdateQuestV1GuildsMeQuestsQuestIdPatch>>,
          TError,
          Awaited<ReturnType<typeof partialUpdateQuestV1GuildsMeQuestsQuestIdPatch>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePartialUpdateQuestV1GuildsMeQuestsQuestIdPatch<TData = Awaited<ReturnType<typeof partialUpdateQuestV1GuildsMeQuestsQuestIdPatch>>, TError = ErrorType<HTTPValidationError>>(
 questId: number,
    questUpdate: QuestUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateQuestV1GuildsMeQuestsQuestIdPatch>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof partialUpdateQuestV1GuildsMeQuestsQuestIdPatch>>,
          TError,
          Awaited<ReturnType<typeof partialUpdateQuestV1GuildsMeQuestsQuestIdPatch>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePartialUpdateQuestV1GuildsMeQuestsQuestIdPatch<TData = Awaited<ReturnType<typeof partialUpdateQuestV1GuildsMeQuestsQuestIdPatch>>, TError = ErrorType<HTTPValidationError>>(
 questId: number,
    questUpdate: QuestUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateQuestV1GuildsMeQuestsQuestIdPatch>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Partial Update Quest
 */

export function usePartialUpdateQuestV1GuildsMeQuestsQuestIdPatch<TData = Awaited<ReturnType<typeof partialUpdateQuestV1GuildsMeQuestsQuestIdPatch>>, TError = ErrorType<HTTPValidationError>>(
 questId: number,
    questUpdate: QuestUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateQuestV1GuildsMeQuestsQuestIdPatch>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPartialUpdateQuestV1GuildsMeQuestsQuestIdPatchQueryOptions(questId,questUpdate,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}


/**
 * @summary Partial Update Quest
 */
export const invalidatePartialUpdateQuestV1GuildsMeQuestsQuestIdPatch = async (
 queryClient: QueryClient, questId: number,
    questUpdate: QuestUpdate, options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getPartialUpdateQuestV1GuildsMeQuestsQuestIdPatchQueryKey(questId,questUpdate) }, options);

  return queryClient;
}




export const getGetQuestStatisticsV1GuildsMeQuestsQuestIdStatisticsGetUrl = (questId: number,) => {




  return `/v1/guilds/me/quests/${questId}/statistics`
}

/**
 * Get Quest Statistics
 *
 * Returns aggregated statistics for a specific quest, including funnel data,
 * completion timing, per-objective drop-off analysis, and daily activity.
 * Useful for quest admins to analyse difficulty, engagement, and player behaviour.
 * @summary Get Quest Statistics
 */
export const getQuestStatisticsV1GuildsMeQuestsQuestIdStatisticsGet = async (questId: number, options?: Parameters<typeof nexuscoreFetcher>[1]): Promise<QuestStatisticsOut> => {

  return nexuscoreFetcher<QuestStatisticsOut>(getGetQuestStatisticsV1GuildsMeQuestsQuestIdStatisticsGetUrl(questId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetQuestStatisticsV1GuildsMeQuestsQuestIdStatisticsGetQueryKey = (questId: number,) => {
    return [
    `/v1/guilds/me/quests/${questId}/statistics`
    ] as const;
    }


export const getGetQuestStatisticsV1GuildsMeQuestsQuestIdStatisticsGetQueryOptions = <TData = Awaited<ReturnType<typeof getQuestStatisticsV1GuildsMeQuestsQuestIdStatisticsGet>>, TError = ErrorType<HTTPValidationError>>(questId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestStatisticsV1GuildsMeQuestsQuestIdStatisticsGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetQuestStatisticsV1GuildsMeQuestsQuestIdStatisticsGetQueryKey(questId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getQuestStatisticsV1GuildsMeQuestsQuestIdStatisticsGet>>> = ({ signal }) => getQuestStatisticsV1GuildsMeQuestsQuestIdStatisticsGet(questId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: questId !== null && questId !== undefined,  staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getQuestStatisticsV1GuildsMeQuestsQuestIdStatisticsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetQuestStatisticsV1GuildsMeQuestsQuestIdStatisticsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getQuestStatisticsV1GuildsMeQuestsQuestIdStatisticsGet>>>
export type GetQuestStatisticsV1GuildsMeQuestsQuestIdStatisticsGetQueryError = ErrorType<HTTPValidationError>


export function useGetQuestStatisticsV1GuildsMeQuestsQuestIdStatisticsGet<TData = Awaited<ReturnType<typeof getQuestStatisticsV1GuildsMeQuestsQuestIdStatisticsGet>>, TError = ErrorType<HTTPValidationError>>(
 questId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestStatisticsV1GuildsMeQuestsQuestIdStatisticsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestStatisticsV1GuildsMeQuestsQuestIdStatisticsGet>>,
          TError,
          Awaited<ReturnType<typeof getQuestStatisticsV1GuildsMeQuestsQuestIdStatisticsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuestStatisticsV1GuildsMeQuestsQuestIdStatisticsGet<TData = Awaited<ReturnType<typeof getQuestStatisticsV1GuildsMeQuestsQuestIdStatisticsGet>>, TError = ErrorType<HTTPValidationError>>(
 questId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestStatisticsV1GuildsMeQuestsQuestIdStatisticsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestStatisticsV1GuildsMeQuestsQuestIdStatisticsGet>>,
          TError,
          Awaited<ReturnType<typeof getQuestStatisticsV1GuildsMeQuestsQuestIdStatisticsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuestStatisticsV1GuildsMeQuestsQuestIdStatisticsGet<TData = Awaited<ReturnType<typeof getQuestStatisticsV1GuildsMeQuestsQuestIdStatisticsGet>>, TError = ErrorType<HTTPValidationError>>(
 questId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestStatisticsV1GuildsMeQuestsQuestIdStatisticsGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Quest Statistics
 */

export function useGetQuestStatisticsV1GuildsMeQuestsQuestIdStatisticsGet<TData = Awaited<ReturnType<typeof getQuestStatisticsV1GuildsMeQuestsQuestIdStatisticsGet>>, TError = ErrorType<HTTPValidationError>>(
 questId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestStatisticsV1GuildsMeQuestsQuestIdStatisticsGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetQuestStatisticsV1GuildsMeQuestsQuestIdStatisticsGetQueryOptions(questId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}


/**
 * @summary Get Quest Statistics
 */
export const invalidateGetQuestStatisticsV1GuildsMeQuestsQuestIdStatisticsGet = async (
 queryClient: QueryClient, questId: number, options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getGetQuestStatisticsV1GuildsMeQuestsQuestIdStatisticsGetQueryKey(questId) }, options);

  return queryClient;
}




export const getCreateQuestProgressV1GuildsMeQuestsProgressPostUrl = () => {




  return `/v1/guilds/me/quests/progress`
}

/**
 * Create New Quest Progress
 *
 * Adds a new quest to a user, tracking their progress.
 * Automatically sets the quest progress to "active".
 * @summary Create Quest Progress
 */
export const createQuestProgressV1GuildsMeQuestsProgressPost = async (questProgressIn: QuestProgressIn, options?: Parameters<typeof nexuscoreFetcher>[1]): Promise<QuestProgressOut> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return nexuscoreFetcher<QuestProgressOut>(getCreateQuestProgressV1GuildsMeQuestsProgressPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(questProgressIn)
  }
);}





export const getCreateQuestProgressV1GuildsMeQuestsProgressPostQueryKey = (questProgressIn?: QuestProgressIn,) => {
    return [
    'POST', `/v1/guilds/me/quests/progress`, questProgressIn
    ] as const;
    }


export const getCreateQuestProgressV1GuildsMeQuestsProgressPostQueryOptions = <TData = Awaited<ReturnType<typeof createQuestProgressV1GuildsMeQuestsProgressPost>>, TError = ErrorType<HTTPValidationError>>(questProgressIn: QuestProgressIn, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createQuestProgressV1GuildsMeQuestsProgressPost>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCreateQuestProgressV1GuildsMeQuestsProgressPostQueryKey(questProgressIn);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof createQuestProgressV1GuildsMeQuestsProgressPost>>> = ({ signal }) => createQuestProgressV1GuildsMeQuestsProgressPost(questProgressIn, { signal, ...requestOptions });





   return  { queryKey, queryFn,   staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof createQuestProgressV1GuildsMeQuestsProgressPost>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CreateQuestProgressV1GuildsMeQuestsProgressPostQueryResult = NonNullable<Awaited<ReturnType<typeof createQuestProgressV1GuildsMeQuestsProgressPost>>>
export type CreateQuestProgressV1GuildsMeQuestsProgressPostQueryError = ErrorType<HTTPValidationError>


export function useCreateQuestProgressV1GuildsMeQuestsProgressPost<TData = Awaited<ReturnType<typeof createQuestProgressV1GuildsMeQuestsProgressPost>>, TError = ErrorType<HTTPValidationError>>(
 questProgressIn: QuestProgressIn, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof createQuestProgressV1GuildsMeQuestsProgressPost>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof createQuestProgressV1GuildsMeQuestsProgressPost>>,
          TError,
          Awaited<ReturnType<typeof createQuestProgressV1GuildsMeQuestsProgressPost>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreateQuestProgressV1GuildsMeQuestsProgressPost<TData = Awaited<ReturnType<typeof createQuestProgressV1GuildsMeQuestsProgressPost>>, TError = ErrorType<HTTPValidationError>>(
 questProgressIn: QuestProgressIn, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createQuestProgressV1GuildsMeQuestsProgressPost>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof createQuestProgressV1GuildsMeQuestsProgressPost>>,
          TError,
          Awaited<ReturnType<typeof createQuestProgressV1GuildsMeQuestsProgressPost>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreateQuestProgressV1GuildsMeQuestsProgressPost<TData = Awaited<ReturnType<typeof createQuestProgressV1GuildsMeQuestsProgressPost>>, TError = ErrorType<HTTPValidationError>>(
 questProgressIn: QuestProgressIn, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createQuestProgressV1GuildsMeQuestsProgressPost>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Create Quest Progress
 */

export function useCreateQuestProgressV1GuildsMeQuestsProgressPost<TData = Awaited<ReturnType<typeof createQuestProgressV1GuildsMeQuestsProgressPost>>, TError = ErrorType<HTTPValidationError>>(
 questProgressIn: QuestProgressIn, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createQuestProgressV1GuildsMeQuestsProgressPost>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCreateQuestProgressV1GuildsMeQuestsProgressPostQueryOptions(questProgressIn,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}


/**
 * @summary Create Quest Progress
 */
export const invalidateCreateQuestProgressV1GuildsMeQuestsProgressPost = async (
 queryClient: QueryClient, questProgressIn: QuestProgressIn, options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getCreateQuestProgressV1GuildsMeQuestsProgressPostQueryKey(questProgressIn) }, options);

  return queryClient;
}




export const getListQuestProgressV1GuildsMeQuestsProgressUserThornyIdGetUrl = (thornyId: number,) => {




  return `/v1/guilds/me/quests/progress/user/${thornyId}`
}

/**
 * Get All User's Quest Progress
 *
 * Returns all quest progress belonging to a user
 * @summary List Quest Progress
 */
export const listQuestProgressV1GuildsMeQuestsProgressUserThornyIdGet = async (thornyId: number, options?: Parameters<typeof nexuscoreFetcher>[1]): Promise<QuestProgressOut[]> => {

  return nexuscoreFetcher<QuestProgressOut[]>(getListQuestProgressV1GuildsMeQuestsProgressUserThornyIdGetUrl(thornyId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListQuestProgressV1GuildsMeQuestsProgressUserThornyIdGetQueryKey = (thornyId: number,) => {
    return [
    `/v1/guilds/me/quests/progress/user/${thornyId}`
    ] as const;
    }


export const getListQuestProgressV1GuildsMeQuestsProgressUserThornyIdGetQueryOptions = <TData = Awaited<ReturnType<typeof listQuestProgressV1GuildsMeQuestsProgressUserThornyIdGet>>, TError = ErrorType<HTTPValidationError>>(thornyId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listQuestProgressV1GuildsMeQuestsProgressUserThornyIdGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListQuestProgressV1GuildsMeQuestsProgressUserThornyIdGetQueryKey(thornyId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listQuestProgressV1GuildsMeQuestsProgressUserThornyIdGet>>> = ({ signal }) => listQuestProgressV1GuildsMeQuestsProgressUserThornyIdGet(thornyId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: thornyId !== null && thornyId !== undefined,  staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listQuestProgressV1GuildsMeQuestsProgressUserThornyIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListQuestProgressV1GuildsMeQuestsProgressUserThornyIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof listQuestProgressV1GuildsMeQuestsProgressUserThornyIdGet>>>
export type ListQuestProgressV1GuildsMeQuestsProgressUserThornyIdGetQueryError = ErrorType<HTTPValidationError>


export function useListQuestProgressV1GuildsMeQuestsProgressUserThornyIdGet<TData = Awaited<ReturnType<typeof listQuestProgressV1GuildsMeQuestsProgressUserThornyIdGet>>, TError = ErrorType<HTTPValidationError>>(
 thornyId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listQuestProgressV1GuildsMeQuestsProgressUserThornyIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listQuestProgressV1GuildsMeQuestsProgressUserThornyIdGet>>,
          TError,
          Awaited<ReturnType<typeof listQuestProgressV1GuildsMeQuestsProgressUserThornyIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListQuestProgressV1GuildsMeQuestsProgressUserThornyIdGet<TData = Awaited<ReturnType<typeof listQuestProgressV1GuildsMeQuestsProgressUserThornyIdGet>>, TError = ErrorType<HTTPValidationError>>(
 thornyId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listQuestProgressV1GuildsMeQuestsProgressUserThornyIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listQuestProgressV1GuildsMeQuestsProgressUserThornyIdGet>>,
          TError,
          Awaited<ReturnType<typeof listQuestProgressV1GuildsMeQuestsProgressUserThornyIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListQuestProgressV1GuildsMeQuestsProgressUserThornyIdGet<TData = Awaited<ReturnType<typeof listQuestProgressV1GuildsMeQuestsProgressUserThornyIdGet>>, TError = ErrorType<HTTPValidationError>>(
 thornyId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listQuestProgressV1GuildsMeQuestsProgressUserThornyIdGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Quest Progress
 */

export function useListQuestProgressV1GuildsMeQuestsProgressUserThornyIdGet<TData = Awaited<ReturnType<typeof listQuestProgressV1GuildsMeQuestsProgressUserThornyIdGet>>, TError = ErrorType<HTTPValidationError>>(
 thornyId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listQuestProgressV1GuildsMeQuestsProgressUserThornyIdGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListQuestProgressV1GuildsMeQuestsProgressUserThornyIdGetQueryOptions(thornyId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}


/**
 * @summary List Quest Progress
 */
export const invalidateListQuestProgressV1GuildsMeQuestsProgressUserThornyIdGet = async (
 queryClient: QueryClient, thornyId: number, options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getListQuestProgressV1GuildsMeQuestsProgressUserThornyIdGetQueryKey(thornyId) }, options);

  return queryClient;
}




export const getGetActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveGetUrl = (thornyId: number,) => {




  return `/v1/guilds/me/quests/progress/user/${thornyId}/active`
}

/**
 * Get User's Active Quest
 *
 * Returns the user's currently active quest.
 * @summary Get Active Quest Progress
 */
export const getActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveGet = async (thornyId: number, options?: Parameters<typeof nexuscoreFetcher>[1]): Promise<QuestProgressOut> => {

  return nexuscoreFetcher<QuestProgressOut>(getGetActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveGetUrl(thornyId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveGetQueryKey = (thornyId: number,) => {
    return [
    `/v1/guilds/me/quests/progress/user/${thornyId}/active`
    ] as const;
    }


export const getGetActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveGetQueryOptions = <TData = Awaited<ReturnType<typeof getActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveGet>>, TError = ErrorType<HTTPValidationError>>(thornyId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveGetQueryKey(thornyId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveGet>>> = ({ signal }) => getActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveGet(thornyId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: thornyId !== null && thornyId !== undefined,  staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveGetQueryResult = NonNullable<Awaited<ReturnType<typeof getActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveGet>>>
export type GetActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveGetQueryError = ErrorType<HTTPValidationError>


export function useGetActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveGet<TData = Awaited<ReturnType<typeof getActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveGet>>, TError = ErrorType<HTTPValidationError>>(
 thornyId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveGet>>,
          TError,
          Awaited<ReturnType<typeof getActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveGet<TData = Awaited<ReturnType<typeof getActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveGet>>, TError = ErrorType<HTTPValidationError>>(
 thornyId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveGet>>,
          TError,
          Awaited<ReturnType<typeof getActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveGet<TData = Awaited<ReturnType<typeof getActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveGet>>, TError = ErrorType<HTTPValidationError>>(
 thornyId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Active Quest Progress
 */

export function useGetActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveGet<TData = Awaited<ReturnType<typeof getActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveGet>>, TError = ErrorType<HTTPValidationError>>(
 thornyId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveGetQueryOptions(thornyId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}


/**
 * @summary Get Active Quest Progress
 */
export const invalidateGetActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveGet = async (
 queryClient: QueryClient, thornyId: number, options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getGetActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveGetQueryKey(thornyId) }, options);

  return queryClient;
}




export const getFailActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveDeleteUrl = (thornyId: number,) => {




  return `/v1/guilds/me/quests/progress/user/${thornyId}/active`
}

/**
 * Fail User's Active Quest
 *
 * This marks the active quest and all of its objectives as "failed".
 * @summary Fail Active Quest Progress
 */
export const failActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveDelete = async (thornyId: number, options?: Parameters<typeof nexuscoreFetcher>[1]): Promise<void> => {

  return nexuscoreFetcher<void>(getFailActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveDeleteUrl(thornyId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getFailActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveDeleteQueryKey = (thornyId: number,) => {
    return [
    'DELETE', `/v1/guilds/me/quests/progress/user/${thornyId}/active`
    ] as const;
    }


export const getFailActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveDeleteQueryOptions = <TData = Awaited<ReturnType<typeof failActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveDelete>>, TError = ErrorType<HTTPValidationError>>(thornyId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof failActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveDelete>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFailActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveDeleteQueryKey(thornyId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof failActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveDelete>>> = ({ signal }) => failActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveDelete(thornyId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: thornyId !== null && thornyId !== undefined,  staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof failActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveDelete>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FailActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveDeleteQueryResult = NonNullable<Awaited<ReturnType<typeof failActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveDelete>>>
export type FailActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveDeleteQueryError = ErrorType<HTTPValidationError>


export function useFailActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveDelete<TData = Awaited<ReturnType<typeof failActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveDelete>>, TError = ErrorType<HTTPValidationError>>(
 thornyId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof failActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveDelete>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof failActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveDelete>>,
          TError,
          Awaited<ReturnType<typeof failActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveDelete>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFailActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveDelete<TData = Awaited<ReturnType<typeof failActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveDelete>>, TError = ErrorType<HTTPValidationError>>(
 thornyId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof failActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveDelete>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof failActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveDelete>>,
          TError,
          Awaited<ReturnType<typeof failActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveDelete>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFailActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveDelete<TData = Awaited<ReturnType<typeof failActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveDelete>>, TError = ErrorType<HTTPValidationError>>(
 thornyId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof failActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveDelete>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Fail Active Quest Progress
 */

export function useFailActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveDelete<TData = Awaited<ReturnType<typeof failActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveDelete>>, TError = ErrorType<HTTPValidationError>>(
 thornyId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof failActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveDelete>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFailActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveDeleteQueryOptions(thornyId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}


/**
 * @summary Fail Active Quest Progress
 */
export const invalidateFailActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveDelete = async (
 queryClient: QueryClient, thornyId: number, options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getFailActiveQuestProgressV1GuildsMeQuestsProgressUserThornyIdActiveDeleteQueryKey(thornyId) }, options);

  return queryClient;
}




export const getPartialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPatchUrl = (progressId: number,) => {




  return `/v1/guilds/me/quests/progress/${progressId}`
}

/**
 * Update Specific User's Quest
 *
 * Updates a user's quest.
 * @summary Partial Update Quest Progress
 */
export const partialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPatch = async (progressId: number,
    questProgressUpdate: QuestProgressUpdate, options?: Parameters<typeof nexuscoreFetcher>[1]): Promise<QuestProgressOut> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return nexuscoreFetcher<QuestProgressOut>(getPartialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPatchUrl(progressId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(questProgressUpdate)
  }
);}





export const getPartialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPatchQueryKey = (progressId: number,
    questProgressUpdate?: QuestProgressUpdate,) => {
    return [
    'PATCH', `/v1/guilds/me/quests/progress/${progressId}`, questProgressUpdate
    ] as const;
    }


export const getPartialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPatchQueryOptions = <TData = Awaited<ReturnType<typeof partialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPatch>>, TError = ErrorType<HTTPValidationError>>(progressId: number,
    questProgressUpdate: QuestProgressUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPatch>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPartialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPatchQueryKey(progressId,questProgressUpdate);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof partialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPatch>>> = ({ signal }) => partialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPatch(progressId,questProgressUpdate, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: progressId !== null && progressId !== undefined,  staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof partialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPatch>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PartialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPatchQueryResult = NonNullable<Awaited<ReturnType<typeof partialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPatch>>>
export type PartialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPatchQueryError = ErrorType<HTTPValidationError>


export function usePartialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPatch<TData = Awaited<ReturnType<typeof partialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPatch>>, TError = ErrorType<HTTPValidationError>>(
 progressId: number,
    questProgressUpdate: QuestProgressUpdate, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPatch>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof partialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPatch>>,
          TError,
          Awaited<ReturnType<typeof partialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPatch>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePartialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPatch<TData = Awaited<ReturnType<typeof partialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPatch>>, TError = ErrorType<HTTPValidationError>>(
 progressId: number,
    questProgressUpdate: QuestProgressUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPatch>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof partialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPatch>>,
          TError,
          Awaited<ReturnType<typeof partialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPatch>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePartialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPatch<TData = Awaited<ReturnType<typeof partialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPatch>>, TError = ErrorType<HTTPValidationError>>(
 progressId: number,
    questProgressUpdate: QuestProgressUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPatch>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Partial Update Quest Progress
 */

export function usePartialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPatch<TData = Awaited<ReturnType<typeof partialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPatch>>, TError = ErrorType<HTTPValidationError>>(
 progressId: number,
    questProgressUpdate: QuestProgressUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPatch>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPartialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPatchQueryOptions(progressId,questProgressUpdate,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}


/**
 * @summary Partial Update Quest Progress
 */
export const invalidatePartialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPatch = async (
 queryClient: QueryClient, progressId: number,
    questProgressUpdate: QuestProgressUpdate, options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getPartialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPatchQueryKey(progressId,questProgressUpdate) }, options);

  return queryClient;
}




export const getPartialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPutUrl = (progressId: number,) => {




  return `/v1/guilds/me/quests/progress/${progressId}`
}

/**
 * Update Specific User's Quest
 *
 * Updates a user's quest.
 * @summary Partial Update Quest Progress
 */
export const partialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPut = async (progressId: number,
    questProgressUpdate: QuestProgressUpdate, options?: Parameters<typeof nexuscoreFetcher>[1]): Promise<QuestProgressOut> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return nexuscoreFetcher<QuestProgressOut>(getPartialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPutUrl(progressId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(questProgressUpdate)
  }
);}





export const getPartialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPutQueryKey = (progressId: number,
    questProgressUpdate?: QuestProgressUpdate,) => {
    return [
    'PUT', `/v1/guilds/me/quests/progress/${progressId}`, questProgressUpdate
    ] as const;
    }


export const getPartialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPutQueryOptions = <TData = Awaited<ReturnType<typeof partialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPut>>, TError = ErrorType<HTTPValidationError>>(progressId: number,
    questProgressUpdate: QuestProgressUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPut>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPartialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPutQueryKey(progressId,questProgressUpdate);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof partialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPut>>> = ({ signal }) => partialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPut(progressId,questProgressUpdate, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: progressId !== null && progressId !== undefined,  staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof partialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPut>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PartialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPutQueryResult = NonNullable<Awaited<ReturnType<typeof partialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPut>>>
export type PartialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPutQueryError = ErrorType<HTTPValidationError>


export function usePartialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPut<TData = Awaited<ReturnType<typeof partialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPut>>, TError = ErrorType<HTTPValidationError>>(
 progressId: number,
    questProgressUpdate: QuestProgressUpdate, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPut>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof partialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPut>>,
          TError,
          Awaited<ReturnType<typeof partialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPut>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePartialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPut<TData = Awaited<ReturnType<typeof partialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPut>>, TError = ErrorType<HTTPValidationError>>(
 progressId: number,
    questProgressUpdate: QuestProgressUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPut>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof partialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPut>>,
          TError,
          Awaited<ReturnType<typeof partialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPut>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePartialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPut<TData = Awaited<ReturnType<typeof partialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPut>>, TError = ErrorType<HTTPValidationError>>(
 progressId: number,
    questProgressUpdate: QuestProgressUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPut>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Partial Update Quest Progress
 */

export function usePartialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPut<TData = Awaited<ReturnType<typeof partialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPut>>, TError = ErrorType<HTTPValidationError>>(
 progressId: number,
    questProgressUpdate: QuestProgressUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPut>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPartialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPutQueryOptions(progressId,questProgressUpdate,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}


/**
 * @summary Partial Update Quest Progress
 */
export const invalidatePartialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPut = async (
 queryClient: QueryClient, progressId: number,
    questProgressUpdate: QuestProgressUpdate, options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getPartialUpdateQuestProgressV1GuildsMeQuestsProgressProgressIdPutQueryKey(progressId,questProgressUpdate) }, options);

  return queryClient;
}




