/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  InvalidateOptions,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  RelayModel
} from '../model';

import { nexuscoreFetcher } from '../../../lib/nexuscore-fetcher.ts';
import type { ErrorType } from '../../../lib/nexuscore-fetcher.ts';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getServerRelayV1RelayPostUrl = () => {




  return `/v1/relay`
}

/**
 * Relays a message to the discord server via a webhook.
 * Essentially acts as a wrapper, instead of calling a HTTP to the
 * webhook, just send a POST to here.
 * @summary Server Relay
 */
export const serverRelayV1RelayPost = async (relayModel: RelayModel, options?: RequestInit): Promise<unknown> => {

  return nexuscoreFetcher<unknown>(getServerRelayV1RelayPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(relayModel)
  }
);}





export const getServerRelayV1RelayPostQueryKey = (relayModel?: RelayModel,) => {
    return [
    'POST', `/v1/relay`, relayModel
    ] as const;
    }


export const getServerRelayV1RelayPostQueryOptions = <TData = Awaited<ReturnType<typeof serverRelayV1RelayPost>>, TError = ErrorType<HTTPValidationError>>(relayModel: RelayModel, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serverRelayV1RelayPost>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getServerRelayV1RelayPostQueryKey(relayModel);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof serverRelayV1RelayPost>>> = ({ signal }) => serverRelayV1RelayPost(relayModel, { signal, ...requestOptions });





   return  { queryKey, queryFn,   staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof serverRelayV1RelayPost>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ServerRelayV1RelayPostQueryResult = NonNullable<Awaited<ReturnType<typeof serverRelayV1RelayPost>>>
export type ServerRelayV1RelayPostQueryError = ErrorType<HTTPValidationError>


export function useServerRelayV1RelayPost<TData = Awaited<ReturnType<typeof serverRelayV1RelayPost>>, TError = ErrorType<HTTPValidationError>>(
 relayModel: RelayModel, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof serverRelayV1RelayPost>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof serverRelayV1RelayPost>>,
          TError,
          Awaited<ReturnType<typeof serverRelayV1RelayPost>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useServerRelayV1RelayPost<TData = Awaited<ReturnType<typeof serverRelayV1RelayPost>>, TError = ErrorType<HTTPValidationError>>(
 relayModel: RelayModel, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serverRelayV1RelayPost>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof serverRelayV1RelayPost>>,
          TError,
          Awaited<ReturnType<typeof serverRelayV1RelayPost>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useServerRelayV1RelayPost<TData = Awaited<ReturnType<typeof serverRelayV1RelayPost>>, TError = ErrorType<HTTPValidationError>>(
 relayModel: RelayModel, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serverRelayV1RelayPost>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Server Relay
 */

export function useServerRelayV1RelayPost<TData = Awaited<ReturnType<typeof serverRelayV1RelayPost>>, TError = ErrorType<HTTPValidationError>>(
 relayModel: RelayModel, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serverRelayV1RelayPost>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getServerRelayV1RelayPostQueryOptions(relayModel,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}


/**
 * @summary Server Relay
 */
export const invalidateServerRelayV1RelayPost = async (
 queryClient: QueryClient, relayModel: RelayModel, options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getServerRelayV1RelayPostQueryKey(relayModel) }, options);

  return queryClient;
}




