/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  RelayModel
} from '../model';

import { nexuscoreFetcher } from '../../../lib/nexuscore-fetcher';
import type { ErrorType } from '../../../lib/nexuscore-fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Relays a message to the discord server via a webhook.
Essentially acts as a wrapper, instead of calling a HTTP to the
webhook, just send a POST to here.
 * @summary Server Relay
 */
export const getServerRelayV1RelayPostUrl = () => {




  return `/v1/relay`
}

export const serverRelayV1RelayPost = async (relayModel: RelayModel, options?: RequestInit): Promise<unknown> => {

  return nexuscoreFetcher<unknown>(getServerRelayV1RelayPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      relayModel,)
  }
);}




export const getServerRelayV1RelayPostMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof serverRelayV1RelayPost>>, TError,{data: RelayModel}, TContext>, request?: SecondParameter<typeof nexuscoreFetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof serverRelayV1RelayPost>>, TError,{data: RelayModel}, TContext> => {

const mutationKey = ['serverRelayV1RelayPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof serverRelayV1RelayPost>>, {data: RelayModel}> = (props) => {
          const {data} = props ?? {};

          return  serverRelayV1RelayPost(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ServerRelayV1RelayPostMutationResult = NonNullable<Awaited<ReturnType<typeof serverRelayV1RelayPost>>>
    export type ServerRelayV1RelayPostMutationBody = RelayModel
    export type ServerRelayV1RelayPostMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Server Relay
 */
export const useServerRelayV1RelayPost = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof serverRelayV1RelayPost>>, TError,{data: RelayModel}, TContext>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof serverRelayV1RelayPost>>,
        TError,
        {data: RelayModel},
        TContext
      > => {
      return useMutation(getServerRelayV1RelayPostMutationOptions(options), queryClient);
    }
