/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  InvalidateOptions,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  PinIn,
  PinOut,
  PinUpdate
} from '../model';

import { nexuscoreFetcher } from '../../../lib/nexuscore-fetcher.ts';
import type { ErrorType } from '../../../lib/nexuscore-fetcher.ts';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getListPinsV1PinsGetUrl = () => {




  return `/v1/pins`
}

/**
 * Get a list of Pins
 * @summary List Pins
 */
export const listPinsV1PinsGet = async ( options?: RequestInit): Promise<PinOut[]> => {

  return nexuscoreFetcher<PinOut[]>(getListPinsV1PinsGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListPinsV1PinsGetMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof listPinsV1PinsGet>>, TError,void, TContext>, request?: SecondParameter<typeof nexuscoreFetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof listPinsV1PinsGet>>, TError,void, TContext> => {

const mutationKey = ['listPinsV1PinsGet'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof listPinsV1PinsGet>>, void> = () => {


          return  listPinsV1PinsGet(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ListPinsV1PinsGetMutationResult = NonNullable<Awaited<ReturnType<typeof listPinsV1PinsGet>>>

    export type ListPinsV1PinsGetMutationError = ErrorType<unknown>

    /**
 * @summary List Pins
 */
export const useListPinsV1PinsGet = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof listPinsV1PinsGet>>, TError,void, TContext>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof listPinsV1PinsGet>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getListPinsV1PinsGetMutationOptions(options), queryClient);
    }
    export const getCreatePinV1PinsPostUrl = () => {




  return `/v1/pins`
}

/**
 * Creates a new pin
 * @summary Create Pin
 */
export const createPinV1PinsPost = async (pinIn: PinIn, options?: RequestInit): Promise<PinOut> => {

  return nexuscoreFetcher<PinOut>(getCreatePinV1PinsPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(pinIn)
  }
);}





export const getCreatePinV1PinsPostQueryKey = (pinIn?: PinIn,) => {
    return [
    'POST', `/v1/pins`, pinIn
    ] as const;
    }


export const getCreatePinV1PinsPostQueryOptions = <TData = Awaited<ReturnType<typeof createPinV1PinsPost>>, TError = ErrorType<HTTPValidationError>>(pinIn: PinIn, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createPinV1PinsPost>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCreatePinV1PinsPostQueryKey(pinIn);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof createPinV1PinsPost>>> = ({ signal }) => createPinV1PinsPost(pinIn, { signal, ...requestOptions });





   return  { queryKey, queryFn,   staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof createPinV1PinsPost>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CreatePinV1PinsPostQueryResult = NonNullable<Awaited<ReturnType<typeof createPinV1PinsPost>>>
export type CreatePinV1PinsPostQueryError = ErrorType<HTTPValidationError>


export function useCreatePinV1PinsPost<TData = Awaited<ReturnType<typeof createPinV1PinsPost>>, TError = ErrorType<HTTPValidationError>>(
 pinIn: PinIn, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof createPinV1PinsPost>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof createPinV1PinsPost>>,
          TError,
          Awaited<ReturnType<typeof createPinV1PinsPost>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreatePinV1PinsPost<TData = Awaited<ReturnType<typeof createPinV1PinsPost>>, TError = ErrorType<HTTPValidationError>>(
 pinIn: PinIn, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createPinV1PinsPost>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof createPinV1PinsPost>>,
          TError,
          Awaited<ReturnType<typeof createPinV1PinsPost>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreatePinV1PinsPost<TData = Awaited<ReturnType<typeof createPinV1PinsPost>>, TError = ErrorType<HTTPValidationError>>(
 pinIn: PinIn, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createPinV1PinsPost>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Create Pin
 */

export function useCreatePinV1PinsPost<TData = Awaited<ReturnType<typeof createPinV1PinsPost>>, TError = ErrorType<HTTPValidationError>>(
 pinIn: PinIn, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createPinV1PinsPost>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCreatePinV1PinsPostQueryOptions(pinIn,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}


/**
 * @summary Create Pin
 */
export const invalidateCreatePinV1PinsPost = async (
 queryClient: QueryClient, pinIn: PinIn, options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getCreatePinV1PinsPostQueryKey(pinIn) }, options);

  return queryClient;
}




export const getGetPinV1PinsPinIdGetUrl = (pinId: number,) => {




  return `/v1/pins/${pinId}`
}

/**
 * Returns the pin specified
 * @summary Get Pin
 */
export const getPinV1PinsPinIdGet = async (pinId: number, options?: RequestInit): Promise<PinOut> => {

  return nexuscoreFetcher<PinOut>(getGetPinV1PinsPinIdGetUrl(pinId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPinV1PinsPinIdGetMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getPinV1PinsPinIdGet>>, TError,{pinId: number}, TContext>, request?: SecondParameter<typeof nexuscoreFetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof getPinV1PinsPinIdGet>>, TError,{pinId: number}, TContext> => {

const mutationKey = ['getPinV1PinsPinIdGet'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getPinV1PinsPinIdGet>>, {pinId: number}> = (props) => {
          const {pinId} = props ?? {};

          return  getPinV1PinsPinIdGet(pinId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetPinV1PinsPinIdGetMutationResult = NonNullable<Awaited<ReturnType<typeof getPinV1PinsPinIdGet>>>

    export type GetPinV1PinsPinIdGetMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Get Pin
 */
export const useGetPinV1PinsPinIdGet = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getPinV1PinsPinIdGet>>, TError,{pinId: number}, TContext>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getPinV1PinsPinIdGet>>,
        TError,
        {pinId: number},
        TContext
      > => {
      return useMutation(getGetPinV1PinsPinIdGetMutationOptions(options), queryClient);
    }
    export const getPartialUpdatePinV1PinsPinIdPutUrl = (pinId: number,) => {




  return `/v1/pins/${pinId}`
}

/**
 * Update Pin
 *
 * Update the pin. Anything that you do not want to update can be left as `null`
 * @summary Partial Update Pin
 */
export const partialUpdatePinV1PinsPinIdPut = async (pinId: number,
    pinUpdate: PinUpdate, options?: RequestInit): Promise<PinOut> => {

  return nexuscoreFetcher<PinOut>(getPartialUpdatePinV1PinsPinIdPutUrl(pinId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(pinUpdate)
  }
);}





export const getPartialUpdatePinV1PinsPinIdPutQueryKey = (pinId: number,
    pinUpdate?: PinUpdate,) => {
    return [
    'PUT', `/v1/pins/${pinId}`, pinUpdate
    ] as const;
    }


export const getPartialUpdatePinV1PinsPinIdPutQueryOptions = <TData = Awaited<ReturnType<typeof partialUpdatePinV1PinsPinIdPut>>, TError = ErrorType<HTTPValidationError>>(pinId: number,
    pinUpdate: PinUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdatePinV1PinsPinIdPut>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPartialUpdatePinV1PinsPinIdPutQueryKey(pinId,pinUpdate);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof partialUpdatePinV1PinsPinIdPut>>> = ({ signal }) => partialUpdatePinV1PinsPinIdPut(pinId,pinUpdate, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: pinId !== null && pinId !== undefined,  staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof partialUpdatePinV1PinsPinIdPut>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PartialUpdatePinV1PinsPinIdPutQueryResult = NonNullable<Awaited<ReturnType<typeof partialUpdatePinV1PinsPinIdPut>>>
export type PartialUpdatePinV1PinsPinIdPutQueryError = ErrorType<HTTPValidationError>


export function usePartialUpdatePinV1PinsPinIdPut<TData = Awaited<ReturnType<typeof partialUpdatePinV1PinsPinIdPut>>, TError = ErrorType<HTTPValidationError>>(
 pinId: number,
    pinUpdate: PinUpdate, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdatePinV1PinsPinIdPut>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof partialUpdatePinV1PinsPinIdPut>>,
          TError,
          Awaited<ReturnType<typeof partialUpdatePinV1PinsPinIdPut>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePartialUpdatePinV1PinsPinIdPut<TData = Awaited<ReturnType<typeof partialUpdatePinV1PinsPinIdPut>>, TError = ErrorType<HTTPValidationError>>(
 pinId: number,
    pinUpdate: PinUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdatePinV1PinsPinIdPut>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof partialUpdatePinV1PinsPinIdPut>>,
          TError,
          Awaited<ReturnType<typeof partialUpdatePinV1PinsPinIdPut>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePartialUpdatePinV1PinsPinIdPut<TData = Awaited<ReturnType<typeof partialUpdatePinV1PinsPinIdPut>>, TError = ErrorType<HTTPValidationError>>(
 pinId: number,
    pinUpdate: PinUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdatePinV1PinsPinIdPut>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Partial Update Pin
 */

export function usePartialUpdatePinV1PinsPinIdPut<TData = Awaited<ReturnType<typeof partialUpdatePinV1PinsPinIdPut>>, TError = ErrorType<HTTPValidationError>>(
 pinId: number,
    pinUpdate: PinUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdatePinV1PinsPinIdPut>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPartialUpdatePinV1PinsPinIdPutQueryOptions(pinId,pinUpdate,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}


/**
 * @summary Partial Update Pin
 */
export const invalidatePartialUpdatePinV1PinsPinIdPut = async (
 queryClient: QueryClient, pinId: number,
    pinUpdate: PinUpdate, options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getPartialUpdatePinV1PinsPinIdPutQueryKey(pinId,pinUpdate) }, options);

  return queryClient;
}




export const getPartialUpdatePinV1PinsPinIdPatchUrl = (pinId: number,) => {




  return `/v1/pins/${pinId}`
}

/**
 * Update Pin
 *
 * Update the pin. Anything that you do not want to update can be left as `null`
 * @summary Partial Update Pin
 */
export const partialUpdatePinV1PinsPinIdPatch = async (pinId: number,
    pinUpdate: PinUpdate, options?: RequestInit): Promise<PinOut> => {

  return nexuscoreFetcher<PinOut>(getPartialUpdatePinV1PinsPinIdPatchUrl(pinId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(pinUpdate)
  }
);}





export const getPartialUpdatePinV1PinsPinIdPatchQueryKey = (pinId: number,
    pinUpdate?: PinUpdate,) => {
    return [
    'PATCH', `/v1/pins/${pinId}`, pinUpdate
    ] as const;
    }


export const getPartialUpdatePinV1PinsPinIdPatchQueryOptions = <TData = Awaited<ReturnType<typeof partialUpdatePinV1PinsPinIdPatch>>, TError = ErrorType<HTTPValidationError>>(pinId: number,
    pinUpdate: PinUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdatePinV1PinsPinIdPatch>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPartialUpdatePinV1PinsPinIdPatchQueryKey(pinId,pinUpdate);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof partialUpdatePinV1PinsPinIdPatch>>> = ({ signal }) => partialUpdatePinV1PinsPinIdPatch(pinId,pinUpdate, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: pinId !== null && pinId !== undefined,  staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof partialUpdatePinV1PinsPinIdPatch>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PartialUpdatePinV1PinsPinIdPatchQueryResult = NonNullable<Awaited<ReturnType<typeof partialUpdatePinV1PinsPinIdPatch>>>
export type PartialUpdatePinV1PinsPinIdPatchQueryError = ErrorType<HTTPValidationError>


export function usePartialUpdatePinV1PinsPinIdPatch<TData = Awaited<ReturnType<typeof partialUpdatePinV1PinsPinIdPatch>>, TError = ErrorType<HTTPValidationError>>(
 pinId: number,
    pinUpdate: PinUpdate, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdatePinV1PinsPinIdPatch>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof partialUpdatePinV1PinsPinIdPatch>>,
          TError,
          Awaited<ReturnType<typeof partialUpdatePinV1PinsPinIdPatch>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePartialUpdatePinV1PinsPinIdPatch<TData = Awaited<ReturnType<typeof partialUpdatePinV1PinsPinIdPatch>>, TError = ErrorType<HTTPValidationError>>(
 pinId: number,
    pinUpdate: PinUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdatePinV1PinsPinIdPatch>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof partialUpdatePinV1PinsPinIdPatch>>,
          TError,
          Awaited<ReturnType<typeof partialUpdatePinV1PinsPinIdPatch>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePartialUpdatePinV1PinsPinIdPatch<TData = Awaited<ReturnType<typeof partialUpdatePinV1PinsPinIdPatch>>, TError = ErrorType<HTTPValidationError>>(
 pinId: number,
    pinUpdate: PinUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdatePinV1PinsPinIdPatch>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Partial Update Pin
 */

export function usePartialUpdatePinV1PinsPinIdPatch<TData = Awaited<ReturnType<typeof partialUpdatePinV1PinsPinIdPatch>>, TError = ErrorType<HTTPValidationError>>(
 pinId: number,
    pinUpdate: PinUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdatePinV1PinsPinIdPatch>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPartialUpdatePinV1PinsPinIdPatchQueryOptions(pinId,pinUpdate,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}


/**
 * @summary Partial Update Pin
 */
export const invalidatePartialUpdatePinV1PinsPinIdPatch = async (
 queryClient: QueryClient, pinId: number,
    pinUpdate: PinUpdate, options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getPartialUpdatePinV1PinsPinIdPatchQueryKey(pinId,pinUpdate) }, options);

  return queryClient;
}




