export interface Project {
    name: string;
    description: string;
    coordinates: [number, number, number];
    dimension: string;
    owner_id: number;
    pin_id: number;
    project_id: string;
    thread_id: number;
    started_on: string;
    completed_on: string | null;
    status: 'ongoing' | 'completed' | 'abandoned';
    status_since: string;
    owner: {
        username: string;
        birthday: string;
        balance: number;
        active: boolean;
        role: string;
        patron: boolean;
        level: number;
        xp: number;
        required_xp: number;
        last_message: string;
        gamertag: string;
        whitelist: string;
        location: [number, number, number];
        dimension: string;
        hidden: boolean;
        thorny_id: number;
        user_id: string;
        guild_id: string;
        join_date: string;
        profile: {
            slogan: string;
            aboutme: string;
            lore: string;
            character_name: string;
            character_age: number;
            character_race: string;
            character_role: string;
            character_origin: string;
            character_beliefs: string;
            agility: number;
            valor: number;
            strength: number;
            charisma: number;
            creativity: number;
            ingenuity: number;
            thorny_id: number;
        };
    };
}