/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  InvalidateOptions,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  ItemCreateModel,
  ItemListModel,
  ItemModel,
  ItemUpdateModel,
  WorldOut,
  WorldUpdate
} from '../model';

import { nexuscoreFetcher } from '../../../lib/nexuscore-fetcher.ts';
import type { ErrorType } from '../../../lib/nexuscore-fetcher.ts';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetWorldV1GuildsMeWorldsGetUrl = () => {




  return `/v1/guilds/me/worlds`
}

/**
 * @summary Get World
 */
export const getWorldV1GuildsMeWorldsGet = async ( options?: Parameters<typeof nexuscoreFetcher>[1]): Promise<WorldOut> => {

  return nexuscoreFetcher<WorldOut>(getGetWorldV1GuildsMeWorldsGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetWorldV1GuildsMeWorldsGetQueryKey = () => {
    return [
    `/v1/guilds/me/worlds`
    ] as const;
    }


export const getGetWorldV1GuildsMeWorldsGetQueryOptions = <TData = Awaited<ReturnType<typeof getWorldV1GuildsMeWorldsGet>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorldV1GuildsMeWorldsGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWorldV1GuildsMeWorldsGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWorldV1GuildsMeWorldsGet>>> = ({ signal }) => getWorldV1GuildsMeWorldsGet({ signal, ...requestOptions });





   return  { queryKey, queryFn,   staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWorldV1GuildsMeWorldsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetWorldV1GuildsMeWorldsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getWorldV1GuildsMeWorldsGet>>>
export type GetWorldV1GuildsMeWorldsGetQueryError = ErrorType<unknown>


export function useGetWorldV1GuildsMeWorldsGet<TData = Awaited<ReturnType<typeof getWorldV1GuildsMeWorldsGet>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorldV1GuildsMeWorldsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorldV1GuildsMeWorldsGet>>,
          TError,
          Awaited<ReturnType<typeof getWorldV1GuildsMeWorldsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWorldV1GuildsMeWorldsGet<TData = Awaited<ReturnType<typeof getWorldV1GuildsMeWorldsGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorldV1GuildsMeWorldsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorldV1GuildsMeWorldsGet>>,
          TError,
          Awaited<ReturnType<typeof getWorldV1GuildsMeWorldsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWorldV1GuildsMeWorldsGet<TData = Awaited<ReturnType<typeof getWorldV1GuildsMeWorldsGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorldV1GuildsMeWorldsGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get World
 */

export function useGetWorldV1GuildsMeWorldsGet<TData = Awaited<ReturnType<typeof getWorldV1GuildsMeWorldsGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorldV1GuildsMeWorldsGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetWorldV1GuildsMeWorldsGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}


/**
 * @summary Get World
 */
export const invalidateGetWorldV1GuildsMeWorldsGet = async (
 queryClient: QueryClient,  options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getGetWorldV1GuildsMeWorldsGetQueryKey() }, options);

  return queryClient;
}




export const getPartialUpdateWorldV1GuildsMeWorldsPutUrl = () => {




  return `/v1/guilds/me/worlds`
}

/**
 * @summary Partial Update World
 */
export const partialUpdateWorldV1GuildsMeWorldsPut = async (worldUpdate: WorldUpdate, options?: Parameters<typeof nexuscoreFetcher>[1]): Promise<WorldOut> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return nexuscoreFetcher<WorldOut>(getPartialUpdateWorldV1GuildsMeWorldsPutUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(worldUpdate)
  }
);}





export const getPartialUpdateWorldV1GuildsMeWorldsPutMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof partialUpdateWorldV1GuildsMeWorldsPut>>, TError,{data: WorldUpdate}, TContext>, request?: SecondParameter<typeof nexuscoreFetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof partialUpdateWorldV1GuildsMeWorldsPut>>, TError,{data: WorldUpdate}, TContext> => {

const mutationKey = ['partialUpdateWorldV1GuildsMeWorldsPut'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof partialUpdateWorldV1GuildsMeWorldsPut>>, {data: WorldUpdate}> = (props) => {
          const {data} = props ?? {};

          return  partialUpdateWorldV1GuildsMeWorldsPut(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PartialUpdateWorldV1GuildsMeWorldsPutMutationResult = NonNullable<Awaited<ReturnType<typeof partialUpdateWorldV1GuildsMeWorldsPut>>>
    export type PartialUpdateWorldV1GuildsMeWorldsPutMutationBody = WorldUpdate
    export type PartialUpdateWorldV1GuildsMeWorldsPutMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Partial Update World
 */
export const usePartialUpdateWorldV1GuildsMeWorldsPut = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof partialUpdateWorldV1GuildsMeWorldsPut>>, TError,{data: WorldUpdate}, TContext>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof partialUpdateWorldV1GuildsMeWorldsPut>>,
        TError,
        {data: WorldUpdate},
        TContext
      > => {
      return useMutation(getPartialUpdateWorldV1GuildsMeWorldsPutMutationOptions(options), queryClient);
    }
    export const getPartialUpdateWorldV1GuildsMeWorldsPatchUrl = () => {




  return `/v1/guilds/me/worlds`
}

/**
 * @summary Partial Update World
 */
export const partialUpdateWorldV1GuildsMeWorldsPatch = async (worldUpdate: WorldUpdate, options?: Parameters<typeof nexuscoreFetcher>[1]): Promise<WorldOut> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return nexuscoreFetcher<WorldOut>(getPartialUpdateWorldV1GuildsMeWorldsPatchUrl(),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(worldUpdate)
  }
);}





export const getPartialUpdateWorldV1GuildsMeWorldsPatchMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof partialUpdateWorldV1GuildsMeWorldsPatch>>, TError,{data: WorldUpdate}, TContext>, request?: SecondParameter<typeof nexuscoreFetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof partialUpdateWorldV1GuildsMeWorldsPatch>>, TError,{data: WorldUpdate}, TContext> => {

const mutationKey = ['partialUpdateWorldV1GuildsMeWorldsPatch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof partialUpdateWorldV1GuildsMeWorldsPatch>>, {data: WorldUpdate}> = (props) => {
          const {data} = props ?? {};

          return  partialUpdateWorldV1GuildsMeWorldsPatch(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PartialUpdateWorldV1GuildsMeWorldsPatchMutationResult = NonNullable<Awaited<ReturnType<typeof partialUpdateWorldV1GuildsMeWorldsPatch>>>
    export type PartialUpdateWorldV1GuildsMeWorldsPatchMutationBody = WorldUpdate
    export type PartialUpdateWorldV1GuildsMeWorldsPatchMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Partial Update World
 */
export const usePartialUpdateWorldV1GuildsMeWorldsPatch = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof partialUpdateWorldV1GuildsMeWorldsPatch>>, TError,{data: WorldUpdate}, TContext>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof partialUpdateWorldV1GuildsMeWorldsPatch>>,
        TError,
        {data: WorldUpdate},
        TContext
      > => {
      return useMutation(getPartialUpdateWorldV1GuildsMeWorldsPatchMutationOptions(options), queryClient);
    }
    export const getListItemsV1GuildsMeWorldsItemsGetUrl = () => {




  return `/v1/guilds/me/worlds/items`
}

/**
 * Get All Item
 *
 * This returns a list of all Items
 * @summary List Items
 */
export const listItemsV1GuildsMeWorldsItemsGet = async ( options?: Parameters<typeof nexuscoreFetcher>[1]): Promise<ItemListModel> => {

  return nexuscoreFetcher<ItemListModel>(getListItemsV1GuildsMeWorldsItemsGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListItemsV1GuildsMeWorldsItemsGetQueryKey = () => {
    return [
    `/v1/guilds/me/worlds/items`
    ] as const;
    }


export const getListItemsV1GuildsMeWorldsItemsGetQueryOptions = <TData = Awaited<ReturnType<typeof listItemsV1GuildsMeWorldsItemsGet>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listItemsV1GuildsMeWorldsItemsGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListItemsV1GuildsMeWorldsItemsGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listItemsV1GuildsMeWorldsItemsGet>>> = ({ signal }) => listItemsV1GuildsMeWorldsItemsGet({ signal, ...requestOptions });





   return  { queryKey, queryFn,   staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listItemsV1GuildsMeWorldsItemsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListItemsV1GuildsMeWorldsItemsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listItemsV1GuildsMeWorldsItemsGet>>>
export type ListItemsV1GuildsMeWorldsItemsGetQueryError = ErrorType<unknown>


export function useListItemsV1GuildsMeWorldsItemsGet<TData = Awaited<ReturnType<typeof listItemsV1GuildsMeWorldsItemsGet>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listItemsV1GuildsMeWorldsItemsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listItemsV1GuildsMeWorldsItemsGet>>,
          TError,
          Awaited<ReturnType<typeof listItemsV1GuildsMeWorldsItemsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListItemsV1GuildsMeWorldsItemsGet<TData = Awaited<ReturnType<typeof listItemsV1GuildsMeWorldsItemsGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listItemsV1GuildsMeWorldsItemsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listItemsV1GuildsMeWorldsItemsGet>>,
          TError,
          Awaited<ReturnType<typeof listItemsV1GuildsMeWorldsItemsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListItemsV1GuildsMeWorldsItemsGet<TData = Awaited<ReturnType<typeof listItemsV1GuildsMeWorldsItemsGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listItemsV1GuildsMeWorldsItemsGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Items
 */

export function useListItemsV1GuildsMeWorldsItemsGet<TData = Awaited<ReturnType<typeof listItemsV1GuildsMeWorldsItemsGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listItemsV1GuildsMeWorldsItemsGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListItemsV1GuildsMeWorldsItemsGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}


/**
 * @summary List Items
 */
export const invalidateListItemsV1GuildsMeWorldsItemsGet = async (
 queryClient: QueryClient,  options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getListItemsV1GuildsMeWorldsItemsGetQueryKey() }, options);

  return queryClient;
}




export const getCreateItemV1GuildsMeWorldsItemsPostUrl = () => {




  return `/v1/guilds/me/worlds/items`
}

/**
 * Create New Item
 *
 * Creates a new item to be available for sacrificing
 * If an item with these ID's already exists, it returns a 500.
 * @summary Create Item
 */
export const createItemV1GuildsMeWorldsItemsPost = async (itemCreateModel: ItemCreateModel, options?: Parameters<typeof nexuscoreFetcher>[1]): Promise<ItemModel> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return nexuscoreFetcher<ItemModel>(getCreateItemV1GuildsMeWorldsItemsPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(itemCreateModel)
  }
);}





export const getCreateItemV1GuildsMeWorldsItemsPostMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createItemV1GuildsMeWorldsItemsPost>>, TError,{data: ItemCreateModel}, TContext>, request?: SecondParameter<typeof nexuscoreFetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof createItemV1GuildsMeWorldsItemsPost>>, TError,{data: ItemCreateModel}, TContext> => {

const mutationKey = ['createItemV1GuildsMeWorldsItemsPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createItemV1GuildsMeWorldsItemsPost>>, {data: ItemCreateModel}> = (props) => {
          const {data} = props ?? {};

          return  createItemV1GuildsMeWorldsItemsPost(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateItemV1GuildsMeWorldsItemsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createItemV1GuildsMeWorldsItemsPost>>>
    export type CreateItemV1GuildsMeWorldsItemsPostMutationBody = ItemCreateModel
    export type CreateItemV1GuildsMeWorldsItemsPostMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Create Item
 */
export const useCreateItemV1GuildsMeWorldsItemsPost = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createItemV1GuildsMeWorldsItemsPost>>, TError,{data: ItemCreateModel}, TContext>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createItemV1GuildsMeWorldsItemsPost>>,
        TError,
        {data: ItemCreateModel},
        TContext
      > => {
      return useMutation(getCreateItemV1GuildsMeWorldsItemsPostMutationOptions(options), queryClient);
    }
    export const getGetItemV1GuildsMeWorldsItemsItemIdGetUrl = (itemId: string,) => {




  return `/v1/guilds/me/worlds/items/${itemId}`
}

/**
 * Get Item
 *
 * This returns the Item
 * @summary Get Item
 */
export const getItemV1GuildsMeWorldsItemsItemIdGet = async (itemId: string, options?: Parameters<typeof nexuscoreFetcher>[1]): Promise<ItemModel> => {

  return nexuscoreFetcher<ItemModel>(getGetItemV1GuildsMeWorldsItemsItemIdGetUrl(itemId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetItemV1GuildsMeWorldsItemsItemIdGetQueryKey = (itemId: string,) => {
    return [
    `/v1/guilds/me/worlds/items/${itemId}`
    ] as const;
    }


export const getGetItemV1GuildsMeWorldsItemsItemIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getItemV1GuildsMeWorldsItemsItemIdGet>>, TError = ErrorType<HTTPValidationError>>(itemId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItemV1GuildsMeWorldsItemsItemIdGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetItemV1GuildsMeWorldsItemsItemIdGetQueryKey(itemId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getItemV1GuildsMeWorldsItemsItemIdGet>>> = ({ signal }) => getItemV1GuildsMeWorldsItemsItemIdGet(itemId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: itemId !== null && itemId !== undefined,  staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getItemV1GuildsMeWorldsItemsItemIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetItemV1GuildsMeWorldsItemsItemIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getItemV1GuildsMeWorldsItemsItemIdGet>>>
export type GetItemV1GuildsMeWorldsItemsItemIdGetQueryError = ErrorType<HTTPValidationError>


export function useGetItemV1GuildsMeWorldsItemsItemIdGet<TData = Awaited<ReturnType<typeof getItemV1GuildsMeWorldsItemsItemIdGet>>, TError = ErrorType<HTTPValidationError>>(
 itemId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItemV1GuildsMeWorldsItemsItemIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getItemV1GuildsMeWorldsItemsItemIdGet>>,
          TError,
          Awaited<ReturnType<typeof getItemV1GuildsMeWorldsItemsItemIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetItemV1GuildsMeWorldsItemsItemIdGet<TData = Awaited<ReturnType<typeof getItemV1GuildsMeWorldsItemsItemIdGet>>, TError = ErrorType<HTTPValidationError>>(
 itemId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItemV1GuildsMeWorldsItemsItemIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getItemV1GuildsMeWorldsItemsItemIdGet>>,
          TError,
          Awaited<ReturnType<typeof getItemV1GuildsMeWorldsItemsItemIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetItemV1GuildsMeWorldsItemsItemIdGet<TData = Awaited<ReturnType<typeof getItemV1GuildsMeWorldsItemsItemIdGet>>, TError = ErrorType<HTTPValidationError>>(
 itemId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItemV1GuildsMeWorldsItemsItemIdGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Item
 */

export function useGetItemV1GuildsMeWorldsItemsItemIdGet<TData = Awaited<ReturnType<typeof getItemV1GuildsMeWorldsItemsItemIdGet>>, TError = ErrorType<HTTPValidationError>>(
 itemId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItemV1GuildsMeWorldsItemsItemIdGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetItemV1GuildsMeWorldsItemsItemIdGetQueryOptions(itemId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}


/**
 * @summary Get Item
 */
export const invalidateGetItemV1GuildsMeWorldsItemsItemIdGet = async (
 queryClient: QueryClient, itemId: string, options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getGetItemV1GuildsMeWorldsItemsItemIdGetQueryKey(itemId) }, options);

  return queryClient;
}




export const getPartialUpdateItemV1GuildsMeWorldsItemsItemIdPutUrl = (itemId: string,) => {




  return `/v1/guilds/me/worlds/items/${itemId}`
}

/**
 * Update Item
 *
 * This updates an item. All fields are optional, meaning you may
 * set a field to `null` to not update it.
 * @summary Partial Update Item
 */
export const partialUpdateItemV1GuildsMeWorldsItemsItemIdPut = async (itemId: string,
    itemUpdateModel: ItemUpdateModel, options?: Parameters<typeof nexuscoreFetcher>[1]): Promise<ItemModel> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return nexuscoreFetcher<ItemModel>(getPartialUpdateItemV1GuildsMeWorldsItemsItemIdPutUrl(itemId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(itemUpdateModel)
  }
);}





export const getPartialUpdateItemV1GuildsMeWorldsItemsItemIdPutMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof partialUpdateItemV1GuildsMeWorldsItemsItemIdPut>>, TError,{itemId: string;data: ItemUpdateModel}, TContext>, request?: SecondParameter<typeof nexuscoreFetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof partialUpdateItemV1GuildsMeWorldsItemsItemIdPut>>, TError,{itemId: string;data: ItemUpdateModel}, TContext> => {

const mutationKey = ['partialUpdateItemV1GuildsMeWorldsItemsItemIdPut'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof partialUpdateItemV1GuildsMeWorldsItemsItemIdPut>>, {itemId: string;data: ItemUpdateModel}> = (props) => {
          const {itemId,data} = props ?? {};

          return  partialUpdateItemV1GuildsMeWorldsItemsItemIdPut(itemId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PartialUpdateItemV1GuildsMeWorldsItemsItemIdPutMutationResult = NonNullable<Awaited<ReturnType<typeof partialUpdateItemV1GuildsMeWorldsItemsItemIdPut>>>
    export type PartialUpdateItemV1GuildsMeWorldsItemsItemIdPutMutationBody = ItemUpdateModel
    export type PartialUpdateItemV1GuildsMeWorldsItemsItemIdPutMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Partial Update Item
 */
export const usePartialUpdateItemV1GuildsMeWorldsItemsItemIdPut = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof partialUpdateItemV1GuildsMeWorldsItemsItemIdPut>>, TError,{itemId: string;data: ItemUpdateModel}, TContext>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof partialUpdateItemV1GuildsMeWorldsItemsItemIdPut>>,
        TError,
        {itemId: string;data: ItemUpdateModel},
        TContext
      > => {
      return useMutation(getPartialUpdateItemV1GuildsMeWorldsItemsItemIdPutMutationOptions(options), queryClient);
    }
    export const getPartialUpdateItemV1GuildsMeWorldsItemsItemIdPatchUrl = (itemId: string,) => {




  return `/v1/guilds/me/worlds/items/${itemId}`
}

/**
 * Update Item
 *
 * This updates an item. All fields are optional, meaning you may
 * set a field to `null` to not update it.
 * @summary Partial Update Item
 */
export const partialUpdateItemV1GuildsMeWorldsItemsItemIdPatch = async (itemId: string,
    itemUpdateModel: ItemUpdateModel, options?: Parameters<typeof nexuscoreFetcher>[1]): Promise<ItemModel> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return nexuscoreFetcher<ItemModel>(getPartialUpdateItemV1GuildsMeWorldsItemsItemIdPatchUrl(itemId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(itemUpdateModel)
  }
);}





export const getPartialUpdateItemV1GuildsMeWorldsItemsItemIdPatchMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof partialUpdateItemV1GuildsMeWorldsItemsItemIdPatch>>, TError,{itemId: string;data: ItemUpdateModel}, TContext>, request?: SecondParameter<typeof nexuscoreFetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof partialUpdateItemV1GuildsMeWorldsItemsItemIdPatch>>, TError,{itemId: string;data: ItemUpdateModel}, TContext> => {

const mutationKey = ['partialUpdateItemV1GuildsMeWorldsItemsItemIdPatch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof partialUpdateItemV1GuildsMeWorldsItemsItemIdPatch>>, {itemId: string;data: ItemUpdateModel}> = (props) => {
          const {itemId,data} = props ?? {};

          return  partialUpdateItemV1GuildsMeWorldsItemsItemIdPatch(itemId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PartialUpdateItemV1GuildsMeWorldsItemsItemIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof partialUpdateItemV1GuildsMeWorldsItemsItemIdPatch>>>
    export type PartialUpdateItemV1GuildsMeWorldsItemsItemIdPatchMutationBody = ItemUpdateModel
    export type PartialUpdateItemV1GuildsMeWorldsItemsItemIdPatchMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Partial Update Item
 */
export const usePartialUpdateItemV1GuildsMeWorldsItemsItemIdPatch = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof partialUpdateItemV1GuildsMeWorldsItemsItemIdPatch>>, TError,{itemId: string;data: ItemUpdateModel}, TContext>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof partialUpdateItemV1GuildsMeWorldsItemsItemIdPatch>>,
        TError,
        {itemId: string;data: ItemUpdateModel},
        TContext
      > => {
      return useMutation(getPartialUpdateItemV1GuildsMeWorldsItemsItemIdPatchMutationOptions(options), queryClient);
    }
