/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import type { Scope } from './scope.ts';

export interface ClientCreateRequest {
  /** The name of the client */
  client_name: string;
  /** The guild ID of the client */
  guild_id: number;
  /** The requested scopes of the client */
  scopes: Scope[];
}
