/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */

/**
 * The type of connection
 */
export type ConnectionOutType = typeof ConnectionOutType[keyof typeof ConnectionOutType];


export const ConnectionOutType = {
  connect: 'connect',
  disconnect: 'disconnect',
} as const;
