/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */

/**
 * The type of connection
 */
export type ConnectionInType = typeof ConnectionInType[keyof typeof ConnectionInType];


export const ConnectionInType = {
  connect: 'connect',
  disconnect: 'disconnect',
} as const;
