/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import type { ContentInDataItem } from './contentInDataItem';

export interface ContentIn {
  /** The page this content belongs to */
  page_id: number;
  /** The ThornyID of the user who edited this content */
  edited_by: number;
  editor_type: string | null;
  /** A note describing what changed in this version */
  change_note: string;
  /** The full React editor document as an opaque JSON object */
  data: ContentInDataItem[];
}
