/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import type { LocationCustomization } from './locationCustomization.ts';
import type { MainhandCustomization } from './mainhandCustomization.ts';
import type { MaximumDeathsCustomization } from './maximumDeathsCustomization.ts';
import type { NaturalBlockCustomization } from './naturalBlockCustomization.ts';
import type { TimerCustomization } from './timerCustomization.ts';

export interface Customizations {
  /** Mainhand Customization */
  mainhand?: MainhandCustomization | null;
  /** Location Customization */
  location?: LocationCustomization | null;
  /** Timer Customization */
  timer?: TimerCustomization | null;
  /** Maximum Deaths Customization */
  maximum_deaths?: MaximumDeathsCustomization | null;
  /** Natural Block Customization */
  natural_block?: NaturalBlockCustomization | null;
}
