/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */

export interface DailyPlaytime {
  /** Total playtime in seconds */
  day: string;
  /** The day's playtime in seconds */
  playtime: number;
}
