/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */

export interface DamageModel {
  /** The metadata type */
  metadata_type: 'damage';
  /** The percentage of durability the item should lose */
  damage_percentage: number;
}
