/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import type { CountdownBlock } from './countdownBlock';
import type { CtaBannerBlock } from './ctaBannerBlock';
import type { DividerBlock } from './dividerBlock';
import type { FaqBlock } from './faqBlock';
import type { HeroBlock } from './heroBlock';
import type { HighlightGridBlock } from './highlightGridBlock';
import type { MediaGalleryBlock } from './mediaGalleryBlock';
import type { NarrativeBlock } from './narrativeBlock';
import type { PrizeTiersBlock } from './prizeTiersBlock';
import type { RulesColumnsBlock } from './rulesColumnsBlock';
import type { StatRowBlock } from './statRowBlock';

export interface EventUpdate {
  title?: string | null;
  description?: string | null;
  image_url?: string | null;
  start_time?: string | null;
  end_time?: string | null;
  status?: 'draft' | 'published' | 'archived' | null;
  blocks?: (HeroBlock | CountdownBlock | StatRowBlock | NarrativeBlock | HighlightGridBlock | PrizeTiersBlock | RulesColumnsBlock | FaqBlock | MediaGalleryBlock | CtaBannerBlock | DividerBlock)[] | null;
}
