/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */

/**
 * The status of the event
 */
export type EventInStatus = typeof EventInStatus[keyof typeof EventInStatus];


export const EventInStatus = {
  draft: 'draft',
  published: 'published',
  archived: 'archived',
} as const;
