/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import type { GuildDailyPlaytime } from './guildDailyPlaytime.ts';
import type { GuildMonthlyPlaytime } from './guildMonthlyPlaytime.ts';
import type { GuildWeeklyPlaytime } from './guildWeeklyPlaytime.ts';

export interface GuildPlaytimeAnalysis {
  /** The total playtime of this guild in seconds */
  total_playtime: number;
  /** The total unique players that have played on this guild */
  total_unique_players: number;
  /** Data about the last 7 days of playtime */
  daily_playtime: GuildDailyPlaytime[];
  /** Data about the last 8 weeks of playtime */
  weekly_playtime: GuildWeeklyPlaytime[];
  /** Data about the last 12 months of playtime */
  monthly_playtime: GuildMonthlyPlaytime[];
  /** @nullable */
  peak_playtime_periods?: null;
  /** @nullable */
  peak_active_periods?: null;
  /** @nullable */
  daily_playtime_distribution?: null;
  /** @nullable */
  anomalies?: null;
  /** @nullable */
  predictive_insights?: null;
}
