/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */

export interface HighlightItem {
  /** Phosphor icon component name */
  icon: string;
  /** The highlight title */
  title: string;
  /** Optional subtitle */
  subtitle?: string | null;
  /** Short description of this highlight */
  description: string;
  /** Optional Tailwind color class for the icon */
  color?: string | null;
}
