/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import type { InteractionStatistic } from './interactionStatistic.ts';

export type InteractionStatisticsList = InteractionStatistic[];
