/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */

/**
 * The type of interaction
 */
export type InteractionInType = typeof InteractionInType[keyof typeof InteractionInType];


export const InteractionInType = {
  kill: 'kill',
  mine: 'mine',
  place: 'place',
  use: 'use',
  die: 'die',
  scriptevent: 'scriptevent',
} as const;
