/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import type { InteractionOutType } from './interactionOutType';

export interface InteractionOut {
  /** The ID of the interaction */
  interaction_id: number;
  /** The ThornyID of the user */
  thorny_id: number;
  /** The type of interaction */
  type: InteractionOutType;
  /**
     * The coordinates of the interaction
     * @minItems 3
     * @maxItems 3
     */
  coordinates: [number, number, number];
  /**
     * The reference of the interaction
     * @pattern ^([a-z]+:[0-9a-z_*]+|[A-Za-z0-9_ \-\.]+)$
     */
  reference: string;
  mainhand: string | null;
  /** The time of the interaction */
  time: string;
  /**
     * The dimension of the interaction
     * @pattern ^([a-z]+:[0-9a-z_*]+|[A-Za-z0-9_ \-\.]+)$
     */
  dimension: string;
}
