/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */

export interface ItemModel {
  /**
     * The minecraft ID of the item
     * @pattern ^[a-z]+:[a-z_0-9]+$
     */
  item_id: string;
  /** The initial block value of one of this item */
  value: number;
  /** The maximum uses this item will have before it's value starts going into the negatives */
  max_uses: number;
  /** The depreciation of this item */
  depreciation: number;
  /** The current uses of this item */
  current_uses: number;
}
