/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */

export type ListWikiPagesV1GuildsMeWikiGetParams = {
/**
 * Filter by published status
 */
published?: boolean | null;
/**
 * Filter by category
 */
category?: string | null;
/**
 * Filter by tags
 */
tags?: string[] | null;
/**
 * Fuzzy search by page title (summary and content comes later)
 */
search?: string | null;
/**
 * Sort by field
 */
sort_by?: 'created_at' | 'updated_at' | 'title' | null;
/**
 * Sort order
 */
sort_order?: 'asc' | 'desc' | null;
/**
 * The page number to return
 */
page?: number | null;
/**
 * The number of items per page
 */
page_size?: number | null;
};
