/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */

export type ListSessionsV1GuildsMeSessionsGetParams = {
/**
 * Filter by active sessions
 */
active?: boolean | null;
/**
 * Start time to filter by
 */
time_start?: string | null;
/**
 * End time to filter by
 */
time_end?: string | null;
/**
 * The page number of the results. Defaults to 1
 */
page?: number | null;
/**
 * The number of results per page. Defaults to 100
 */
page_size?: number | null;
};
