/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */

export type ListWikiPagesV1GuildsMeWikiGetSortBy = typeof ListWikiPagesV1GuildsMeWikiGetSortBy[keyof typeof ListWikiPagesV1GuildsMeWikiGetSortBy] | null;


export const ListWikiPagesV1GuildsMeWikiGetSortBy = {
  created_at: 'created_at',
  updated_at: 'updated_at',
  title: 'title',
} as const;
