/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */

export interface ObjectiveStatistics {
  /** The objective ID */
  objective_id: number;
  /** The order of the objective, used for funnel sorting */
  order_index: number;
  /** The objective description */
  description: string;
  /** Number of players who started this objective */
  players_reached: number;
  /** Number of players who completed this objective */
  players_completed: number;
  /** Number of players who failed this objective */
  players_failed: number;
  /** players_completed / players_reached. 0 if none reached. */
  completion_rate: number;
  /** players_failed / players_reached. 0 if none reached. */
  drop_rate: number;
  /** Average time in seconds spent on this objective (start_time to end_time), across completions */
  avg_time_seconds?: number | null;
  /** Median time in seconds spent on this objective, across completions */
  median_time_seconds?: number | null;
}
