/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import type { CustomizationProgress } from './customizationProgress';
import type { KillTargetProgressModel } from './killTargetProgressModel';
import type { MineTargetProgressModel } from './mineTargetProgressModel';
import type { ScriptEventTargetProgressModel } from './scriptEventTargetProgressModel';

export interface ObjectiveProgressUpdate {
  objective_id?: number | null;
  start_time?: string | null;
  end_time?: string | null;
  status?: 'active' | 'pending' | 'completed' | 'failed' | null;
  target_progress?: (MineTargetProgressModel | KillTargetProgressModel | ScriptEventTargetProgressModel)[] | null;
  customization_progress?: CustomizationProgress | null;
}
