/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import type { Customizations } from './customizations';
import type { KillTargetModel } from './killTargetModel';
import type { MineTargetModel } from './mineTargetModel';
import type { RewardUpdate } from './rewardUpdate';
import type { ScriptEventTargetModel } from './scriptEventTargetModel';

export interface ObjectiveUpdate {
  objective_id?: number | null;
  description?: string | null;
  display?: string | null;
  order_index?: number | null;
  objective_type?: 'kill' | 'mine' | 'scriptevent' | null;
  logic?: 'and' | 'or' | 'sequential' | null;
  target_count?: number | null;
  targets?: (MineTargetModel | KillTargetModel | ScriptEventTargetModel)[] | null;
  customizations?: Customizations | null;
  rewards?: RewardUpdate[] | null;
}
