/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import type { Customizations } from './customizations.ts';
import type { KillTargetModel } from './killTargetModel.ts';
import type { MineTargetModel } from './mineTargetModel.ts';
import type { ObjectiveUpdateLogic } from './objectiveUpdateLogic.ts';
import type { ObjectiveUpdateObjectiveType } from './objectiveUpdateObjectiveType.ts';
import type { RewardUpdate } from './rewardUpdate.ts';
import type { ScriptEventTargetModel } from './scriptEventTargetModel.ts';

export interface ObjectiveUpdate {
  objective_id?: number | null;
  description?: string | null;
  display?: string | null;
  order_index?: number | null;
  objective_type?: ObjectiveUpdateObjectiveType;
  logic?: ObjectiveUpdateLogic;
  target_count?: number | null;
  targets?: (MineTargetModel | KillTargetModel | ScriptEventTargetModel)[] | null;
  customizations?: Customizations | null;
  rewards?: RewardUpdate[] | null;
}
