/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */

/**
 * The logic to be applied to the objective targets
 */
export type ObjectiveOutLogic = typeof ObjectiveOutLogic[keyof typeof ObjectiveOutLogic];


export const ObjectiveOutLogic = {
  and: 'and',
  or: 'or',
  sequential: 'sequential',
} as const;
