/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import type { Customizations } from './customizations';
import type { KillTargetModel } from './killTargetModel';
import type { MineTargetModel } from './mineTargetModel';
import type { ObjectiveInLogic } from './objectiveInLogic';
import type { ObjectiveInObjectiveType } from './objectiveInObjectiveType';
import type { RewardIn } from './rewardIn';
import type { ScriptEventTargetModel } from './scriptEventTargetModel';

export interface ObjectiveIn {
  /** The description of the objective */
  description: string;
  display?: string | null;
  /** The order of the objective. Starts at 0. */
  order_index: number;
  /** The type of objective: kill, mine or scriptevent */
  objective_type: ObjectiveInObjectiveType;
  /** The logic to be applied to the objective targets */
  logic: ObjectiveInLogic;
  target_count?: number | null;
  /** The targets of the objective. Target types must be equal to `objective_type` */
  targets: (MineTargetModel | KillTargetModel | ScriptEventTargetModel)[];
  /** The customizations of the objective */
  customizations: Customizations;
  rewards: RewardIn[];
}
