/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import type { CustomizationProgress } from './customizationProgress.ts';
import type { KillTargetProgressModel } from './killTargetProgressModel.ts';
import type { MineTargetProgressModel } from './mineTargetProgressModel.ts';
import type { ObjectiveProgressOutStatus } from './objectiveProgressOutStatus.ts';
import type { ScriptEventTargetProgressModel } from './scriptEventTargetProgressModel.ts';
import type { VisitTargetProgressModel } from './visitTargetProgressModel.ts';

export interface ObjectiveProgressOut {
  /** The quest progress ID */
  progress_id: number;
  /** The objective ID */
  objective_id: number;
  start_time: string | null;
  end_time: string | null;
  /** The status of this objective */
  status: ObjectiveProgressOutStatus;
  /** List of each objective target's progress */
  target_progress: (MineTargetProgressModel | KillTargetProgressModel | ScriptEventTargetProgressModel | VisitTargetProgressModel)[];
  /** Specific customization info to track */
  customization_progress: CustomizationProgress;
}
