/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */

export type ObjectiveUpdateLogic = typeof ObjectiveUpdateLogic[keyof typeof ObjectiveUpdateLogic];


export const ObjectiveUpdateLogic = {
  and: 'and',
  or: 'or',
  sequential: 'sequential',
} as const;
