/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import type { ContentOut } from './contentOut.ts';
import type { ProjectOut } from './projectOut.ts';
import type { UserOut } from './userOut.ts';

export interface PageOut {
  /** The URL-safe slug ID of the page */
  slug: string;
  /** The title of the wiki page */
  title: string;
  summary: string | null;
  /** The category this page belongs to */
  category: string;
  /** Tags for categorizing the page */
  tags: string[];
  cover_image: string | null;
  /** Whether the page is publicly visible */
  published: boolean;
  /** Whether the page is locked to prevent unauthorized edits */
  locked: boolean;
  /** The number of times this page has been viewed */
  view_count: number;
  /** When the page was created */
  created_at: string;
  /** When the page was last updated */
  updated_at: string;
  author: UserOut;
  project?: ProjectOut | null;
  content: ContentOut;
}
