/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */

export interface PinUpdate {
  name?: string | null;
  description?: string | null;
  coordinates?: number[] | null;
  dimension?: string | null;
  pin_type?: string | null;
}
