/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import type { DailyPlaytimeList } from './dailyPlaytimeList';
import type { MonthlyPlaytimeList } from './monthlyPlaytimeList';

export interface PlaytimeSummary {
  /** The ThornyID of a user */
  thorny_id: number;
  /** Total playtime in seconds */
  total: number;
  /** The date and time when the user connected, or `null` */
  session: string | null;
  /** The list of playtime in seconds each day. Up to 7 days. */
  daily: DailyPlaytimeList;
  /** The list of playtime in seconds each month. Up to 12 months. */
  monthly: MonthlyPlaytimeList;
}
