/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */

export interface PotionModel {
  /** The metadata type */
  metadata_type: 'potion';
  /**
     * The potion effect type
     * @pattern ^([a-z]+:[0-9a-z_*]+|[A-Za-z0-9_ \-\.]+)$
     */
  potion_effect: string;
  /** The potion delivery type */
  potion_delivery: string;
}
