/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import type { PresignInContentType } from './presignInContentType.ts';

export interface PresignIn {
  /**
     * Original filename, including extension
     * @minLength 1
     * @maxLength 255
     * @pattern ^[\w\-. ]+\.[A-Za-z0-9]+$
     */
  filename: string;
  /** MIME type of the file being uploaded */
  content_type: PresignInContentType;
}
