/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */

export interface PresignOut {
  /** Short-lived presigned PUT URL for uploading directly to R2 */
  upload_url: string;
  /** Object key/path in the R2 bucket */
  key: string;
  /** Permanent public/CDN URL once the upload completes */
  public_url: string;
}
