/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */

export interface ProjectIn {
  /** The project owner ID */
  owner_id: number;
  /** The coordinates of the project */
  coordinates: number[];
  /** A short description of the project */
  description: string;
  /** The dimension of the project */
  dimension: string;
  /** The name of the project */
  name: string;
  pin_id: number | null;
}
