/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import type { ObjectiveProgressUpdate } from './objectiveProgressUpdate.ts';
import type { QuestProgressUpdateStatus } from './questProgressUpdateStatus.ts';

export interface QuestProgressUpdate {
  start_time?: string | null;
  end_time?: string | null;
  status?: QuestProgressUpdateStatus;
  objectives?: ObjectiveProgressUpdate[] | null;
}
