/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */

export type QuestProgressUpdateStatus = typeof QuestProgressUpdateStatus[keyof typeof QuestProgressUpdateStatus] | null;


export const QuestProgressUpdateStatus = {
  active: 'active',
  pending: 'pending',
  completed: 'completed',
  failed: 'failed',
} as const;
