/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import type { ObjectiveUpdate } from './objectiveUpdate';

export interface QuestUpdate {
  start_time?: string | null;
  end_time?: string | null;
  title?: string | null;
  description?: string | null;
  tags?: string[] | null;
  quest_type?: string | null;
  created_by?: number | null;
  objectives?: ObjectiveUpdate[] | null;
}
