/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */

export interface QuestProgressIn {
  /** The ThornyID of the user */
  thorny_id: number;
  /** The ID of the quest */
  quest_id: number;
}
