/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import type { ObjectiveProgressUpdate } from './objectiveProgressUpdate';

export interface QuestProgressUpdate {
  start_time?: string | null;
  end_time?: string | null;
  status?: 'active' | 'pending' | 'completed' | 'failed' | null;
  objectives?: ObjectiveProgressUpdate[] | null;
}
