/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */

export interface RandomEnchantmentModel {
  /** The metadata type */
  metadata_type: 'enchantment_random';
  /** The minimum XP Level to use for the random enchantments */
  level_min: number;
  /** The maximum XP Level to use for the random enchantments */
  level_max: number;
  /** Whether treasure enchantments are allowed to be added */
  treasure: boolean;
}
