/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import type { RelayModelType } from './relayModelType';

export interface RelayModel {
  /** The type of relay */
  type: RelayModelType;
  /** The content of the message */
  content: string;
  /** The title of the embed */
  embed_title: string;
  /** The content of the embed */
  embed_content: string;
  /** The name to use for the webhook */
  name?: string | null;
}
