/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import type { DamageModel } from './damageModel';
import type { EnchantmentModel } from './enchantmentModel';
import type { LoreModel } from './loreModel';
import type { NameModel } from './nameModel';
import type { PotionModel } from './potionModel';
import type { RandomEnchantmentModel } from './randomEnchantmentModel';

export interface RewardIn {
  balance: number | null;
  item: string | null;
  count: number | null;
  display_name: string | null;
  /** The metadata for the item reward, to add extra customization */
  item_metadata: (EnchantmentModel | RandomEnchantmentModel | PotionModel | NameModel | LoreModel | DamageModel)[];
}
