/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import type { DamageModel } from './damageModel.ts';
import type { EnchantmentModel } from './enchantmentModel.ts';
import type { LoreModel } from './loreModel.ts';
import type { NameModel } from './nameModel.ts';
import type { PotionModel } from './potionModel.ts';
import type { RandomEnchantmentModel } from './randomEnchantmentModel.ts';

export interface RewardOut {
  /** The ID of this reward */
  reward_id: number;
  balance: number | null;
  item: string | null;
  count: number | null;
  display_name: string | null;
  /** The metadata for the item reward, to add extra customization */
  item_metadata: (EnchantmentModel | RandomEnchantmentModel | PotionModel | NameModel | LoreModel | DamageModel)[];
}
