/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */

export type Scope = typeof Scope[keyof typeof Scope];


export const Scope = {
  'guilds:read': 'guilds:read',
  'guilds:write': 'guilds:write',
  'guildsmembers:read': 'guilds.members:read',
  'guildsmembers:write': 'guilds.members:write',
  'guildsprojects:read': 'guilds.projects:read',
  'guildsprojects:write': 'guilds.projects:write',
  'guildspins:read': 'guilds.pins:read',
  'guildspins:write': 'guilds.pins:write',
  'guildsquests:read': 'guilds.quests:read',
  'guildsquests:write': 'guilds.quests:write',
  'events:read': 'events:read',
  'events:write': 'events:write',
  'server:read': 'server:read',
  'admin:clients': 'admin:clients',
  'admin:guilds': 'admin:guilds',
} as const;
