/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */

export interface ScriptEventTargetProgressModel {
  /** The target uuid */
  target_uuid?: string;
  /** The type of the target. Must be equal to `objective_type`. */
  target_type: 'scriptevent';
  /** The number of Script ID's logged so far */
  count?: number;
}
