/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */

export interface TokenResponse {
  /** The JWT token */
  access_token: string;
  /** The token type, always `bearer` */
  token_type?: 'bearer';
  /** The number of seconds until the token expires. Typical lifetime is 60 minutes */
  expires_in: number;
  /** The scopes granted by the token, could be a subset of requested scopes */
  scope: string[];
}
