/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */

export interface UserIn {
  /** The Discord user ID. */
  user_id: number;
  username: string | null;
}
