/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */

export interface VisitTargetProgressModel {
  /** The target uuid */
  target_uuid?: string;
  target_type: 'visit';
  /** The number of this target to be reached. At least 1. */
  count?: number;
  /** The number of seconds spent in the area so far */
  seconds?: number;
}
