/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import type { WaypointWaypointType } from './waypointWaypointType.ts';

export interface Waypoint {
  /**
     * The coordinates to show the waypoint at
     * @minItems 3
     * @maxItems 3
     */
  coordinates: [number, number, number];
  /** The type of waypoint to show */
  waypoint_type: WaypointWaypointType;
  /**
     * The dimension to show the waypoint in
     * @pattern ^([a-z]+:[0-9a-z_*]+|[A-Za-z0-9_ \-\.]+)$
     */
  dimension?: string;
}
