/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */

/**
 * The type of waypoint to show
 */
export type WaypointWaypointType = typeof WaypointWaypointType[keyof typeof WaypointWaypointType];


export const WaypointWaypointType = {
  star: 'star',
  question: 'question',
} as const;
