/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import type { Waypoint } from './waypoint.ts';

export interface WaypointCustomization {
  /** The waypoints to show */
  waypoints: Waypoint[];
}
