/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */

export interface WorldOut {
  /** The guild ID that corresponds to this world */
  guild_id: number;
  /** The Overworld border size */
  overworld_border: number;
  /** The Nether border size */
  nether_border: number;
  /** The End border size */
  end_border: number;
}
