/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  ListWikiPagesV1GuildsMeWikiGetParams,
  PageOut
} from '../model';

import { nexuscoreFetcher } from '../../../lib/nexuscore-fetcher.ts';
import type { ErrorType } from '../../../lib/nexuscore-fetcher.ts';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getListWikiPagesV1GuildsMeWikiGetUrl = (params?: ListWikiPagesV1GuildsMeWikiGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["tags"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? 'null' : String(v));
      });
      return;
    }

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/guilds/me/wiki?${stringifiedParams}` : `/v1/guilds/me/wiki`
}

/**
 * Get a list of Wiki Pages
 * @summary List Wiki Pages
 */
export const listWikiPagesV1GuildsMeWikiGet = async (params?: ListWikiPagesV1GuildsMeWikiGetParams, options?: RequestInit): Promise<PageOut[]> => {

  return nexuscoreFetcher<PageOut[]>(getListWikiPagesV1GuildsMeWikiGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListWikiPagesV1GuildsMeWikiGetMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof listWikiPagesV1GuildsMeWikiGet>>, TError,{params?: ListWikiPagesV1GuildsMeWikiGetParams}, TContext>, request?: SecondParameter<typeof nexuscoreFetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof listWikiPagesV1GuildsMeWikiGet>>, TError,{params?: ListWikiPagesV1GuildsMeWikiGetParams}, TContext> => {

const mutationKey = ['listWikiPagesV1GuildsMeWikiGet'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof listWikiPagesV1GuildsMeWikiGet>>, {params?: ListWikiPagesV1GuildsMeWikiGetParams}> = (props) => {
          const {params} = props ?? {};

          return  listWikiPagesV1GuildsMeWikiGet(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ListWikiPagesV1GuildsMeWikiGetMutationResult = NonNullable<Awaited<ReturnType<typeof listWikiPagesV1GuildsMeWikiGet>>>

    export type ListWikiPagesV1GuildsMeWikiGetMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary List Wiki Pages
 */
export const useListWikiPagesV1GuildsMeWikiGet = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof listWikiPagesV1GuildsMeWikiGet>>, TError,{params?: ListWikiPagesV1GuildsMeWikiGetParams}, TContext>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof listWikiPagesV1GuildsMeWikiGet>>,
        TError,
        {params?: ListWikiPagesV1GuildsMeWikiGetParams},
        TContext
      > => {
      return useMutation(getListWikiPagesV1GuildsMeWikiGetMutationOptions(options), queryClient);
    }
    export const getGetWikiPageV1GuildsMeWikiPageIdGetUrl = (pageId: number,) => {




  return `/v1/guilds/me/wiki/${pageId}`
}

/**
 * Returns a wiki page
 * @summary Get Wiki Page
 */
export const getWikiPageV1GuildsMeWikiPageIdGet = async (pageId: number, options?: RequestInit): Promise<PageOut> => {

  return nexuscoreFetcher<PageOut>(getGetWikiPageV1GuildsMeWikiPageIdGetUrl(pageId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetWikiPageV1GuildsMeWikiPageIdGetMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getWikiPageV1GuildsMeWikiPageIdGet>>, TError,{pageId: number}, TContext>, request?: SecondParameter<typeof nexuscoreFetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof getWikiPageV1GuildsMeWikiPageIdGet>>, TError,{pageId: number}, TContext> => {

const mutationKey = ['getWikiPageV1GuildsMeWikiPageIdGet'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getWikiPageV1GuildsMeWikiPageIdGet>>, {pageId: number}> = (props) => {
          const {pageId} = props ?? {};

          return  getWikiPageV1GuildsMeWikiPageIdGet(pageId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetWikiPageV1GuildsMeWikiPageIdGetMutationResult = NonNullable<Awaited<ReturnType<typeof getWikiPageV1GuildsMeWikiPageIdGet>>>

    export type GetWikiPageV1GuildsMeWikiPageIdGetMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Get Wiki Page
 */
export const useGetWikiPageV1GuildsMeWikiPageIdGet = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getWikiPageV1GuildsMeWikiPageIdGet>>, TError,{pageId: number}, TContext>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getWikiPageV1GuildsMeWikiPageIdGet>>,
        TError,
        {pageId: number},
        TContext
      > => {
      return useMutation(getGetWikiPageV1GuildsMeWikiPageIdGetMutationOptions(options), queryClient);
    }
