/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  InvalidateOptions,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  InteractionSummary,
  LookupUserV1GuildsMeUsersLookupGetParams,
  PlaytimeSummary,
  ProfileOut,
  ProfileUpdate,
  UserIn,
  UserOut,
  UserUpdate
} from '../model';

import { nexuscoreFetcher } from '../../../lib/nexuscore-fetcher.ts';
import type { ErrorType } from '../../../lib/nexuscore-fetcher.ts';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getCreateUserV1GuildsMeUsersPostUrl = () => {




  return `/v1/guilds/me/users`
}

/**
 * Creates a new user in the guild.
 * @summary Create User
 */
export const createUserV1GuildsMeUsersPost = async (userIn: UserIn, options?: Parameters<typeof nexuscoreFetcher>[1]): Promise<UserOut> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return nexuscoreFetcher<UserOut>(getCreateUserV1GuildsMeUsersPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(userIn)
  }
);}





export const getCreateUserV1GuildsMeUsersPostQueryKey = (userIn?: UserIn,) => {
    return [
    'POST', `/v1/guilds/me/users`, userIn
    ] as const;
    }


export const getCreateUserV1GuildsMeUsersPostQueryOptions = <TData = Awaited<ReturnType<typeof createUserV1GuildsMeUsersPost>>, TError = ErrorType<HTTPValidationError>>(userIn: UserIn, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createUserV1GuildsMeUsersPost>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCreateUserV1GuildsMeUsersPostQueryKey(userIn);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof createUserV1GuildsMeUsersPost>>> = ({ signal }) => createUserV1GuildsMeUsersPost(userIn, { signal, ...requestOptions });





   return  { queryKey, queryFn,   staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof createUserV1GuildsMeUsersPost>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CreateUserV1GuildsMeUsersPostQueryResult = NonNullable<Awaited<ReturnType<typeof createUserV1GuildsMeUsersPost>>>
export type CreateUserV1GuildsMeUsersPostQueryError = ErrorType<HTTPValidationError>


export function useCreateUserV1GuildsMeUsersPost<TData = Awaited<ReturnType<typeof createUserV1GuildsMeUsersPost>>, TError = ErrorType<HTTPValidationError>>(
 userIn: UserIn, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof createUserV1GuildsMeUsersPost>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof createUserV1GuildsMeUsersPost>>,
          TError,
          Awaited<ReturnType<typeof createUserV1GuildsMeUsersPost>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreateUserV1GuildsMeUsersPost<TData = Awaited<ReturnType<typeof createUserV1GuildsMeUsersPost>>, TError = ErrorType<HTTPValidationError>>(
 userIn: UserIn, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createUserV1GuildsMeUsersPost>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof createUserV1GuildsMeUsersPost>>,
          TError,
          Awaited<ReturnType<typeof createUserV1GuildsMeUsersPost>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreateUserV1GuildsMeUsersPost<TData = Awaited<ReturnType<typeof createUserV1GuildsMeUsersPost>>, TError = ErrorType<HTTPValidationError>>(
 userIn: UserIn, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createUserV1GuildsMeUsersPost>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Create User
 */

export function useCreateUserV1GuildsMeUsersPost<TData = Awaited<ReturnType<typeof createUserV1GuildsMeUsersPost>>, TError = ErrorType<HTTPValidationError>>(
 userIn: UserIn, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createUserV1GuildsMeUsersPost>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCreateUserV1GuildsMeUsersPostQueryOptions(userIn,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}


/**
 * @summary Create User
 */
export const invalidateCreateUserV1GuildsMeUsersPost = async (
 queryClient: QueryClient, userIn: UserIn, options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getCreateUserV1GuildsMeUsersPostQueryKey(userIn) }, options);

  return queryClient;
}




export const getLookupUserV1GuildsMeUsersLookupGetUrl = (params?: LookupUserV1GuildsMeUsersLookupGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/guilds/me/users/lookup?${stringifiedParams}` : `/v1/guilds/me/users/lookup`
}

/**
 * Looks up a guild member by gamertag, whitelisted gamertag, or Discord ID.
 * Exactly one parameter must be provided.
 * @summary Lookup User
 */
export const lookupUserV1GuildsMeUsersLookupGet = async (params?: LookupUserV1GuildsMeUsersLookupGetParams, options?: Parameters<typeof nexuscoreFetcher>[1]): Promise<UserOut> => {

  return nexuscoreFetcher<UserOut>(getLookupUserV1GuildsMeUsersLookupGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getLookupUserV1GuildsMeUsersLookupGetQueryKey = (params?: LookupUserV1GuildsMeUsersLookupGetParams,) => {
    return [
    `/v1/guilds/me/users/lookup`, ...(params ? [params] : [])
    ] as const;
    }


export const getLookupUserV1GuildsMeUsersLookupGetQueryOptions = <TData = Awaited<ReturnType<typeof lookupUserV1GuildsMeUsersLookupGet>>, TError = ErrorType<HTTPValidationError>>(params?: LookupUserV1GuildsMeUsersLookupGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof lookupUserV1GuildsMeUsersLookupGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLookupUserV1GuildsMeUsersLookupGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof lookupUserV1GuildsMeUsersLookupGet>>> = ({ signal }) => lookupUserV1GuildsMeUsersLookupGet(params, { signal, ...requestOptions });





   return  { queryKey, queryFn,   staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof lookupUserV1GuildsMeUsersLookupGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LookupUserV1GuildsMeUsersLookupGetQueryResult = NonNullable<Awaited<ReturnType<typeof lookupUserV1GuildsMeUsersLookupGet>>>
export type LookupUserV1GuildsMeUsersLookupGetQueryError = ErrorType<HTTPValidationError>


export function useLookupUserV1GuildsMeUsersLookupGet<TData = Awaited<ReturnType<typeof lookupUserV1GuildsMeUsersLookupGet>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  LookupUserV1GuildsMeUsersLookupGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof lookupUserV1GuildsMeUsersLookupGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof lookupUserV1GuildsMeUsersLookupGet>>,
          TError,
          Awaited<ReturnType<typeof lookupUserV1GuildsMeUsersLookupGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLookupUserV1GuildsMeUsersLookupGet<TData = Awaited<ReturnType<typeof lookupUserV1GuildsMeUsersLookupGet>>, TError = ErrorType<HTTPValidationError>>(
 params?: LookupUserV1GuildsMeUsersLookupGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof lookupUserV1GuildsMeUsersLookupGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof lookupUserV1GuildsMeUsersLookupGet>>,
          TError,
          Awaited<ReturnType<typeof lookupUserV1GuildsMeUsersLookupGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLookupUserV1GuildsMeUsersLookupGet<TData = Awaited<ReturnType<typeof lookupUserV1GuildsMeUsersLookupGet>>, TError = ErrorType<HTTPValidationError>>(
 params?: LookupUserV1GuildsMeUsersLookupGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof lookupUserV1GuildsMeUsersLookupGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Lookup User
 */

export function useLookupUserV1GuildsMeUsersLookupGet<TData = Awaited<ReturnType<typeof lookupUserV1GuildsMeUsersLookupGet>>, TError = ErrorType<HTTPValidationError>>(
 params?: LookupUserV1GuildsMeUsersLookupGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof lookupUserV1GuildsMeUsersLookupGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getLookupUserV1GuildsMeUsersLookupGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}


/**
 * @summary Lookup User
 */
export const invalidateLookupUserV1GuildsMeUsersLookupGet = async (
 queryClient: QueryClient, params?: LookupUserV1GuildsMeUsersLookupGetParams, options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getLookupUserV1GuildsMeUsersLookupGetQueryKey(params) }, options);

  return queryClient;
}




export const getGetUserV1GuildsMeUsersThornyIdGetUrl = (thornyId: number,) => {




  return `/v1/guilds/me/users/${thornyId}`
}

/**
 * This returns the User object
 * @summary Get User
 */
export const getUserV1GuildsMeUsersThornyIdGet = async (thornyId: number, options?: Parameters<typeof nexuscoreFetcher>[1]): Promise<UserOut> => {

  return nexuscoreFetcher<UserOut>(getGetUserV1GuildsMeUsersThornyIdGetUrl(thornyId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetUserV1GuildsMeUsersThornyIdGetQueryKey = (thornyId: number,) => {
    return [
    `/v1/guilds/me/users/${thornyId}`
    ] as const;
    }


export const getGetUserV1GuildsMeUsersThornyIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getUserV1GuildsMeUsersThornyIdGet>>, TError = ErrorType<HTTPValidationError>>(thornyId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserV1GuildsMeUsersThornyIdGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserV1GuildsMeUsersThornyIdGetQueryKey(thornyId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserV1GuildsMeUsersThornyIdGet>>> = ({ signal }) => getUserV1GuildsMeUsersThornyIdGet(thornyId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: thornyId !== null && thornyId !== undefined,  staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserV1GuildsMeUsersThornyIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserV1GuildsMeUsersThornyIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getUserV1GuildsMeUsersThornyIdGet>>>
export type GetUserV1GuildsMeUsersThornyIdGetQueryError = ErrorType<HTTPValidationError>


export function useGetUserV1GuildsMeUsersThornyIdGet<TData = Awaited<ReturnType<typeof getUserV1GuildsMeUsersThornyIdGet>>, TError = ErrorType<HTTPValidationError>>(
 thornyId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserV1GuildsMeUsersThornyIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserV1GuildsMeUsersThornyIdGet>>,
          TError,
          Awaited<ReturnType<typeof getUserV1GuildsMeUsersThornyIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserV1GuildsMeUsersThornyIdGet<TData = Awaited<ReturnType<typeof getUserV1GuildsMeUsersThornyIdGet>>, TError = ErrorType<HTTPValidationError>>(
 thornyId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserV1GuildsMeUsersThornyIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserV1GuildsMeUsersThornyIdGet>>,
          TError,
          Awaited<ReturnType<typeof getUserV1GuildsMeUsersThornyIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserV1GuildsMeUsersThornyIdGet<TData = Awaited<ReturnType<typeof getUserV1GuildsMeUsersThornyIdGet>>, TError = ErrorType<HTTPValidationError>>(
 thornyId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserV1GuildsMeUsersThornyIdGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get User
 */

export function useGetUserV1GuildsMeUsersThornyIdGet<TData = Awaited<ReturnType<typeof getUserV1GuildsMeUsersThornyIdGet>>, TError = ErrorType<HTTPValidationError>>(
 thornyId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserV1GuildsMeUsersThornyIdGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserV1GuildsMeUsersThornyIdGetQueryOptions(thornyId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}


/**
 * @summary Get User
 */
export const invalidateGetUserV1GuildsMeUsersThornyIdGet = async (
 queryClient: QueryClient, thornyId: number, options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getGetUserV1GuildsMeUsersThornyIdGetQueryKey(thornyId) }, options);

  return queryClient;
}




export const getPartialUpdateUserV1GuildsMeUsersThornyIdPatchUrl = (thornyId: number,) => {




  return `/v1/guilds/me/users/${thornyId}`
}

/**
 * This updates a user. All fields are optional, meaning you may
 * set a field to `null` to not update it.
 *
 * `whitelist` does not apply to this. If you set it to null, it will become null.
 * @summary Partial Update User
 */
export const partialUpdateUserV1GuildsMeUsersThornyIdPatch = async (thornyId: number,
    userUpdate: UserUpdate, options?: Parameters<typeof nexuscoreFetcher>[1]): Promise<UserOut> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return nexuscoreFetcher<UserOut>(getPartialUpdateUserV1GuildsMeUsersThornyIdPatchUrl(thornyId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(userUpdate)
  }
);}





export const getPartialUpdateUserV1GuildsMeUsersThornyIdPatchQueryKey = (thornyId: number,
    userUpdate?: UserUpdate,) => {
    return [
    'PATCH', `/v1/guilds/me/users/${thornyId}`, userUpdate
    ] as const;
    }


export const getPartialUpdateUserV1GuildsMeUsersThornyIdPatchQueryOptions = <TData = Awaited<ReturnType<typeof partialUpdateUserV1GuildsMeUsersThornyIdPatch>>, TError = ErrorType<HTTPValidationError>>(thornyId: number,
    userUpdate: UserUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateUserV1GuildsMeUsersThornyIdPatch>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPartialUpdateUserV1GuildsMeUsersThornyIdPatchQueryKey(thornyId,userUpdate);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof partialUpdateUserV1GuildsMeUsersThornyIdPatch>>> = ({ signal }) => partialUpdateUserV1GuildsMeUsersThornyIdPatch(thornyId,userUpdate, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: thornyId !== null && thornyId !== undefined,  staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof partialUpdateUserV1GuildsMeUsersThornyIdPatch>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PartialUpdateUserV1GuildsMeUsersThornyIdPatchQueryResult = NonNullable<Awaited<ReturnType<typeof partialUpdateUserV1GuildsMeUsersThornyIdPatch>>>
export type PartialUpdateUserV1GuildsMeUsersThornyIdPatchQueryError = ErrorType<HTTPValidationError>


export function usePartialUpdateUserV1GuildsMeUsersThornyIdPatch<TData = Awaited<ReturnType<typeof partialUpdateUserV1GuildsMeUsersThornyIdPatch>>, TError = ErrorType<HTTPValidationError>>(
 thornyId: number,
    userUpdate: UserUpdate, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateUserV1GuildsMeUsersThornyIdPatch>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof partialUpdateUserV1GuildsMeUsersThornyIdPatch>>,
          TError,
          Awaited<ReturnType<typeof partialUpdateUserV1GuildsMeUsersThornyIdPatch>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePartialUpdateUserV1GuildsMeUsersThornyIdPatch<TData = Awaited<ReturnType<typeof partialUpdateUserV1GuildsMeUsersThornyIdPatch>>, TError = ErrorType<HTTPValidationError>>(
 thornyId: number,
    userUpdate: UserUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateUserV1GuildsMeUsersThornyIdPatch>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof partialUpdateUserV1GuildsMeUsersThornyIdPatch>>,
          TError,
          Awaited<ReturnType<typeof partialUpdateUserV1GuildsMeUsersThornyIdPatch>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePartialUpdateUserV1GuildsMeUsersThornyIdPatch<TData = Awaited<ReturnType<typeof partialUpdateUserV1GuildsMeUsersThornyIdPatch>>, TError = ErrorType<HTTPValidationError>>(
 thornyId: number,
    userUpdate: UserUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateUserV1GuildsMeUsersThornyIdPatch>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Partial Update User
 */

export function usePartialUpdateUserV1GuildsMeUsersThornyIdPatch<TData = Awaited<ReturnType<typeof partialUpdateUserV1GuildsMeUsersThornyIdPatch>>, TError = ErrorType<HTTPValidationError>>(
 thornyId: number,
    userUpdate: UserUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateUserV1GuildsMeUsersThornyIdPatch>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPartialUpdateUserV1GuildsMeUsersThornyIdPatchQueryOptions(thornyId,userUpdate,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}


/**
 * @summary Partial Update User
 */
export const invalidatePartialUpdateUserV1GuildsMeUsersThornyIdPatch = async (
 queryClient: QueryClient, thornyId: number,
    userUpdate: UserUpdate, options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getPartialUpdateUserV1GuildsMeUsersThornyIdPatchQueryKey(thornyId,userUpdate) }, options);

  return queryClient;
}




export const getPartialUpdateUserV1GuildsMeUsersThornyIdPutUrl = (thornyId: number,) => {




  return `/v1/guilds/me/users/${thornyId}`
}

/**
 * This updates a user. All fields are optional, meaning you may
 * set a field to `null` to not update it.
 *
 * `whitelist` does not apply to this. If you set it to null, it will become null.
 * @summary Partial Update User
 */
export const partialUpdateUserV1GuildsMeUsersThornyIdPut = async (thornyId: number,
    userUpdate: UserUpdate, options?: Parameters<typeof nexuscoreFetcher>[1]): Promise<UserOut> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return nexuscoreFetcher<UserOut>(getPartialUpdateUserV1GuildsMeUsersThornyIdPutUrl(thornyId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(userUpdate)
  }
);}





export const getPartialUpdateUserV1GuildsMeUsersThornyIdPutQueryKey = (thornyId: number,
    userUpdate?: UserUpdate,) => {
    return [
    'PUT', `/v1/guilds/me/users/${thornyId}`, userUpdate
    ] as const;
    }


export const getPartialUpdateUserV1GuildsMeUsersThornyIdPutQueryOptions = <TData = Awaited<ReturnType<typeof partialUpdateUserV1GuildsMeUsersThornyIdPut>>, TError = ErrorType<HTTPValidationError>>(thornyId: number,
    userUpdate: UserUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateUserV1GuildsMeUsersThornyIdPut>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPartialUpdateUserV1GuildsMeUsersThornyIdPutQueryKey(thornyId,userUpdate);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof partialUpdateUserV1GuildsMeUsersThornyIdPut>>> = ({ signal }) => partialUpdateUserV1GuildsMeUsersThornyIdPut(thornyId,userUpdate, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: thornyId !== null && thornyId !== undefined,  staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof partialUpdateUserV1GuildsMeUsersThornyIdPut>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PartialUpdateUserV1GuildsMeUsersThornyIdPutQueryResult = NonNullable<Awaited<ReturnType<typeof partialUpdateUserV1GuildsMeUsersThornyIdPut>>>
export type PartialUpdateUserV1GuildsMeUsersThornyIdPutQueryError = ErrorType<HTTPValidationError>


export function usePartialUpdateUserV1GuildsMeUsersThornyIdPut<TData = Awaited<ReturnType<typeof partialUpdateUserV1GuildsMeUsersThornyIdPut>>, TError = ErrorType<HTTPValidationError>>(
 thornyId: number,
    userUpdate: UserUpdate, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateUserV1GuildsMeUsersThornyIdPut>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof partialUpdateUserV1GuildsMeUsersThornyIdPut>>,
          TError,
          Awaited<ReturnType<typeof partialUpdateUserV1GuildsMeUsersThornyIdPut>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePartialUpdateUserV1GuildsMeUsersThornyIdPut<TData = Awaited<ReturnType<typeof partialUpdateUserV1GuildsMeUsersThornyIdPut>>, TError = ErrorType<HTTPValidationError>>(
 thornyId: number,
    userUpdate: UserUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateUserV1GuildsMeUsersThornyIdPut>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof partialUpdateUserV1GuildsMeUsersThornyIdPut>>,
          TError,
          Awaited<ReturnType<typeof partialUpdateUserV1GuildsMeUsersThornyIdPut>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePartialUpdateUserV1GuildsMeUsersThornyIdPut<TData = Awaited<ReturnType<typeof partialUpdateUserV1GuildsMeUsersThornyIdPut>>, TError = ErrorType<HTTPValidationError>>(
 thornyId: number,
    userUpdate: UserUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateUserV1GuildsMeUsersThornyIdPut>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Partial Update User
 */

export function usePartialUpdateUserV1GuildsMeUsersThornyIdPut<TData = Awaited<ReturnType<typeof partialUpdateUserV1GuildsMeUsersThornyIdPut>>, TError = ErrorType<HTTPValidationError>>(
 thornyId: number,
    userUpdate: UserUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateUserV1GuildsMeUsersThornyIdPut>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPartialUpdateUserV1GuildsMeUsersThornyIdPutQueryOptions(thornyId,userUpdate,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}


/**
 * @summary Partial Update User
 */
export const invalidatePartialUpdateUserV1GuildsMeUsersThornyIdPut = async (
 queryClient: QueryClient, thornyId: number,
    userUpdate: UserUpdate, options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getPartialUpdateUserV1GuildsMeUsersThornyIdPutQueryKey(thornyId,userUpdate) }, options);

  return queryClient;
}




export const getGetUserProfileV1GuildsMeUsersThornyIdProfileGetUrl = (thornyId: number,) => {




  return `/v1/guilds/me/users/${thornyId}/profile`
}

/**
 * This returns the user's profile.
 *
 * Will be removed in a future release. Use `/users/{thorny_id}` instead.
 * @deprecated
 * @summary Get User Profile
 */
export const getUserProfileV1GuildsMeUsersThornyIdProfileGet = async (thornyId: number, options?: Parameters<typeof nexuscoreFetcher>[1]): Promise<ProfileOut> => {

  return nexuscoreFetcher<ProfileOut>(getGetUserProfileV1GuildsMeUsersThornyIdProfileGetUrl(thornyId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetUserProfileV1GuildsMeUsersThornyIdProfileGetQueryKey = (thornyId: number,) => {
    return [
    `/v1/guilds/me/users/${thornyId}/profile`
    ] as const;
    }


export const getGetUserProfileV1GuildsMeUsersThornyIdProfileGetQueryOptions = <TData = Awaited<ReturnType<typeof getUserProfileV1GuildsMeUsersThornyIdProfileGet>>, TError = ErrorType<HTTPValidationError>>(thornyId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserProfileV1GuildsMeUsersThornyIdProfileGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserProfileV1GuildsMeUsersThornyIdProfileGetQueryKey(thornyId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserProfileV1GuildsMeUsersThornyIdProfileGet>>> = ({ signal }) => getUserProfileV1GuildsMeUsersThornyIdProfileGet(thornyId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: thornyId !== null && thornyId !== undefined,  staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserProfileV1GuildsMeUsersThornyIdProfileGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserProfileV1GuildsMeUsersThornyIdProfileGetQueryResult = NonNullable<Awaited<ReturnType<typeof getUserProfileV1GuildsMeUsersThornyIdProfileGet>>>
export type GetUserProfileV1GuildsMeUsersThornyIdProfileGetQueryError = ErrorType<HTTPValidationError>


export function useGetUserProfileV1GuildsMeUsersThornyIdProfileGet<TData = Awaited<ReturnType<typeof getUserProfileV1GuildsMeUsersThornyIdProfileGet>>, TError = ErrorType<HTTPValidationError>>(
 thornyId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserProfileV1GuildsMeUsersThornyIdProfileGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserProfileV1GuildsMeUsersThornyIdProfileGet>>,
          TError,
          Awaited<ReturnType<typeof getUserProfileV1GuildsMeUsersThornyIdProfileGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserProfileV1GuildsMeUsersThornyIdProfileGet<TData = Awaited<ReturnType<typeof getUserProfileV1GuildsMeUsersThornyIdProfileGet>>, TError = ErrorType<HTTPValidationError>>(
 thornyId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserProfileV1GuildsMeUsersThornyIdProfileGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserProfileV1GuildsMeUsersThornyIdProfileGet>>,
          TError,
          Awaited<ReturnType<typeof getUserProfileV1GuildsMeUsersThornyIdProfileGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserProfileV1GuildsMeUsersThornyIdProfileGet<TData = Awaited<ReturnType<typeof getUserProfileV1GuildsMeUsersThornyIdProfileGet>>, TError = ErrorType<HTTPValidationError>>(
 thornyId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserProfileV1GuildsMeUsersThornyIdProfileGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @deprecated
 * @summary Get User Profile
 */

export function useGetUserProfileV1GuildsMeUsersThornyIdProfileGet<TData = Awaited<ReturnType<typeof getUserProfileV1GuildsMeUsersThornyIdProfileGet>>, TError = ErrorType<HTTPValidationError>>(
 thornyId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserProfileV1GuildsMeUsersThornyIdProfileGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserProfileV1GuildsMeUsersThornyIdProfileGetQueryOptions(thornyId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}


/**
 * @deprecated
 * @summary Get User Profile
 */
export const invalidateGetUserProfileV1GuildsMeUsersThornyIdProfileGet = async (
 queryClient: QueryClient, thornyId: number, options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getGetUserProfileV1GuildsMeUsersThornyIdProfileGetQueryKey(thornyId) }, options);

  return queryClient;
}




export const getPartialUpdateProfileV1GuildsMeUsersThornyIdProfilePatchUrl = (thornyId: number,) => {




  return `/v1/guilds/me/users/${thornyId}/profile`
}

/**
 * This updates a user's profile. Anything set to NULL will be ignored.
 * @summary Partial Update Profile
 */
export const partialUpdateProfileV1GuildsMeUsersThornyIdProfilePatch = async (thornyId: number,
    profileUpdate: ProfileUpdate, options?: Parameters<typeof nexuscoreFetcher>[1]): Promise<ProfileOut> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return nexuscoreFetcher<ProfileOut>(getPartialUpdateProfileV1GuildsMeUsersThornyIdProfilePatchUrl(thornyId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(profileUpdate)
  }
);}





export const getPartialUpdateProfileV1GuildsMeUsersThornyIdProfilePatchQueryKey = (thornyId: number,
    profileUpdate?: ProfileUpdate,) => {
    return [
    'PATCH', `/v1/guilds/me/users/${thornyId}/profile`, profileUpdate
    ] as const;
    }


export const getPartialUpdateProfileV1GuildsMeUsersThornyIdProfilePatchQueryOptions = <TData = Awaited<ReturnType<typeof partialUpdateProfileV1GuildsMeUsersThornyIdProfilePatch>>, TError = ErrorType<HTTPValidationError>>(thornyId: number,
    profileUpdate: ProfileUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateProfileV1GuildsMeUsersThornyIdProfilePatch>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPartialUpdateProfileV1GuildsMeUsersThornyIdProfilePatchQueryKey(thornyId,profileUpdate);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof partialUpdateProfileV1GuildsMeUsersThornyIdProfilePatch>>> = ({ signal }) => partialUpdateProfileV1GuildsMeUsersThornyIdProfilePatch(thornyId,profileUpdate, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: thornyId !== null && thornyId !== undefined,  staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof partialUpdateProfileV1GuildsMeUsersThornyIdProfilePatch>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PartialUpdateProfileV1GuildsMeUsersThornyIdProfilePatchQueryResult = NonNullable<Awaited<ReturnType<typeof partialUpdateProfileV1GuildsMeUsersThornyIdProfilePatch>>>
export type PartialUpdateProfileV1GuildsMeUsersThornyIdProfilePatchQueryError = ErrorType<HTTPValidationError>


export function usePartialUpdateProfileV1GuildsMeUsersThornyIdProfilePatch<TData = Awaited<ReturnType<typeof partialUpdateProfileV1GuildsMeUsersThornyIdProfilePatch>>, TError = ErrorType<HTTPValidationError>>(
 thornyId: number,
    profileUpdate: ProfileUpdate, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateProfileV1GuildsMeUsersThornyIdProfilePatch>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof partialUpdateProfileV1GuildsMeUsersThornyIdProfilePatch>>,
          TError,
          Awaited<ReturnType<typeof partialUpdateProfileV1GuildsMeUsersThornyIdProfilePatch>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePartialUpdateProfileV1GuildsMeUsersThornyIdProfilePatch<TData = Awaited<ReturnType<typeof partialUpdateProfileV1GuildsMeUsersThornyIdProfilePatch>>, TError = ErrorType<HTTPValidationError>>(
 thornyId: number,
    profileUpdate: ProfileUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateProfileV1GuildsMeUsersThornyIdProfilePatch>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof partialUpdateProfileV1GuildsMeUsersThornyIdProfilePatch>>,
          TError,
          Awaited<ReturnType<typeof partialUpdateProfileV1GuildsMeUsersThornyIdProfilePatch>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePartialUpdateProfileV1GuildsMeUsersThornyIdProfilePatch<TData = Awaited<ReturnType<typeof partialUpdateProfileV1GuildsMeUsersThornyIdProfilePatch>>, TError = ErrorType<HTTPValidationError>>(
 thornyId: number,
    profileUpdate: ProfileUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateProfileV1GuildsMeUsersThornyIdProfilePatch>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Partial Update Profile
 */

export function usePartialUpdateProfileV1GuildsMeUsersThornyIdProfilePatch<TData = Awaited<ReturnType<typeof partialUpdateProfileV1GuildsMeUsersThornyIdProfilePatch>>, TError = ErrorType<HTTPValidationError>>(
 thornyId: number,
    profileUpdate: ProfileUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateProfileV1GuildsMeUsersThornyIdProfilePatch>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPartialUpdateProfileV1GuildsMeUsersThornyIdProfilePatchQueryOptions(thornyId,profileUpdate,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}


/**
 * @summary Partial Update Profile
 */
export const invalidatePartialUpdateProfileV1GuildsMeUsersThornyIdProfilePatch = async (
 queryClient: QueryClient, thornyId: number,
    profileUpdate: ProfileUpdate, options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getPartialUpdateProfileV1GuildsMeUsersThornyIdProfilePatchQueryKey(thornyId,profileUpdate) }, options);

  return queryClient;
}




export const getPartialUpdateProfileV1GuildsMeUsersThornyIdProfilePutUrl = (thornyId: number,) => {




  return `/v1/guilds/me/users/${thornyId}/profile`
}

/**
 * This updates a user's profile. Anything set to NULL will be ignored.
 * @summary Partial Update Profile
 */
export const partialUpdateProfileV1GuildsMeUsersThornyIdProfilePut = async (thornyId: number,
    profileUpdate: ProfileUpdate, options?: Parameters<typeof nexuscoreFetcher>[1]): Promise<ProfileOut> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return nexuscoreFetcher<ProfileOut>(getPartialUpdateProfileV1GuildsMeUsersThornyIdProfilePutUrl(thornyId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(profileUpdate)
  }
);}





export const getPartialUpdateProfileV1GuildsMeUsersThornyIdProfilePutQueryKey = (thornyId: number,
    profileUpdate?: ProfileUpdate,) => {
    return [
    'PUT', `/v1/guilds/me/users/${thornyId}/profile`, profileUpdate
    ] as const;
    }


export const getPartialUpdateProfileV1GuildsMeUsersThornyIdProfilePutQueryOptions = <TData = Awaited<ReturnType<typeof partialUpdateProfileV1GuildsMeUsersThornyIdProfilePut>>, TError = ErrorType<HTTPValidationError>>(thornyId: number,
    profileUpdate: ProfileUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateProfileV1GuildsMeUsersThornyIdProfilePut>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPartialUpdateProfileV1GuildsMeUsersThornyIdProfilePutQueryKey(thornyId,profileUpdate);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof partialUpdateProfileV1GuildsMeUsersThornyIdProfilePut>>> = ({ signal }) => partialUpdateProfileV1GuildsMeUsersThornyIdProfilePut(thornyId,profileUpdate, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: thornyId !== null && thornyId !== undefined,  staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof partialUpdateProfileV1GuildsMeUsersThornyIdProfilePut>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PartialUpdateProfileV1GuildsMeUsersThornyIdProfilePutQueryResult = NonNullable<Awaited<ReturnType<typeof partialUpdateProfileV1GuildsMeUsersThornyIdProfilePut>>>
export type PartialUpdateProfileV1GuildsMeUsersThornyIdProfilePutQueryError = ErrorType<HTTPValidationError>


export function usePartialUpdateProfileV1GuildsMeUsersThornyIdProfilePut<TData = Awaited<ReturnType<typeof partialUpdateProfileV1GuildsMeUsersThornyIdProfilePut>>, TError = ErrorType<HTTPValidationError>>(
 thornyId: number,
    profileUpdate: ProfileUpdate, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateProfileV1GuildsMeUsersThornyIdProfilePut>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof partialUpdateProfileV1GuildsMeUsersThornyIdProfilePut>>,
          TError,
          Awaited<ReturnType<typeof partialUpdateProfileV1GuildsMeUsersThornyIdProfilePut>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePartialUpdateProfileV1GuildsMeUsersThornyIdProfilePut<TData = Awaited<ReturnType<typeof partialUpdateProfileV1GuildsMeUsersThornyIdProfilePut>>, TError = ErrorType<HTTPValidationError>>(
 thornyId: number,
    profileUpdate: ProfileUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateProfileV1GuildsMeUsersThornyIdProfilePut>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof partialUpdateProfileV1GuildsMeUsersThornyIdProfilePut>>,
          TError,
          Awaited<ReturnType<typeof partialUpdateProfileV1GuildsMeUsersThornyIdProfilePut>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePartialUpdateProfileV1GuildsMeUsersThornyIdProfilePut<TData = Awaited<ReturnType<typeof partialUpdateProfileV1GuildsMeUsersThornyIdProfilePut>>, TError = ErrorType<HTTPValidationError>>(
 thornyId: number,
    profileUpdate: ProfileUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateProfileV1GuildsMeUsersThornyIdProfilePut>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Partial Update Profile
 */

export function usePartialUpdateProfileV1GuildsMeUsersThornyIdProfilePut<TData = Awaited<ReturnType<typeof partialUpdateProfileV1GuildsMeUsersThornyIdProfilePut>>, TError = ErrorType<HTTPValidationError>>(
 thornyId: number,
    profileUpdate: ProfileUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof partialUpdateProfileV1GuildsMeUsersThornyIdProfilePut>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPartialUpdateProfileV1GuildsMeUsersThornyIdProfilePutQueryOptions(thornyId,profileUpdate,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}


/**
 * @summary Partial Update Profile
 */
export const invalidatePartialUpdateProfileV1GuildsMeUsersThornyIdProfilePut = async (
 queryClient: QueryClient, thornyId: number,
    profileUpdate: ProfileUpdate, options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getPartialUpdateProfileV1GuildsMeUsersThornyIdProfilePutQueryKey(thornyId,profileUpdate) }, options);

  return queryClient;
}




export const getGetUserPlaytimeV1GuildsMeUsersThornyIdPlaytimeGetUrl = (thornyId: number,) => {




  return `/v1/guilds/me/users/${thornyId}/playtime`
}

/**
 * This returns the user's playtime. Note that all playtime is in seconds!
 * @summary Get User Playtime
 */
export const getUserPlaytimeV1GuildsMeUsersThornyIdPlaytimeGet = async (thornyId: number, options?: Parameters<typeof nexuscoreFetcher>[1]): Promise<PlaytimeSummary> => {

  return nexuscoreFetcher<PlaytimeSummary>(getGetUserPlaytimeV1GuildsMeUsersThornyIdPlaytimeGetUrl(thornyId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetUserPlaytimeV1GuildsMeUsersThornyIdPlaytimeGetQueryKey = (thornyId: number,) => {
    return [
    `/v1/guilds/me/users/${thornyId}/playtime`
    ] as const;
    }


export const getGetUserPlaytimeV1GuildsMeUsersThornyIdPlaytimeGetQueryOptions = <TData = Awaited<ReturnType<typeof getUserPlaytimeV1GuildsMeUsersThornyIdPlaytimeGet>>, TError = ErrorType<HTTPValidationError>>(thornyId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserPlaytimeV1GuildsMeUsersThornyIdPlaytimeGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserPlaytimeV1GuildsMeUsersThornyIdPlaytimeGetQueryKey(thornyId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserPlaytimeV1GuildsMeUsersThornyIdPlaytimeGet>>> = ({ signal }) => getUserPlaytimeV1GuildsMeUsersThornyIdPlaytimeGet(thornyId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: thornyId !== null && thornyId !== undefined,  staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserPlaytimeV1GuildsMeUsersThornyIdPlaytimeGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserPlaytimeV1GuildsMeUsersThornyIdPlaytimeGetQueryResult = NonNullable<Awaited<ReturnType<typeof getUserPlaytimeV1GuildsMeUsersThornyIdPlaytimeGet>>>
export type GetUserPlaytimeV1GuildsMeUsersThornyIdPlaytimeGetQueryError = ErrorType<HTTPValidationError>


export function useGetUserPlaytimeV1GuildsMeUsersThornyIdPlaytimeGet<TData = Awaited<ReturnType<typeof getUserPlaytimeV1GuildsMeUsersThornyIdPlaytimeGet>>, TError = ErrorType<HTTPValidationError>>(
 thornyId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserPlaytimeV1GuildsMeUsersThornyIdPlaytimeGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserPlaytimeV1GuildsMeUsersThornyIdPlaytimeGet>>,
          TError,
          Awaited<ReturnType<typeof getUserPlaytimeV1GuildsMeUsersThornyIdPlaytimeGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserPlaytimeV1GuildsMeUsersThornyIdPlaytimeGet<TData = Awaited<ReturnType<typeof getUserPlaytimeV1GuildsMeUsersThornyIdPlaytimeGet>>, TError = ErrorType<HTTPValidationError>>(
 thornyId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserPlaytimeV1GuildsMeUsersThornyIdPlaytimeGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserPlaytimeV1GuildsMeUsersThornyIdPlaytimeGet>>,
          TError,
          Awaited<ReturnType<typeof getUserPlaytimeV1GuildsMeUsersThornyIdPlaytimeGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserPlaytimeV1GuildsMeUsersThornyIdPlaytimeGet<TData = Awaited<ReturnType<typeof getUserPlaytimeV1GuildsMeUsersThornyIdPlaytimeGet>>, TError = ErrorType<HTTPValidationError>>(
 thornyId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserPlaytimeV1GuildsMeUsersThornyIdPlaytimeGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get User Playtime
 */

export function useGetUserPlaytimeV1GuildsMeUsersThornyIdPlaytimeGet<TData = Awaited<ReturnType<typeof getUserPlaytimeV1GuildsMeUsersThornyIdPlaytimeGet>>, TError = ErrorType<HTTPValidationError>>(
 thornyId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserPlaytimeV1GuildsMeUsersThornyIdPlaytimeGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserPlaytimeV1GuildsMeUsersThornyIdPlaytimeGetQueryOptions(thornyId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}


/**
 * @summary Get User Playtime
 */
export const invalidateGetUserPlaytimeV1GuildsMeUsersThornyIdPlaytimeGet = async (
 queryClient: QueryClient, thornyId: number, options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getGetUserPlaytimeV1GuildsMeUsersThornyIdPlaytimeGetQueryKey(thornyId) }, options);

  return queryClient;
}




export const getGetUserInteractionsV1GuildsMeUsersThornyIdInteractionsGetUrl = (thornyId: number,) => {




  return `/v1/guilds/me/users/${thornyId}/interactions`
}

/**
 * This returns the user's interaction summary.
 * This may take long to process, so ensure you have the proper timeouts set.
 * @summary Get User Interactions
 */
export const getUserInteractionsV1GuildsMeUsersThornyIdInteractionsGet = async (thornyId: number, options?: Parameters<typeof nexuscoreFetcher>[1]): Promise<InteractionSummary> => {

  return nexuscoreFetcher<InteractionSummary>(getGetUserInteractionsV1GuildsMeUsersThornyIdInteractionsGetUrl(thornyId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetUserInteractionsV1GuildsMeUsersThornyIdInteractionsGetQueryKey = (thornyId: number,) => {
    return [
    `/v1/guilds/me/users/${thornyId}/interactions`
    ] as const;
    }


export const getGetUserInteractionsV1GuildsMeUsersThornyIdInteractionsGetQueryOptions = <TData = Awaited<ReturnType<typeof getUserInteractionsV1GuildsMeUsersThornyIdInteractionsGet>>, TError = ErrorType<HTTPValidationError>>(thornyId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserInteractionsV1GuildsMeUsersThornyIdInteractionsGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserInteractionsV1GuildsMeUsersThornyIdInteractionsGetQueryKey(thornyId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserInteractionsV1GuildsMeUsersThornyIdInteractionsGet>>> = ({ signal }) => getUserInteractionsV1GuildsMeUsersThornyIdInteractionsGet(thornyId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: thornyId !== null && thornyId !== undefined,  staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserInteractionsV1GuildsMeUsersThornyIdInteractionsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserInteractionsV1GuildsMeUsersThornyIdInteractionsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getUserInteractionsV1GuildsMeUsersThornyIdInteractionsGet>>>
export type GetUserInteractionsV1GuildsMeUsersThornyIdInteractionsGetQueryError = ErrorType<HTTPValidationError>


export function useGetUserInteractionsV1GuildsMeUsersThornyIdInteractionsGet<TData = Awaited<ReturnType<typeof getUserInteractionsV1GuildsMeUsersThornyIdInteractionsGet>>, TError = ErrorType<HTTPValidationError>>(
 thornyId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserInteractionsV1GuildsMeUsersThornyIdInteractionsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserInteractionsV1GuildsMeUsersThornyIdInteractionsGet>>,
          TError,
          Awaited<ReturnType<typeof getUserInteractionsV1GuildsMeUsersThornyIdInteractionsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserInteractionsV1GuildsMeUsersThornyIdInteractionsGet<TData = Awaited<ReturnType<typeof getUserInteractionsV1GuildsMeUsersThornyIdInteractionsGet>>, TError = ErrorType<HTTPValidationError>>(
 thornyId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserInteractionsV1GuildsMeUsersThornyIdInteractionsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserInteractionsV1GuildsMeUsersThornyIdInteractionsGet>>,
          TError,
          Awaited<ReturnType<typeof getUserInteractionsV1GuildsMeUsersThornyIdInteractionsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserInteractionsV1GuildsMeUsersThornyIdInteractionsGet<TData = Awaited<ReturnType<typeof getUserInteractionsV1GuildsMeUsersThornyIdInteractionsGet>>, TError = ErrorType<HTTPValidationError>>(
 thornyId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserInteractionsV1GuildsMeUsersThornyIdInteractionsGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get User Interactions
 */

export function useGetUserInteractionsV1GuildsMeUsersThornyIdInteractionsGet<TData = Awaited<ReturnType<typeof getUserInteractionsV1GuildsMeUsersThornyIdInteractionsGet>>, TError = ErrorType<HTTPValidationError>>(
 thornyId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserInteractionsV1GuildsMeUsersThornyIdInteractionsGet>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserInteractionsV1GuildsMeUsersThornyIdInteractionsGetQueryOptions(thornyId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}


/**
 * @summary Get User Interactions
 */
export const invalidateGetUserInteractionsV1GuildsMeUsersThornyIdInteractionsGet = async (
 queryClient: QueryClient, thornyId: number, options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getGetUserInteractionsV1GuildsMeUsersThornyIdInteractionsGetQueryKey(thornyId) }, options);

  return queryClient;
}




