/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  InvalidateOptions,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BodyGetTokenAuthTokenPost,
  ClientCreateRequest,
  ClientCreateResponse,
  HTTPValidationError,
  TokenResponse
} from '../model';

import { nexuscoreFetcher } from '../../../lib/nexuscore-fetcher.ts';
import type { ErrorType } from '../../../lib/nexuscore-fetcher.ts';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetTokenAuthTokenPostUrl = () => {




  return `/auth/token`
}

/**
 * @summary Get Token
 */
export const getTokenAuthTokenPost = async (bodyGetTokenAuthTokenPost?: BodyGetTokenAuthTokenPost, options?: RequestInit): Promise<TokenResponse> => {
    const formUrlEncoded = new URLSearchParams();
if(bodyGetTokenAuthTokenPost?.grant_type !== undefined) {
 formUrlEncoded.append(`grant_type`, bodyGetTokenAuthTokenPost.grant_type);
 }
if(bodyGetTokenAuthTokenPost?.scope !== undefined) {
 formUrlEncoded.append(`scope`, bodyGetTokenAuthTokenPost.scope);
 }
if(bodyGetTokenAuthTokenPost?.guild_id !== undefined && bodyGetTokenAuthTokenPost.guild_id !== null) {
 formUrlEncoded.append(`guild_id`, bodyGetTokenAuthTokenPost.guild_id.toString())
 }
if(bodyGetTokenAuthTokenPost?.client_id !== undefined && bodyGetTokenAuthTokenPost.client_id !== null) {
 formUrlEncoded.append(`client_id`, bodyGetTokenAuthTokenPost.client_id);
 }
if(bodyGetTokenAuthTokenPost?.client_secret !== undefined && bodyGetTokenAuthTokenPost.client_secret !== null) {
 formUrlEncoded.append(`client_secret`, bodyGetTokenAuthTokenPost.client_secret);
 }

  return nexuscoreFetcher<TokenResponse>(getGetTokenAuthTokenPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded', ...options?.headers },
    body: formUrlEncoded
  }
);}





export const getGetTokenAuthTokenPostQueryKey = (bodyGetTokenAuthTokenPost?: BodyGetTokenAuthTokenPost,) => {
    return [
    'POST', `/auth/token`, bodyGetTokenAuthTokenPost
    ] as const;
    }


export const getGetTokenAuthTokenPostQueryOptions = <TData = Awaited<ReturnType<typeof getTokenAuthTokenPost>>, TError = ErrorType<HTTPValidationError>>(bodyGetTokenAuthTokenPost?: BodyGetTokenAuthTokenPost, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTokenAuthTokenPost>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTokenAuthTokenPostQueryKey(bodyGetTokenAuthTokenPost);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTokenAuthTokenPost>>> = ({ signal }) => getTokenAuthTokenPost(bodyGetTokenAuthTokenPost, { signal, ...requestOptions });





   return  { queryKey, queryFn,   staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTokenAuthTokenPost>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTokenAuthTokenPostQueryResult = NonNullable<Awaited<ReturnType<typeof getTokenAuthTokenPost>>>
export type GetTokenAuthTokenPostQueryError = ErrorType<HTTPValidationError>


export function useGetTokenAuthTokenPost<TData = Awaited<ReturnType<typeof getTokenAuthTokenPost>>, TError = ErrorType<HTTPValidationError>>(
 bodyGetTokenAuthTokenPost: undefined |  BodyGetTokenAuthTokenPost, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTokenAuthTokenPost>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTokenAuthTokenPost>>,
          TError,
          Awaited<ReturnType<typeof getTokenAuthTokenPost>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTokenAuthTokenPost<TData = Awaited<ReturnType<typeof getTokenAuthTokenPost>>, TError = ErrorType<HTTPValidationError>>(
 bodyGetTokenAuthTokenPost?: BodyGetTokenAuthTokenPost, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTokenAuthTokenPost>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTokenAuthTokenPost>>,
          TError,
          Awaited<ReturnType<typeof getTokenAuthTokenPost>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTokenAuthTokenPost<TData = Awaited<ReturnType<typeof getTokenAuthTokenPost>>, TError = ErrorType<HTTPValidationError>>(
 bodyGetTokenAuthTokenPost?: BodyGetTokenAuthTokenPost, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTokenAuthTokenPost>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Token
 */

export function useGetTokenAuthTokenPost<TData = Awaited<ReturnType<typeof getTokenAuthTokenPost>>, TError = ErrorType<HTTPValidationError>>(
 bodyGetTokenAuthTokenPost?: BodyGetTokenAuthTokenPost, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTokenAuthTokenPost>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTokenAuthTokenPostQueryOptions(bodyGetTokenAuthTokenPost,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}


/**
 * @summary Get Token
 */
export const invalidateGetTokenAuthTokenPost = async (
 queryClient: QueryClient, bodyGetTokenAuthTokenPost?: BodyGetTokenAuthTokenPost, options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getGetTokenAuthTokenPostQueryKey(bodyGetTokenAuthTokenPost) }, options);

  return queryClient;
}




export const getRegisterClientAuthClientsPostUrl = () => {




  return `/auth/clients`
}

/**
 * Master-tier clients only. Creates a guild-scoped API key.
 * @summary Register Client
 */
export const registerClientAuthClientsPost = async (clientCreateRequest: ClientCreateRequest, options?: RequestInit): Promise<ClientCreateResponse> => {

  return nexuscoreFetcher<ClientCreateResponse>(getRegisterClientAuthClientsPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(clientCreateRequest)
  }
);}





export const getRegisterClientAuthClientsPostQueryKey = (clientCreateRequest?: ClientCreateRequest,) => {
    return [
    'POST', `/auth/clients`, clientCreateRequest
    ] as const;
    }


export const getRegisterClientAuthClientsPostQueryOptions = <TData = Awaited<ReturnType<typeof registerClientAuthClientsPost>>, TError = ErrorType<HTTPValidationError>>(clientCreateRequest: ClientCreateRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registerClientAuthClientsPost>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRegisterClientAuthClientsPostQueryKey(clientCreateRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof registerClientAuthClientsPost>>> = ({ signal }) => registerClientAuthClientsPost(clientCreateRequest, { signal, ...requestOptions });





   return  { queryKey, queryFn,   staleTime: 300000, gcTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof registerClientAuthClientsPost>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RegisterClientAuthClientsPostQueryResult = NonNullable<Awaited<ReturnType<typeof registerClientAuthClientsPost>>>
export type RegisterClientAuthClientsPostQueryError = ErrorType<HTTPValidationError>


export function useRegisterClientAuthClientsPost<TData = Awaited<ReturnType<typeof registerClientAuthClientsPost>>, TError = ErrorType<HTTPValidationError>>(
 clientCreateRequest: ClientCreateRequest, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof registerClientAuthClientsPost>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof registerClientAuthClientsPost>>,
          TError,
          Awaited<ReturnType<typeof registerClientAuthClientsPost>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRegisterClientAuthClientsPost<TData = Awaited<ReturnType<typeof registerClientAuthClientsPost>>, TError = ErrorType<HTTPValidationError>>(
 clientCreateRequest: ClientCreateRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registerClientAuthClientsPost>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof registerClientAuthClientsPost>>,
          TError,
          Awaited<ReturnType<typeof registerClientAuthClientsPost>>
        > , 'initialData'
      >, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRegisterClientAuthClientsPost<TData = Awaited<ReturnType<typeof registerClientAuthClientsPost>>, TError = ErrorType<HTTPValidationError>>(
 clientCreateRequest: ClientCreateRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registerClientAuthClientsPost>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Register Client
 */

export function useRegisterClientAuthClientsPost<TData = Awaited<ReturnType<typeof registerClientAuthClientsPost>>, TError = ErrorType<HTTPValidationError>>(
 clientCreateRequest: ClientCreateRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registerClientAuthClientsPost>>, TError, TData>>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getRegisterClientAuthClientsPostQueryOptions(clientCreateRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}


/**
 * @summary Register Client
 */
export const invalidateRegisterClientAuthClientsPost = async (
 queryClient: QueryClient, clientCreateRequest: ClientCreateRequest, options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getRegisterClientAuthClientsPostQueryKey(clientCreateRequest) }, options);

  return queryClient;
}




