import type { Icon } from '@phosphor-icons/react'
import {
    Trophy as TrophyIcon,
    Medal as MedalIcon,
    Star as StarIcon,
    Crown as CrownIcon,
    Sword as SwordIcon,
    Shield as ShieldIcon,
    Lightning as LightningIcon,
    Fire as FireIcon,
    Skull as SkullIcon,
    Heart as HeartIcon,
    Diamond as DiamondIcon,
    Gem as GemIcon,
    Coin as CoinIcon,
    Globe as GlobeIcon,
    Users as UsersIcon,
    User as UserIcon,
    Clock as ClockIcon,
    Calendar as CalendarIcon,
    MapPin as MapPinIcon,
    Flag as FlagIcon,
    Target as TargetIcon,
    Crosshair as CrosshairIcon,
    Hammer as HammerIcon,
    Axe as AxeIcon,
    Bow as BowIcon,
    Sparkle as SparkleIcon,
    Question as QuestionIcon,
    Info as InfoIcon,
    Warning as WarningIcon,
    CheckCircle as CheckCircleIcon,
    XCircle as XCircleIcon,
    ArrowRight as ArrowRightIcon,
    ArrowLeft as ArrowLeftIcon,
    GameController as GameControllerIcon,
    Scroll as ScrollIcon,
    Book as BookIcon,
    Confetti as ConfettiIcon,
    Gift as GiftIcon,
    Ticket as TicketIcon,
    Campfire as CampfireIcon,
    Hourglass as HourglassIcon,
    Rocket as RocketIcon,
    Planet as PlanetIcon,
    Mountains as MountainsIcon,
    Tree as TreeIcon,
    Waves as WavesIcon,
    Snowflake as SnowflakeIcon,
    Sun as SunIcon,
    Moon as MoonIcon,
    Wind as WindIcon,
    Drop as DropIcon,
    Leaf as LeafIcon,
    Flower as FlowerIcon,
    Butterfly as ButterflyIcon,
    Cat as CatIcon,
    Dog as DogIcon,
    Horse as HorseIcon,
    Bird as BirdIcon,
    Fish as FishIcon,
    Bug as BugIcon,
    Alien as AlienIcon,
    Robot as RobotIcon,
    Ghost as GhostIcon,
    Wizard as WizardIcon,
    Sword as BladeSwordIcon,
    HandFist as HandFistIcon,
    PersonArmsSpread as PersonArmsSpreadIcon,
    Buildings as BuildingsIcon,
    Castle as CastleIcon,
    Tent as TentIcon,
    House as HouseIcon,
    Number1 as Number1Icon,
    Number2 as Number2Icon,
    Number3 as Number3Icon,
} from '@phosphor-icons/react'

const iconMap: Record<string, Icon> = {
    TrophyIcon,
    MedalIcon,
    StarIcon,
    CrownIcon,
    SwordIcon,
    ShieldIcon,
    LightningIcon,
    FireIcon,
    SkullIcon,
    HeartIcon,
    DiamondIcon,
    GemIcon,
    CoinIcon,
    GlobeIcon,
    UsersIcon,
    UserIcon,
    ClockIcon,
    CalendarIcon,
    MapPinIcon,
    FlagIcon,
    TargetIcon,
    CrosshairIcon,
    HammerIcon,
    AxeIcon,
    BowIcon,
    SparkleIcon,
    QuestionIcon,
    InfoIcon,
    WarningIcon,
    CheckCircleIcon,
    XCircleIcon,
    ArrowRightIcon,
    ArrowLeftIcon,
    GameControllerIcon,
    ScrollIcon,
    BookIcon,
    ConfettiIcon,
    GiftIcon,
    TicketIcon,
    CampfireIcon,
    HourglassIcon,
    RocketIcon,
    PlanetIcon,
    MountainsIcon,
    TreeIcon,
    WavesIcon,
    SnowflakeIcon,
    SunIcon,
    MoonIcon,
    WindIcon,
    DropIcon,
    LeafIcon,
    FlowerIcon,
    ButterflyIcon,
    CatIcon,
    DogIcon,
    HorseIcon,
    BirdIcon,
    FishIcon,
    BugIcon,
    AlienIcon,
    RobotIcon,
    GhostIcon,
    WizardIcon,
    BladeSwordIcon,
    HandFistIcon,
    PersonArmsSpreadIcon,
    BuildingsIcon,
    CastleIcon,
    TentIcon,
    HouseIcon,
    Number1Icon,
    Number2Icon,
    Number3Icon,
}

interface IconResolverProps {
    name: string
    className?: string
    weight?: 'thin' | 'light' | 'regular' | 'bold' | 'fill' | 'duotone'
    size?: number
}

export function resolveIcon(name: string): Icon {
    return iconMap[name] ?? QuestionIcon
}

export function IconResolver({ name, className, weight = 'duotone', size }: IconResolverProps) {
    const ResolvedIcon = resolveIcon(name)
    return <ResolvedIcon className={className} weight={weight} size={size} />
}
