/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Nexuscore
 * The backend for all Everthorn internal services
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  LeaderboardModel
} from '../model';

import { nexuscoreFetcher } from '../../../lib/nexuscore-fetcher.ts';
import type { ErrorType } from '../../../lib/nexuscore-fetcher.ts';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getGetPlaytimeLeaderboardV1GuildsMeLeaderboardPlaytimeMonthGetUrl = (month: string,) => {




  return `/v1/guilds/me/leaderboard/playtime/${month}`
}

/**
 * Returns the guild's playtime leaderboard, in order. Playtime is in seconds.
 * @summary Get Playtime Leaderboard
 */
export const getPlaytimeLeaderboardV1GuildsMeLeaderboardPlaytimeMonthGet = async (month: string, options?: RequestInit): Promise<LeaderboardModel> => {

  return nexuscoreFetcher<LeaderboardModel>(getGetPlaytimeLeaderboardV1GuildsMeLeaderboardPlaytimeMonthGetUrl(month),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPlaytimeLeaderboardV1GuildsMeLeaderboardPlaytimeMonthGetMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getPlaytimeLeaderboardV1GuildsMeLeaderboardPlaytimeMonthGet>>, TError,{month: string}, TContext>, request?: SecondParameter<typeof nexuscoreFetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof getPlaytimeLeaderboardV1GuildsMeLeaderboardPlaytimeMonthGet>>, TError,{month: string}, TContext> => {

const mutationKey = ['getPlaytimeLeaderboardV1GuildsMeLeaderboardPlaytimeMonthGet'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getPlaytimeLeaderboardV1GuildsMeLeaderboardPlaytimeMonthGet>>, {month: string}> = (props) => {
          const {month} = props ?? {};

          return  getPlaytimeLeaderboardV1GuildsMeLeaderboardPlaytimeMonthGet(month,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetPlaytimeLeaderboardV1GuildsMeLeaderboardPlaytimeMonthGetMutationResult = NonNullable<Awaited<ReturnType<typeof getPlaytimeLeaderboardV1GuildsMeLeaderboardPlaytimeMonthGet>>>

    export type GetPlaytimeLeaderboardV1GuildsMeLeaderboardPlaytimeMonthGetMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Get Playtime Leaderboard
 */
export const useGetPlaytimeLeaderboardV1GuildsMeLeaderboardPlaytimeMonthGet = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getPlaytimeLeaderboardV1GuildsMeLeaderboardPlaytimeMonthGet>>, TError,{month: string}, TContext>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getPlaytimeLeaderboardV1GuildsMeLeaderboardPlaytimeMonthGet>>,
        TError,
        {month: string},
        TContext
      > => {
      return useMutation(getGetPlaytimeLeaderboardV1GuildsMeLeaderboardPlaytimeMonthGetMutationOptions(options), queryClient);
    }
    export const getGetCurrencyLeaderboardV1GuildsMeLeaderboardCurrencyGetUrl = () => {




  return `/v1/guilds/me/leaderboard/currency`
}

/**
 * Returns the guild's currency leaderboard, in order.
 * @summary Get Currency Leaderboard
 */
export const getCurrencyLeaderboardV1GuildsMeLeaderboardCurrencyGet = async ( options?: RequestInit): Promise<LeaderboardModel> => {

  return nexuscoreFetcher<LeaderboardModel>(getGetCurrencyLeaderboardV1GuildsMeLeaderboardCurrencyGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCurrencyLeaderboardV1GuildsMeLeaderboardCurrencyGetMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getCurrencyLeaderboardV1GuildsMeLeaderboardCurrencyGet>>, TError,void, TContext>, request?: SecondParameter<typeof nexuscoreFetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof getCurrencyLeaderboardV1GuildsMeLeaderboardCurrencyGet>>, TError,void, TContext> => {

const mutationKey = ['getCurrencyLeaderboardV1GuildsMeLeaderboardCurrencyGet'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getCurrencyLeaderboardV1GuildsMeLeaderboardCurrencyGet>>, void> = () => {


          return  getCurrencyLeaderboardV1GuildsMeLeaderboardCurrencyGet(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetCurrencyLeaderboardV1GuildsMeLeaderboardCurrencyGetMutationResult = NonNullable<Awaited<ReturnType<typeof getCurrencyLeaderboardV1GuildsMeLeaderboardCurrencyGet>>>

    export type GetCurrencyLeaderboardV1GuildsMeLeaderboardCurrencyGetMutationError = ErrorType<unknown>

    /**
 * @summary Get Currency Leaderboard
 */
export const useGetCurrencyLeaderboardV1GuildsMeLeaderboardCurrencyGet = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getCurrencyLeaderboardV1GuildsMeLeaderboardCurrencyGet>>, TError,void, TContext>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getCurrencyLeaderboardV1GuildsMeLeaderboardCurrencyGet>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getGetCurrencyLeaderboardV1GuildsMeLeaderboardCurrencyGetMutationOptions(options), queryClient);
    }
    export const getGetLevelsLeaderboardV1GuildsMeLeaderboardLevelsGetUrl = () => {




  return `/v1/guilds/me/leaderboard/levels`
}

/**
 * Returns the guild's playtime leaderboard, in order. Playtime is in seconds.
 * @summary Get Levels Leaderboard
 */
export const getLevelsLeaderboardV1GuildsMeLeaderboardLevelsGet = async ( options?: RequestInit): Promise<LeaderboardModel> => {

  return nexuscoreFetcher<LeaderboardModel>(getGetLevelsLeaderboardV1GuildsMeLeaderboardLevelsGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetLevelsLeaderboardV1GuildsMeLeaderboardLevelsGetMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getLevelsLeaderboardV1GuildsMeLeaderboardLevelsGet>>, TError,void, TContext>, request?: SecondParameter<typeof nexuscoreFetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof getLevelsLeaderboardV1GuildsMeLeaderboardLevelsGet>>, TError,void, TContext> => {

const mutationKey = ['getLevelsLeaderboardV1GuildsMeLeaderboardLevelsGet'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getLevelsLeaderboardV1GuildsMeLeaderboardLevelsGet>>, void> = () => {


          return  getLevelsLeaderboardV1GuildsMeLeaderboardLevelsGet(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetLevelsLeaderboardV1GuildsMeLeaderboardLevelsGetMutationResult = NonNullable<Awaited<ReturnType<typeof getLevelsLeaderboardV1GuildsMeLeaderboardLevelsGet>>>

    export type GetLevelsLeaderboardV1GuildsMeLeaderboardLevelsGetMutationError = ErrorType<unknown>

    /**
 * @summary Get Levels Leaderboard
 */
export const useGetLevelsLeaderboardV1GuildsMeLeaderboardLevelsGet = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getLevelsLeaderboardV1GuildsMeLeaderboardLevelsGet>>, TError,void, TContext>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getLevelsLeaderboardV1GuildsMeLeaderboardLevelsGet>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getGetLevelsLeaderboardV1GuildsMeLeaderboardLevelsGetMutationOptions(options), queryClient);
    }
    export const getGetQuestsLeaderboardV1GuildsMeLeaderboardQuestsGetUrl = () => {




  return `/v1/guilds/me/leaderboard/quests`
}

/**
 * Returns the guild's playtime leaderboard, in order. Playtime is in seconds.
 * @summary Get Quests Leaderboard
 */
export const getQuestsLeaderboardV1GuildsMeLeaderboardQuestsGet = async ( options?: RequestInit): Promise<LeaderboardModel> => {

  return nexuscoreFetcher<LeaderboardModel>(getGetQuestsLeaderboardV1GuildsMeLeaderboardQuestsGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetQuestsLeaderboardV1GuildsMeLeaderboardQuestsGetMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getQuestsLeaderboardV1GuildsMeLeaderboardQuestsGet>>, TError,void, TContext>, request?: SecondParameter<typeof nexuscoreFetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof getQuestsLeaderboardV1GuildsMeLeaderboardQuestsGet>>, TError,void, TContext> => {

const mutationKey = ['getQuestsLeaderboardV1GuildsMeLeaderboardQuestsGet'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getQuestsLeaderboardV1GuildsMeLeaderboardQuestsGet>>, void> = () => {


          return  getQuestsLeaderboardV1GuildsMeLeaderboardQuestsGet(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetQuestsLeaderboardV1GuildsMeLeaderboardQuestsGetMutationResult = NonNullable<Awaited<ReturnType<typeof getQuestsLeaderboardV1GuildsMeLeaderboardQuestsGet>>>

    export type GetQuestsLeaderboardV1GuildsMeLeaderboardQuestsGetMutationError = ErrorType<unknown>

    /**
 * @summary Get Quests Leaderboard
 */
export const useGetQuestsLeaderboardV1GuildsMeLeaderboardQuestsGet = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getQuestsLeaderboardV1GuildsMeLeaderboardQuestsGet>>, TError,void, TContext>, request?: SecondParameter<typeof nexuscoreFetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getQuestsLeaderboardV1GuildsMeLeaderboardQuestsGet>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getGetQuestsLeaderboardV1GuildsMeLeaderboardQuestsGetMutationOptions(options), queryClient);
    }
